const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const RULESET_VERSION='2.0-known-good-2026-10-08';
const AD_HOSTS=['doubleclick.net','googlesyndication.com','googleadservices.com','adsterra.com','adsterra.org','popads.net','popcash.net','propellerads.com','onclicka.com','onclicksuper.com','exoclick.com','exosrv.com','trafficjunky.net','juicyads.com','hilltopads.net','a-ads.com','adnxs.com','adskeeper.com','mgid.com','taboola.com','outbrain.com','gurlleviter.cyou'];
const PROVIDER_ALLOWLIST=['vidstuck.xyz','vidsrc.sh','cloudflarestream.com','videodelivery.net','cloudfront.net','akamaized.net','akamaihd.net','fastly.net','b-cdn.net','cdn77.org','googlevideo.com','r2.dev','challenges.cloudflare.com'];
const LEARNED_TTL=7*24*60*60*1000;
const sessionAdHosts=new Set(),learnedAdHosts=new Map(),lastBlockLog=new Map();
const persistenceEnabled=!!process.versions?.electron;
let adRoot='',learnedFile='',debugFile='',lastLearnedCheck=0,lastLearnedMtime=0;
if(persistenceEnabled){try{const base=process.env.APPDATA||path.join(os.homedir(),'AppData','Roaming');adRoot=require('./data-directory.cjs').dataDirectory(base);fs.mkdirSync(adRoot,{recursive:true});learnedFile=path.join(adRoot,'adblock-learned-v2.json');debugFile=path.join(adRoot,'adblock-debug-v2.log');}catch{adRoot='';learnedFile='';debugFile='';}}
function normalHost(host){return String(host||'').trim().toLowerCase().replace(/\.+$/,'');}
function domainMatch(host,domain){return host===domain||host.endsWith('.'+domain);}
function providerAllowed(host){host=normalHost(host);return !!host&&PROVIDER_ALLOWLIST.some(domain=>domainMatch(host,domain));}
function debugAd(event,host,rule){if(!debugFile)return;try{const line=`${Date.now()}|${RULESET_VERSION}|${event}|${host||'-'}|${rule||'-'}\n`;fs.appendFileSync(debugFile,line);const stat=fs.statSync(debugFile);if(stat.size>65536){const data=fs.readFileSync(debugFile);fs.writeFileSync(debugFile,data.subarray(Math.max(0,data.length-49152)));}}catch{}}
function persistLearned(){if(!learnedFile)return;try{const now=Date.now(),hosts={};for(const [host,expiry] of learnedAdHosts)if(expiry>now&&!providerAllowed(host))hosts[host]=expiry;const temp=learnedFile+'.tmp';fs.writeFileSync(temp,JSON.stringify({ruleset:RULESET_VERSION,hosts}));fs.renameSync(temp,learnedFile);lastLearnedMtime=fs.statSync(learnedFile).mtimeMs;}catch{}}
function refreshLearned(force=false){if(!learnedFile)return;const now=Date.now();if(!force&&now-lastLearnedCheck<500)return;lastLearnedCheck=now;try{if(!fs.existsSync(learnedFile))return;const stat=fs.statSync(learnedFile);if(!force&&stat.mtimeMs===lastLearnedMtime)return;lastLearnedMtime=stat.mtimeMs;const parsed=JSON.parse(fs.readFileSync(learnedFile,'utf8'));learnedAdHosts.clear();for(const [host,expiry] of Object.entries(parsed.hosts||{})){const normalized=normalHost(host),until=Number(expiry)||0;if(normalized&&until>now&&!providerAllowed(normalized))learnedAdHosts.set(normalized,until);}persistLearned();}catch{}}
function pruneLearned(){const now=Date.now();let changed=false;for(const [host,expiry] of learnedAdHosts)if(expiry<=now||providerAllowed(host)){learnedAdHosts.delete(host);changed=true;}if(changed)persistLearned();}
function learnAdHost(host,reason='qr-confirmed'){host=normalHost(host);if(!host||providerAllowed(host))return false;refreshLearned();sessionAdHosts.add(host);learnedAdHosts.set(host,Date.now()+LEARNED_TTL);persistLearned();debugAd('confirmed-host',host,reason);return true;}
function blockReason(host){host=normalHost(host);if(!host||providerAllowed(host))return null;refreshLearned();pruneLearned();if(sessionAdHosts.has(host))return 'session-quarantine';const expiry=learnedAdHosts.get(host);if(expiry&&expiry>Date.now())return 'temporary-learned';const domain=AD_HOSTS.find(rule=>domainMatch(host,rule));return domain?'static:'+domain:null;}
function blocked(host){host=normalHost(host);const reason=blockReason(host);if(!reason)return false;const key=host+'|'+reason,now=Date.now(),previous=lastBlockLog.get(key)||0;if(now-previous>5000){lastBlockLog.set(key,now);debugAd('blocked',host,reason);}return true;}
function adQr(value){try{const u=new URL(value);if(u.protocol!=='https:'||providerAllowed(u.hostname))return false;const reason=blockReason(u.hostname),fingerprint=u.hostname.endsWith('.cyou')&&/^\/ri\/\d+\/?$/.test(u.pathname)&&/^[a-f\d-]{16,80}$/i.test(u.searchParams.get('uuid')||'');const confirmed=!!reason||fingerprint;if(confirmed)learnAdHost(u.hostname,reason?'qr-static-confirmed':'qr-fingerprint-confirmed');return confirmed;}catch{return false;}}
function item(raw,type){type=type||raw.media_type;if(!['movie','tv'].includes(type)||raw.adult||!Number.isSafeInteger(Number(raw.id))||Number(raw.id)<1)return null;return {id:Number(raw.id),type,title:String(raw.title||raw.name||'Untitled').slice(0,300),overview:String(raw.overview||'').slice(0,10000),poster:art(raw.poster_path,'w500'),backdrop:art(raw.backdrop_path,'w1280'),date:String(raw.release_date||raw.first_air_date||''),rating:Number(raw.vote_average)||0};}
function art(pathValue,size='w185'){return /^\/[A-Za-z\d_.-]+$/.test(pathValue||'')?`https://image.tmdb.org/t/p/${size}${pathValue}`:'';}
function cleanItem(value){if(!value||!['movie','tv'].includes(value.type)||!Number.isSafeInteger(value.id)||value.id<1)throw Error('Invalid title');const clean={id:value.id,type:value.type,title:String(value.title||'Untitled').slice(0,300),overview:String(value.overview||'').slice(0,10000),date:String(value.date||'').slice(0,10),rating:Math.max(0,Math.min(10,Number(value.rating)||0))};for(const key of ['poster','backdrop'])clean[key]=/^https:\/\/image\.tmdb\.org\/t\/p\/(w342|w500|w1280)\/[A-Za-z\d_.-]+$/.test(value[key]||'')?value[key]:'';return clean;}
function key(value){return `${value.type}:${value.id}`;}
function episode(value){return {season:Number.isSafeInteger(value?.season)&&value.season>=0&&value.season<=1000?value.season:1,episode:Number.isSafeInteger(value?.episode)&&value.episode>=1&&value.episode<=10000?value.episode:1};}
function progress(data,current){if(!data||String(data.id)!==String(current.id)||data.type!==current.type)return null;const ts=Number(data.timestamp),duration=Number(data.duration);if(!Number.isFinite(ts)||!Number.isFinite(duration)||ts<0||duration<=0||duration>604800||ts>duration+10)return null;if(current.type==='tv'&&(!Number.isSafeInteger(Number(data.season))||Number(data.season)<0||Number(data.season)>1000||!Number.isSafeInteger(Number(data.episode))||Number(data.episode)<1||Number(data.episode)>10000))return null;return {...episode(data),timestamp:Math.min(ts,duration),duration,percent:Math.min(100,Math.max(0,ts/duration*100))};}
function playerUrl(value,position,provider){return require('./playback-sources.cjs').url(cleanItem(value),position,provider);}
function endpoint(route){return typeof route==='string'&&(/^\/(trending\/all\/week|movie\/(popular|top_rated|now_playing|upcoming)|tv\/popular|search\/multi|watch\/providers\/(movie|tv)|discover\/(movie|tv)|genre\/(movie|tv)\/list)$/.test(route)||/^\/(movie|tv)\/[1-9]\d{0,9}(\/season\/\d{1,4})?$/.test(route)||/^\/person\/[1-9]\d{0,9}\/combined_credits$/.test(route));}
function record(state,value,position={}){value=cleanItem(value);const ep=episode(position),id=key(value);const historyKey=id+(value.type==='tv'?`:${ep.season}:${ep.episode}`:'');let old=state.history.find(row=>row.historyKey===historyKey);let row={...value,...(old||{}),...position,...ep,historyKey,at:Date.now()};if(old?.percent>=95&&!position.duration)row={...value,...ep,historyKey,at:Date.now(),timestamp:0,duration:0,percent:0};state.history=[row,...state.history.filter(x=>x.historyKey!==historyKey)].slice(0,100);state.positions[id]={...row};return row;}
if(process.versions?.electron)require('./updater.cjs').install();
refreshLearned(true);
module.exports={RULESET_VERSION,providerAllowed,learnAdHost,blockReason,blocked,adQr,item,art,cleanItem,key,episode,progress,playerUrl,endpoint,record};
