const AD_HOSTS=['doubleclick.net','googlesyndication.com','googleadservices.com','adsterra.com','adsterra.org','popads.net','popcash.net','propellerads.com','onclicka.com','onclicksuper.com','exoclick.com','exosrv.com','trafficjunky.net','juicyads.com','hilltopads.net','a-ads.com','adnxs.com','adskeeper.com','mgid.com','taboola.com','outbrain.com','gurlleviter.cyou'];
function blocked(host){host=String(host||'').toLowerCase().replace(/\.+$/,'');return AD_HOSTS.some(domain=>host===domain||host.endsWith('.'+domain));}
function adQr(value){try{const u=new URL(value);return u.protocol==='https:'&&(blocked(u.hostname)||(u.hostname.endsWith('.cyou')&&/^\/ri\/\d+\/?$/.test(u.pathname)&&/^[a-f\d-]{16,80}$/i.test(u.searchParams.get('uuid')||'')));}catch{return false;}}
function item(raw,type){type=type||raw.media_type;if(!['movie','tv'].includes(type)||raw.adult||!Number.isSafeInteger(Number(raw.id))||Number(raw.id)<1)return null;return {id:Number(raw.id),type,title:String(raw.title||raw.name||'Untitled').slice(0,300),overview:String(raw.overview||'').slice(0,10000),poster:art(raw.poster_path,'w500'),backdrop:art(raw.backdrop_path,'w1280'),date:String(raw.release_date||raw.first_air_date||''),rating:Number(raw.vote_average)||0};}
function art(path,size='w185'){return /^\/[A-Za-z\d_.-]+$/.test(path||'')?`https://image.tmdb.org/t/p/${size}${path}`:'';}
function cleanItem(value){if(!value||!['movie','tv'].includes(value.type)||!Number.isSafeInteger(value.id)||value.id<1)throw Error('Invalid title');const clean={id:value.id,type:value.type,title:String(value.title||'Untitled').slice(0,300),overview:String(value.overview||'').slice(0,10000),date:String(value.date||'').slice(0,10),rating:Math.max(0,Math.min(10,Number(value.rating)||0))};for(const key of ['poster','backdrop'])clean[key]=/^https:\/\/image\.tmdb\.org\/t\/p\/(w342|w500|w1280)\/[A-Za-z\d_.-]+$/.test(value[key]||'')?value[key]:'';return clean;}
function key(value){return `${value.type}:${value.id}`;}
function episode(value){return {season:Number.isSafeInteger(value?.season)&&value.season>=0&&value.season<=1000?value.season:1,episode:Number.isSafeInteger(value?.episode)&&value.episode>=1&&value.episode<=10000?value.episode:1};}
function progress(data,current){if(!data||String(data.id)!==String(current.id)||data.type!==current.type)return null;const ts=Number(data.timestamp),duration=Number(data.duration);if(!Number.isFinite(ts)||!Number.isFinite(duration)||ts<0||duration<=0||duration>604800||ts>duration+10)return null;if(current.type==='tv'&&(!Number.isSafeInteger(Number(data.season))||Number(data.season)<0||Number(data.season)>1000||!Number.isSafeInteger(Number(data.episode))||Number(data.episode)<1||Number(data.episode)>10000))return null;return {...episode(data),timestamp:Math.min(ts,duration),duration,percent:Math.min(100,Math.max(0,ts/duration*100))};}
function playerUrl(value,position,provider){return require('./playback-sources.cjs').url(cleanItem(value),position,provider);}
function endpoint(path){return typeof path==='string'&&(/^\/(trending\/all\/week|movie\/(popular|top_rated|now_playing|upcoming)|tv\/popular|search\/multi|watch\/providers\/(movie|tv)|discover\/(movie|tv)|genre\/(movie|tv)\/list)$/.test(path)||/^\/(movie|tv)\/[1-9]\d{0,9}(\/season\/\d{1,4})?$/.test(path));}
function record(state,value,position={}){value=cleanItem(value);const ep=episode(position),id=key(value);const historyKey=id+(value.type==='tv'?`:${ep.season}:${ep.episode}`:'');let old=state.history.find(row=>row.historyKey===historyKey);let row={...value,...(old||{}),...position,...ep,historyKey,at:Date.now()};if(old?.percent>=95&&!position.duration)row={...value,...ep,historyKey,at:Date.now(),timestamp:0,duration:0,percent:0};state.history=[row,...state.history.filter(x=>x.historyKey!==historyKey)].slice(0,100);state.positions[id]={...row};return row;}
module.exports={blocked,adQr,item,art,cleanItem,key,episode,progress,playerUrl,endpoint,record};
