'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http');
function mediaKind(url,mime=''){try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))return '';if(/\.m3u8$/i.test(u.pathname)||/mpegurl/i.test(mime))return 'hls';if(/\.(mp4|m4v|webm)$/i.test(u.pathname)||/^video\/(mp4|webm)/i.test(mime))return 'file';}catch{}return '';}
function attrs(line){const out={};for(const m of line.matchAll(/([A-Z0-9-]+)=("[^"]*"|[^,]*)/g))out[m[1]]=m[2].replace(/^"|"$/g,'');return out;}
function magnet(value){if(typeof value!=='string'||value.length>16000)throw Error('Invalid magnet link');const u=new URL(value);if(u.protocol!=='magnet:'||!/^urn:btih:(?:[a-f0-9]{40}|[a-z2-7]{32})$/i.test(u.searchParams.get('xt')||''))throw Error('Enter a BitTorrent magnet link');for(const name of ['xs','as','ws'])u.searchParams.delete(name);return u.href;}
function createStore(root,fetcher=fetch,onChange=()=>{}){
 fs.mkdirSync(root,{recursive:true});const index=path.join(root,'index.json');let rows=[];try{rows=JSON.parse(fs.readFileSync(index,'utf8')).filter(r=>/^[a-f0-9]{24}$/.test(r.id));}catch{}for(const r of rows)if(['downloading','queued','metadata'].includes(r.status))r.status='paused';let server,base,client;const jobs=new Map(),token=crypto.randomBytes(24).toString('hex');
 const directory=r=>path.join(root,r.id);
 function persist(){fs.writeFileSync(index+'.tmp',JSON.stringify(rows));fs.renameSync(index+'.tmp',index);onChange();}
 function list(){return rows.map(({id,title,status,bytes,total,error,kind,peers,speed})=>({id,title,status,bytes,total,error,kind,peers,speed}));}
 function get(id){const r=rows.find(r=>r.id===id);if(!r)throw Error('Download not found');return r;}
 async function request(r,url,signal,headers={}){const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw Error('Unsupported media URL');const response=await fetcher(u.href,{headers:{...r.headers,...headers},signal});if(!response.ok)throw Error('Source unavailable. Open the movie again to refresh its source.');return response;}
 function aborted(signal){if(signal.aborted)throw Error('Paused');}
 async function resource(r,url,name,signal,range){const dest=path.join(directory(r),name);if(fs.existsSync(dest))return;aborted(signal);const response=await request(r,url,signal,range?{Range:'bytes='+range}:{});if(range&&response.status!==206)throw Error('Source does not support segment ranges');const fd=fs.openSync(dest+'.part','w');let size=0;try{for await(const chunk of response.body){aborted(signal);fs.writeSync(fd,chunk);size+=chunk.length;r.bytes+=chunk.length;if(r.bytes>50*1024**3)throw Error('Download exceeds 50 GB');}}catch(e){r.bytes-=size;fs.rmSync(dest+'.part',{force:true});throw e;}finally{fs.closeSync(fd);}fs.renameSync(dest+'.part',dest);}
 async function fileDownload(r,signal){const name=r.mime==='video/webm'||/\.webm(?:\?|$)/i.test(r.url)?'movie.webm':'movie.mp4',dest=path.join(directory(r),name),part=dest+'.part';let offset=fs.existsSync(part)?fs.statSync(part).size:0;const response=await request(r,r.url,signal,offset?{Range:'bytes='+offset+'-'}:{});if(offset&&response.status!==206){offset=0;fs.rmSync(part,{force:true});}if(offset&&!response.headers.get('content-range')?.startsWith('bytes '+offset+'-'))throw Error('Source cannot resume this download');const length=Number(response.headers.get('content-length'));r.total=length?length+offset:0;r.bytes=offset;const fd=fs.openSync(part,offset?'a':'w');try{for await(const chunk of response.body){aborted(signal);fs.writeSync(fd,chunk);r.bytes+=chunk.length;if(r.bytes>50*1024**3)throw Error('Download exceeds 50 GB');}if(r.total&&r.total!==r.bytes)throw Error('Incomplete movie. Resume to retry.');}finally{fs.closeSync(fd);}const signature=Buffer.alloc(12),check=fs.openSync(part,'r');fs.readSync(check,signature,0,12,0);fs.closeSync(check);if(signature.toString('ascii',4,8)!=='ftyp'&&!signature.subarray(0,4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3])))throw Error('Source did not return a supported movie file');fs.renameSync(part,dest);r.entry=name;}
 async function hlsDownload(r,signal){const manifests=new Map(),resources=new Map(),rangeEnds=new Map();let count=0;r.bytes=fs.readdirSync(directory(r)).filter(f=>f.endsWith('.bin')).reduce((sum,f)=>sum+fs.statSync(path.join(directory(r),f)).size,0);
 async function playlist(url,depth=0){if(depth>4)throw Error('Unsupported nested playlist');if(manifests.has(url))return manifests.get(url);const response=await request(r,url,signal),text=await response.text();if(text.length>2*1024**2||!text.trimStart().startsWith('#EXTM3U'))throw Error('Source did not return an HLS movie');const origin=response.url||url,lines=text.replace(/\r/g,'').split('\n'),name='playlist-'+manifests.size+'.m3u8';manifests.set(url,name);const variants=[];for(let i=0;i<lines.length;i++)if(lines[i].startsWith('#EXT-X-STREAM-INF:')){let j=i+1;while(!lines[j]?.trim()&&j<lines.length)j++;variants.push({line:lines[i],a:attrs(lines[i]),url:new URL(lines[j],origin).href});}
 const output=['#EXTM3U'];if(variants.length){const eligible=variants.filter(v=>Number((v.a.RESOLUTION||'0x0').split('x')[1])<=1080);const chosen=(eligible.length?eligible:variants).sort((a,b)=>Number(b.a.BANDWIDTH)-Number(a.a.BANDWIDTH))[0];for(const type of ['AUDIO','SUBTITLES']){const group=chosen.a[type];if(!group)continue;const tracks=lines.filter(l=>l.startsWith('#EXT-X-MEDIA:')).map(line=>({line,a:attrs(line)})).filter(t=>t.a.TYPE===type&&t.a['GROUP-ID']===group);const t=tracks.find(t=>t.a.DEFAULT==='YES')||tracks[0];if(t)output.push(t.a.URI?t.line.replace(/URI="[^"]*"/,'URI="'+await playlist(new URL(t.a.URI,origin).href,depth+1)+'"'):t.line);}output.push(chosen.line,await playlist(chosen.url,depth+1));}
 else{if(!lines.includes('#EXT-X-ENDLIST'))throw Error('Live streams cannot be downloaded. Choose a movie or episode.');if(lines.some(l=>l.startsWith('#EXT-X-SESSION-KEY')||l.startsWith('#EXT-X-KEY:')&&!/METHOD=(NONE|AES-128)(,|$)/.test(l)))throw Error('Protected source does not support offline downloads');let pendingRange;
 const range=(value,uri)=>{const [length,offset]=value.split('@').map(Number),address=new URL(uri,origin).href,start=offset===undefined?rangeEnds.get(address)||0:offset;if(!Number.isSafeInteger(length)||length<1||!Number.isSafeInteger(start)||start<0)throw Error('Invalid segment range');rangeEnds.set(address,start+length);return start+'-'+(start+length-1);};
 const save=async(uri,partRange)=>{const address=new URL(uri,origin).href,key=address+'|'+(partRange||'');if(resources.has(key))return resources.get(key);if(++count>20000)throw Error('Too many movie segments');const local='media-'+crypto.createHash('sha256').update(key).digest('hex').slice(0,32)+'.bin';resources.set(key,local);await resource(r,address,local,signal,partRange);return local;};
 for(const line of lines.slice(1)){aborted(signal);if(line.startsWith('#EXT-X-BYTERANGE:')){pendingRange=line.slice('#EXT-X-BYTERANGE:'.length);continue;}if(line.startsWith('#EXT-X-MAP:')||line.startsWith('#EXT-X-KEY:')){const a=attrs(line);output.push(a.URI?line.replace(/URI="[^"]*"/,'URI="'+await save(a.URI,a.BYTERANGE?range(a.BYTERANGE,a.URI):null)+'"').replace(/,?BYTERANGE="[^"]*"/,''):line);}else if(line.trim()&&!line.startsWith('#')){output.push(await save(line,pendingRange?range(pendingRange,line):null));pendingRange=null;}else if(!/URI=/.test(line))output.push(line);}}
 fs.writeFileSync(path.join(directory(r),name),output.join('\n')+'\n');return name;}
 r.entry=await playlist(r.url);r.total=r.bytes;
 }
 async function torrentDownload(r,controller){if(!client){const {default:WebTorrent}=await import('webtorrent');client=new WebTorrent({utp:false,lsd:false,natUpnp:false,natPmp:false,tracker:{rtcConfig:null}});client.on('error',()=>{});}aborted(controller.signal);r.status='metadata';persist();await new Promise((resolve,reject)=>{let torrent;const stop=()=>{if(torrent)client.remove(torrent,{destroyStore:false},()=>reject(Error('Paused')));else reject(Error('Paused'));};controller.signal.addEventListener('abort',stop,{once:true});torrent=client.add(r.url,{path:directory(r)},t=>{if(controller.signal.aborted){stop();return;}const files=t.files.filter(f=>/\.(mp4|m4v|webm|mkv)$/i.test(f.name)&&!/(^|[\s._-])sample([\s._-]|$)/i.test(f.name));if(!files.length){client.remove(t,{destroyStore:false},()=>reject(Error('Torrent contains no playable movie file')));return;}const selected=files.sort((a,b)=>b.length-a.length)[0];const actual=path.resolve(directory(r),selected.path);if(!actual.startsWith(path.resolve(directory(r))+path.sep)){client.remove(t,{destroyStore:false},()=>reject(Error('Invalid torrent file path')));return;}for(const file of t.files)file.deselect();selected.select();r.entry=selected.path;r.total=selected.length;r.status='downloading';const progress=()=>{r.bytes=selected.downloaded;r.peers=t.numPeers;r.speed=t.downloadSpeed;};const timer=setInterval(progress,1000);const finish=()=>{if(selected.done){clearInterval(timer);progress();controller.signal.removeEventListener('abort',stop);client.remove(t,{destroyStore:false},()=>resolve());}};selected.on('done',finish);t.on('error',e=>{clearInterval(timer);reject(Error('Torrent connection failed. Resume to retry.'));});controller.signal.addEventListener('abort',()=>clearInterval(timer),{once:true});finish();});});}
 async function run(r){if(jobs.has(r.id)||r.status==='completed')return;const controller=new AbortController();jobs.set(r.id,controller);r.status='downloading';r.error='';persist();const timer=setInterval(persist,1000);try{fs.mkdirSync(directory(r),{recursive:true});if(r.kind==='torrent')await torrentDownload(r,controller);else if(r.kind==='hls')await hlsDownload(r,controller.signal);else await fileDownload(r,controller.signal);aborted(controller.signal);r.status='completed';}catch(e){r.status=controller.signal.aborted?'paused':'failed';r.error=controller.signal.aborted?'':e.message.includes('ENOSPC')?'Not enough storage. Free space and resume.':e.message;}finally{clearInterval(timer);jobs.delete(r.id);persist();}}
 function add(value){const kind=value.kind==='torrent'?'torrent':mediaKind(value.url,value.mime);if(!kind)throw Error('Source is not downloadable');const url=kind==='torrent'?magnet(value.url):value.url;let r=rows.find(r=>r.key===value.key&&r.status!=='failed');if(r){run(r);return r.id;}r={id:crypto.randomBytes(12).toString('hex'),key:String(value.key||url).slice(0,200),title:String(value.title||'Movie download').slice(0,300),url,mime:value.mime||'',headers:value.headers||{},kind,status:'queued',bytes:0,total:0,error:''};rows.unshift(r);persist();run(r);return r.id;}
 async function action(id,action){const r=get(id);if(action==='pause'){jobs.get(id)?.abort();if(!jobs.has(id)){r.status='paused';persist();}}else if(action==='resume'){if(jobs.has(id))return;run(r);}else if(action==='remove'){jobs.get(id)?.abort();while(jobs.has(id))await new Promise(resolve=>setTimeout(resolve,25));rows=rows.filter(x=>x!==r);fs.rmSync(directory(r),{recursive:true,force:true});persist();}else throw Error('Unsupported download action');}
 async function playback(id){const r=get(id),entry=path.resolve(directory(r),r.entry||'');if(r.status!=='completed'||!entry.startsWith(path.resolve(directory(r))+path.sep)||!fs.existsSync(entry))throw Error('Wait for the download to finish');if(!server){server=http.createServer((req,res)=>{let parts;try{parts=new URL(req.url,'http://localhost').pathname.split('/').filter(Boolean).map(decodeURIComponent);}catch{res.writeHead(404).end();return;}if(parts.length<3||parts[0]!==token||!/^[a-f0-9]{24}$/.test(parts[1])){res.writeHead(404).end();return;}const row=rows.find(x=>x.id===parts[1]&&x.status==='completed');if(!row){res.writeHead(404).end();return;}const folder=directory(row),file=path.resolve(folder,...parts.slice(2));if(!file.startsWith(path.resolve(folder)+path.sep)){res.writeHead(404).end();return;}try{const stat=fs.statSync(file);if(!stat.isFile())throw Error();let start=0,end=stat.size-1;const m=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range||'');if(m){start=Number(m[1]);end=m[2]?Math.min(Number(m[2]),end):end;}if(start>end||start>=stat.size){res.writeHead(416).end();return;}const mime=file.endsWith('.m3u8')?'application/vnd.apple.mpegurl':file.endsWith('.webm')?'video/webm':file.endsWith('.mkv')?'video/x-matroska':file.endsWith('.mp4')||file.endsWith('.m4v')?'video/mp4':'application/octet-stream';const h={'Content-Type':mime,'Content-Length':end-start+1,'Accept-Ranges':'bytes','Access-Control-Allow-Origin':'*'};if(m)h['Content-Range']='bytes '+start+'-'+end+'/'+stat.size;res.writeHead(m?206:200,h);if(req.method==='HEAD')res.end();else fs.createReadStream(file,{start,end}).on('error',()=>res.destroy()).pipe(res);}catch{res.writeHead(404).end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));base='http://127.0.0.1:'+server.address().port+'/'+token;server.unref();}return {name:r.title,url:base+'/'+r.id+'/'+r.entry.split(path.sep).map(encodeURIComponent).join('/'),mime:r.kind==='hls'?'application/x-mpegURL':r.entry.endsWith('.webm')?'video/webm':r.entry.endsWith('.mkv')?'video/x-matroska':'video/mp4',headers:{},offline:true};}
 function close(){for(const job of jobs.values())job.abort();client?.destroy();server?.close();}
 return {list,add,action,playback,close};
}
module.exports={mediaKind,magnet,attrs,createStore};
