'use strict';
const fs=require('node:fs/promises'),path=require('node:path');
const URLS={LiveTV:'https://raw.githubusercontent.com/Zer0Spce/ZeroStreams/main/playlist.m3u',IPTV:'https://raw.githubusercontent.com/Zer0Spce/ZeroStreams/main/IPTV.m3u'};
const TTL=3600000;
function http(value){try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&!/[\r\n]/.test(value);}catch{return false;}}
function headers(target,name,value){if(typeof value!=='string'||!value||value.length>2048||/[\r\n]/.test(value))return;const n={'user-agent':'User-Agent',referer:'Referer',origin:'Origin'}[name.toLowerCase()];if(n&&(n==='User-Agent'||http(value)))target[n]=value;}
function parseHeaders(target,value){for(const pair of value.split('&')){const i=pair.indexOf('=');if(i>0)try{headers(target,decodeURIComponent(pair.slice(0,i)),decodeURIComponent(pair.slice(i+1)));}catch{}}}
function parse(text){if(typeof text!=='string'||text.length>5000000||!text.replace(/^\uFEFF/,'').trim().startsWith('#EXTM3U')||text.includes('#EXT-X-TARGETDURATION'))throw Error('Expected an M3U channel playlist');const rows=[],seen=new Set();let item;
for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(line.startsWith('#EXTINF:')){item=null;let quote='',comma=-1;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'||c==="'")quote=quote===c?'':quote||c;if(c===','&&!quote){comma=i;break;}}if(comma<0)continue;const attrs={};for(const m of line.slice(0,comma).matchAll(/([\w-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s,]+))/g))attrs[m[1].toLowerCase()]=m[2]??m[3]??m[4];const name=line.slice(comma+1).trim()||attrs['tvg-name'];if(name)item={name,group:attrs['group-title']||'Channels',logo:http(attrs['tvg-logo'])?attrs['tvg-logo']:'',headers:{},mime:'',drmType:'',drmKey:''};}
else if(item&&line.startsWith('#EXTGRP:'))item.group=line.slice(8).trim()||'Channels';
else if(item&&line.startsWith('#EXTVLCOPT:')){const i=line.indexOf('='),name=line.slice(11,i).trim();headers(item.headers,{'http-referrer':'Referer','http-referer':'Referer','http-user-agent':'User-Agent','http-origin':'Origin'}[name]||'',line.slice(i+1).trim());}
else if(item&&line.startsWith('#KODIPROP:')){const i=line.indexOf('='),name=line.slice(10,i),value=line.slice(i+1).trim();if(name.endsWith('.license_type'))item.drmType=value.toLowerCase();if(name.endsWith('.license_key'))item.drmKey=value;if(name.endsWith('.manifest_type'))item.mime=value==='mpd'?'application/dash+xml':value==='hls'?'application/x-mpegurl':'';if(name.endsWith('.stream_headers')||name.endsWith('.common_headers'))parseHeaders(item.headers,value);}
else if(item&&!line.startsWith('#')&&http(line.split('|')[0])){const [url,h]=line.split('|',2);item.url=url;if(h)parseHeaders(item.headers,h);if(!item.mime)item.mime=new URL(url).pathname.endsWith('.mpd')?'application/dash+xml':new URL(url).pathname.endsWith('.m3u8')?'application/x-mpegurl':'';const id=item.name+'|'+url;if(!seen.has(id)){seen.add(id);rows.push(item);}item=null;if(rows.length>=3000)break;}}
if(!rows.length)throw Error('No playable channels in this playlist');return rows;}
function clearKeys(value){const out={};const hex=v=>{v=String(v).trim();const normalized=v.replace(/-/g,'');if(/^[\da-f]{32}$/i.test(normalized))return normalized.toLowerCase();if(!/^[\w+/-]{22}={0,2}$/.test(String(v)))throw Error('Invalid channel key');return Buffer.from(String(v),'base64').toString('hex');};value=value.split('|')[0].trim();if(value.startsWith('{')){const obj=JSON.parse(value.replace(/'([^']*)'/g,(_,text)=>JSON.stringify(text))); if(Array.isArray(obj.keys))for(const k of obj.keys)out[hex(k.kid)]=hex(k.k);else for(const [id,k]of Object.entries(obj))out[hex(id)]=hex(k);}else for(const pair of value.split(',')){const [id,k]=pair.split(':');out[hex(id)]=hex(k);}if(!Object.keys(out).length||Object.keys(out).length>32)throw Error('Invalid channel key count');return out;}
function createStore(root,fetcher=fetch){const snapshots=new Map(),pending=new Map();return {async get(section,force=false){if(!Object.hasOwn(URLS,section))throw Error('Invalid playlist');if(pending.has(section))return pending.get(section);const task=(async()=>{let cached=snapshots.get(section);const file=path.join(root,section+'.m3u');if(!cached)try{const body=await fs.readFile(file,'utf8');cached={channels:parse(body),updated:(await fs.stat(file)).mtimeMs};snapshots.set(section,cached);}catch{}if(cached&&((section==='IPTV'&&!force)||(section==='LiveTV'&&!force&&Date.now()-cached.updated<TTL)))return {...cached,error:''};try{const response=await fetcher(URLS[section],{signal:AbortSignal.timeout(25000),cache:'no-store',redirect:'error'});if(!response.ok)throw Error('Playlist unavailable');if(Number(response.headers.get('content-length'))>5000000)throw Error('Playlist too large');let body='',size=0;const decoder=new TextDecoder();for await(const chunk of response.body){size+=chunk.length;if(size>5000000)throw Error('Playlist too large');body+=decoder.decode(chunk,{stream:true});}body+=decoder.decode();const channels=parse(body);await fs.mkdir(root,{recursive:true});await fs.writeFile(file+'.tmp',body);await fs.rename(file+'.tmp',file);cached={channels,updated:Date.now()};snapshots.set(section,cached);return {...cached,error:''};}catch(error){if(cached)return {...cached,error:'Refresh unavailable · showing saved channels'};throw Error('Could not load channels. Check your connection and refresh.');}})();pending.set(section,task);try{return await task;}finally{pending.delete(section);}},select(section,index){if(!Object.hasOwn(URLS,section)||!Number.isSafeInteger(index)||index<0)throw Error('Invalid channel');const c=snapshots.get(section)?.channels[index];if(!c)throw Error('Channel not found. Refresh the list.');return c;}};}
module.exports={parse,clearKeys,createStore,URLS,TTL,http};
