'use strict';
// RawCast is invoked only for explicit downloads or selected RawCast playback; never catalog or trailers.
const BASE='https://api.rawcast.space/v1';
class RawCast {
  constructor(getKey,fetcher=fetch,onUsage=()=>{}){this.getKey=getKey;this.fetch=fetcher;this.onUsage=onUsage;this.streamCache=new Map();this.cache=new Map();this.pending=new Map();this.usage=null;this.generation=0;}
  hasKey(){return !!this.getKey();}
  clear(){this.generation++;this.streamCache.clear();this.cache.clear();this.pending.clear();this.usage=null;}
  async request(route,redirect=false){const key=this.getKey();if(!key)throw Object.assign(Error('RawCast API key required. Add your own key in Settings → RawCast API.'),{code:'KEY_REQUIRED'});let response;try{response=await this.fetch(BASE+route,{headers:{'X-API-Key':key,Accept:'application/json','User-Agent':'ZeroPlay/1.7.2'},signal:AbortSignal.timeout(30000),redirect:'manual'});}catch{throw Error('RawCast connection failed. Try again.');}
    if(key!==this.getKey())throw Error('RawCast configuration changed. Try again.');
    const limit=Number(response.headers.get('X-RateLimit-Limit')),remaining=Number(response.headers.get('X-RateLimit-Remaining')),reset=Number(response.headers.get('X-RateLimit-Reset'));
    if(response.headers.has('X-RateLimit-Limit')&&response.headers.has('X-RateLimit-Remaining')&&Number.isFinite(limit)&&limit>0&&Number.isFinite(remaining)&&remaining>=0){this.usage={limit,remaining,used:Math.max(0,limit-remaining),percent:Math.max(0,Math.min(100,(limit-remaining)/limit*100)),...(reset>0?{reset:reset*1000}:{}),at:Date.now()};this.onUsage(this.usage);}
    if(redirect&&[301,302,303,307,308].includes(response.status))return {url:response.headers.get('location'),format:'mp4'};let data={};try{data=await response.json();}catch{if(response.ok)throw Error('RawCast returned an unreadable response. Try again.');}
    if(!response.ok){const messages={401:'RawCast API key rejected.',403:'RawCast API key is unavailable or your account requires verification.',404:'Unavailable for Download.',429:'RawCast rate or monthly request limit reached. Try again later.',502:'RawCast could not resolve this download. Try again later.'};throw Object.assign(Error(messages[response.status]||'RawCast request failed. Try again.'),{status:response.status,retryAfter:Math.min(3600,Number(response.headers.get('Retry-After'))||0)});}
    return data;
  }
  async resolve(item,episode={},quality='1080p',fresh=false){if(!['movie','tv'].includes(item?.type)||!Number.isSafeInteger(item.id)||item.id<1)throw Error('Invalid download title');const season=Number(episode.season),number=Number(episode.episode);if(item.type==='tv'&&(!Number.isSafeInteger(season)||season<0||!Number.isSafeInteger(number)||number<1))throw Error('Select a season and episode first.');if(!['1080p','720p','480p','360p'].includes(quality))throw Error('Invalid download quality');const id=[item.type,item.id,season,number,quality].join(':');if(!fresh&&this.cache.get(id)?.until>Date.now())return this.cache.get(id).value;if(this.pending.has(id))return this.pending.get(id);
    const epoch=this.generation;const task=(async()=>{let data;try{data=await this.request('/download/'+item.type+'/'+item.id+(item.type==='tv'?'/'+season+'/'+number:'')+'?quality='+quality+'&redirect=false',true);}catch(e){if(e.status===404){this.cache.set(id,{until:Date.now()+300000,value:null});return null;}throw e;}
      // Only the documented direct-file contract is accepted. HLS is never a download.
      if(data.tmdbId!=null&&String(data.tmdbId)!==String(item.id)||/rick.?roll|never.gonna.give.you.up/i.test(String(data.title||data.filename||'')))throw Error('RawCast returned the wrong download. Choose another title or source.');const url=data.downloadUrl||data.url;let parsed;try{parsed=new URL(url);}catch{return null;}if(!['','mp4','mkv','webm','mov','m4v','ts','mpeg','mpg','flv','avi'].includes(String(data.format||'').toLowerCase())||parsed.protocol!=='https:'||parsed.username||parsed.password||/\.m3u8(?:$|\?)/i.test(url))return null;
      if(epoch!==this.generation)throw Error('RawCast configuration changed. Try again.');const value={url:parsed.href,format:String(data.format||'').toLowerCase(),quality:data.quality||quality};this.cache.set(id,{until:Date.now()+120000,value});return value;})();this.pending.set(id,task);try{return await task;}finally{if(this.pending.get(id)===task)this.pending.delete(id);}
  }
  async download(address,options={}){for(let i=0;i<6;i++){const url=new URL(address);if(url.protocol!=='https:'||url.username||url.password||/rick.?roll|dQw4w9WgXc/i.test(url.href))throw Error('Server returned an unsupported download URL.');const headers={...options.headers,'User-Agent':'ZeroPlay/1.7.2'};if(['rawcast.space','api.rawcast.space'].includes(url.hostname))headers['X-API-Key']=this.getKey();const response=await this.fetch(url.href,{...options,headers,redirect:'manual'});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');await response.body?.cancel();if(!location)throw Error('Server returned an invalid download redirect.');address=new URL(location,url).href;continue;}return response;}throw Error('Server returned too many download redirects.');}
  async manifest(address,headers){for(let i=0;i<6;i++){const url=new URL(address);if(url.protocol!=='https:'||url.username||url.password)throw Error('Invalid manifest');const auth={...headers};if(['rawcast.space','api.rawcast.space'].includes(url.hostname))auth['X-API-Key']=this.getKey();const response=await this.fetch(url.href,{headers:auth,redirect:'manual',signal:AbortSignal.timeout(15000)});if([301,302,303,307,308].includes(response.status)){const next=response.headers.get('location');await response.body?.cancel();if(!next)throw Error('Invalid redirect');address=new URL(next,url).href;continue;}if(!response.ok){await response.body?.cancel();throw Error('Unavailable manifest');}const reader=response.body.getReader();let bytes=Buffer.alloc(0);try{while(bytes.length<65536){const part=await reader.read();if(part.done)break;bytes=Buffer.concat([bytes,Buffer.from(part.value)]);if(bytes.includes(Buffer.from('<MPD'))||bytes.includes(Buffer.from('#EXTM3U')))break;}}finally{await reader.cancel();}const text=bytes.toString('utf8');if(/rick.?roll|dQw4w9WgXc|never.gonna.give.you.up/i.test(text))throw Error('Wrong video');const mime=text.includes('<MPD')?'application/dash+xml':text.includes('#EXTM3U')?'application/x-mpegURL':null;if(!mime)throw Error('Not an adaptive manifest');return {url:url.href,mime};}throw Error('Too many redirects');}
  async stream(item,episode={}){if(!['movie','tv'].includes(item?.type)||!Number.isSafeInteger(item.id)||item.id<1)throw Error('Invalid playback title');const ep=item.type==='tv'?{season:episode.season??1,episode:episode.episode??1}:{};if(item.type==='tv'&&(!Number.isSafeInteger(ep.season)||ep.season<1||ep.season>1000||!Number.isSafeInteger(ep.episode)||ep.episode<1||ep.episode>10000))throw Error('Select a season and episode first.');const route='/sources/'+item.type+'/'+item.id+(item.type==='tv'?'/'+ep.season+'/'+ep.episode:'')+'?lang=en&cleanOnly=true';const cached=this.streamCache.get(route);if(cached?.until>Date.now())return cached.value;const epoch=this.generation;const data=await this.request(route);if(data.tmdbId!=null&&String(data.tmdbId)!==String(item.id)||data.mediaType&&data.mediaType!==item.type)throw Error('RawCast returned the wrong title. Choose another source.');
    for(const server of data.servers||[])for(const stream of server.streams||[]){if(server.format==='mp4')continue;try{let address=stream.manifestUrl;if(!address){const resolver=new URL(stream.url);if(!['https://api.rawcast.space','https://rawcast.space'].includes(resolver.origin)||!resolver.pathname.startsWith('/v1/resolve/'))continue;const resolved=await this.request(resolver.pathname.slice(3)+resolver.search,true);address=resolved.manifestUrl||resolved.url;}
      const url=new URL(address);if(url.protocol!=='https:'||url.username||url.password||/rick.?roll|dQw4w9WgXc|never.gonna.give.you.up/i.test(url.href))continue;if(epoch!==this.generation)throw Error('RawCast configuration changed. Try again.');const headers={};for(const [name,value]of Object.entries(stream.headers||{}))if(['referer','user-agent','origin'].includes(name.toLowerCase())&&typeof value==='string'&&!/[\r\n]/.test(value))headers[name]=value;const manifest=await this.manifest(url.href,headers);if(epoch!==this.generation)throw Error('RawCast configuration changed. Try again.');const value={...manifest,headers,subtitles:(data.subtitles||[]).filter(s=>{try{const u=new URL(s.url);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}).map(s=>({url:s.url,language:s.language||'en',label:s.label||s.language||'Subtitles'}))};this.streamCache.set(route,{value,until:Date.now()+120000});return value;}catch(error){if(epoch!==this.generation)throw error;}}
    throw Error('RawCast stream unavailable. Choose another source.');}
  // No account endpoint is documented for API-key auth. A tiny documented metadata
  // request refreshes authoritative quota headers when the provider supplies them.
  async refreshUsage(){await this.request('/meta/movie/550?lang=en-US');return this.usage;}
  async test(){await this.request('/meta/movie/550?lang=en-US');return {status:'Connected',usage:this.usage};}
}
module.exports={RawCast};
