const fs=require('node:fs'),path=require('node:path');
const PRIMARY='https://api.ppv.st';
function domain(value){return typeof value==='string'&&/^(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z]{2,}$/i.test(value)?'https://api.'+value:null;}
function iframe(value){if(typeof value!=='string'||!value.trim()||value.length>100000)throw Error('Embedded player unavailable');const text=value.trim();if(text.startsWith('<'))return {html:text};const url=new URL(text);if(!['https:','http:'].includes(url.protocol)||url.username||url.password)throw Error('Invalid embedded player URL');return {url:url.href};}
function normalize(data){if(data?.success!==true||!Array.isArray(data.streams))throw Error('Invalid Live Sports catalogue');return data.streams.map(group=>({category:String(group.category||'Sports'),events:(group.streams||[]).filter(x=>x&&x.id!==undefined).map(x=>({id:String(x.id),title:String(x.name||'Live event'),poster:typeof x.poster==='string'&&/^https?:\/\//.test(x.poster)?x.poster:'',start:Number(x.starts_at)||0,end:Number(x.ends_at)||0,alwaysLive:!!Number(x.always_live),sources:[x,...(Array.isArray(x.substreams)?x.substreams:[])].flatMap((source,index)=>{try{return [{label:String(source.source_tag||source.tag||'Source '+(index+1)),embed:iframe(source.iframe)}];}catch{return [];}})})).filter(x=>x.sources.length)})).filter(x=>x.events.length);}
function createStore(file,fetcher=fetch,clock=Date.now){let cached=null,inflight,forced=Promise.resolve();try{cached=JSON.parse(fs.readFileSync(file,'utf8'));}catch{}let bases=[PRIMARY];if(cached?.base&&/^https:\/\/api\.[a-z0-9.-]+$/i.test(cached.base)&&cached.base!==PRIMARY)bases.push(cached.base);async function json(url){const r=await fetcher(url,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Live Sports API unavailable');const body=await r.text();if(body.length>8000000)throw Error('Catalogue too large');return JSON.parse(body);}
async function discover(){try{const ping=await json(PRIMARY+'/api/ping');if(ping.success===true&&Array.isArray(ping.domains))bases=[PRIMARY,...new Set(ping.domains.map(domain).filter(Boolean))];}catch{}}
async function update(){await discover();let last;for(const base of bases){try{const categories=normalize(await json(base+'/api/streams'));const next={categories,updated:clock(),base};fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file+'.tmp',JSON.stringify(next));fs.renameSync(file+'.tmp',file);cached=next;return {...cached,stale:false};}catch(e){last=e;}}if(cached)return {...cached,stale:true,error:'Unable to refresh · showing cached events'};throw last||Error('Live Sports unavailable');}
return {async get(force=false){if(force){const task=forced.catch(()=>{}).then(()=>inflight?inflight.catch(()=>{}):null).then(update);forced=task;return task;}if(!force&&cached&&clock()-cached.updated<60000)return {...cached,stale:false};if(!inflight)inflight=update().finally(()=>{inflight=null;});return inflight;},select(id,index){const event=cached?.categories.flatMap(c=>c.events).find(x=>x.id===String(id));if(!event||!Number.isSafeInteger(index)||!event.sources[index])throw Error('Stream unavailable · refresh and retry');return {...event,source:event.sources[index],base:cached.base};}};}
module.exports={normalize,iframe,domain,createStore};
