'use strict';
const {app,BrowserWindow,ipcMain}=require('electron');
const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),{Readable}=require('node:stream'),{pipeline}=require('node:stream/promises');
const versions=require('./version-manager.cjs');
const API='https://api.github.com/repos/Zer0Spce/ZeroPlay/releases?per_page=20';
let installed=false,mainWindow,updateWindow,currentRelease,downloadBusy=false;
const cleanVersion=value=>String(value||'').trim().replace(/^v/i,'').split('-')[0].split('.').map(x=>Number(x)||0);
function newer(remote,local){const a=cleanVersion(remote),b=cleanVersion(local),n=Math.max(a.length,b.length,3);for(let i=0;i<n;i++){const d=(a[i]||0)-(b[i]||0);if(d)return d>0;}return false;}
function testRelease(release){return /(?:^|[-_.])(test|demo|placeholder)(?:$|[-_.])/i.test(String(release?.tag_name||''));}
function stateFile(){return path.join(app.getPath('userData'),'updater.json');}
function readState(){try{return JSON.parse(fs.readFileSync(stateFile(),'utf8'));}catch{return {};}}
function writeState(value){const target=stateFile(),temp=target+'.tmp';fs.writeFileSync(temp,JSON.stringify(value));fs.renameSync(temp,target);}
function releaseView(release){return {current:app.getVersion(),version:String(release.tag_name||'').replace(/^v/i,''),tag:release.tag_name||'',name:release.name||release.tag_name||'ZeroPlay update',changelog:release.body||'No changelog was provided.',published:release.published_at||'',assetName:release.asset?.name||'',size:Number(release.asset?.size)||0};}
async function latest(){const response=await fetch(API,{headers:{Accept:'application/vnd.github+json','User-Agent':'ZeroPlay-Windows-Updater'},signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Could not check GitHub for updates ('+response.status+').');const releases=await response.json();const release=Array.isArray(releases)?releases.find(r=>!r.draft&&!r.prerelease&&!testRelease(r)):null;if(!release)throw Error('No stable ZeroPlay release is available.');const version=String(release.tag_name||'').replace(/^v/i,'');const asset=(release.assets||[]).find(x=>x.name===`ZeroPlay-${version}-Windows-x64.zip`)||(release.assets||[]).find(x=>/^ZeroPlay-.*-Windows-x64\.zip$/i.test(x.name||''));if(!asset)throw Error('The latest stable release does not contain a Windows portable ZIP.');const checksumAsset=(release.assets||[]).find(x=>/^SHA256SUMS\.txt$/i.test(x.name||''))||null;return {...release,asset,checksumAsset};}
function trustedMain(event){if(!mainWindow||mainWindow.isDestroyed()||event.sender!==mainWindow.webContents)throw Error('Untrusted updater request');}
function trustedUpdate(event){if(!updateWindow||updateWindow.isDestroyed()||event.sender!==updateWindow.webContents)throw Error('Untrusted updater window');}
function closeUpdate(){if(updateWindow&&!updateWindow.isDestroyed())updateWindow.close();updateWindow=null;}
async function showUpdate(release){currentRelease=release;if(updateWindow&&!updateWindow.isDestroyed()){updateWindow.focus();updateWindow.webContents.send('update-release',releaseView(release));return;}updateWindow=new BrowserWindow({width:560,height:590,minWidth:500,minHeight:500,maxWidth:680,maxHeight:760,resizable:true,maximizable:false,fullscreenable:false,title:'ZeroPlay Update',parent:mainWindow||undefined,modal:false,show:false,autoHideMenuBar:true,backgroundColor:'#0f0f0f',icon:path.join(__dirname,'assets/icon.png'),webPreferences:{preload:path.join(__dirname,'updater-preload.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false,webSecurity:true}});updateWindow.setMenuBarVisibility(false);updateWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));updateWindow.webContents.on('will-navigate',event=>event.preventDefault());updateWindow.on('closed',()=>{updateWindow=null;});updateWindow.once('ready-to-show',()=>updateWindow?.show());await updateWindow.loadFile(path.join(__dirname,'ui/updater.html'));updateWindow.webContents.send('update-release',releaseView(release));}
async function check({manual=false}={}){const release=await latest(),info=releaseView(release);if(!newer(info.version,app.getVersion()))return {status:'current',...info};if(!manual&&readState().skippedVersion===info.version)return {status:'skipped',...info};await showUpdate(release);return {status:'available',...info};}
async function sha256(file){const hash=crypto.createHash('sha256'),stream=fs.createReadStream(file);for await(const chunk of stream)hash.update(chunk);return hash.digest('hex');}
async function expectedSha256(release){const direct=String(release.asset?.digest||'').trim().toLowerCase();if(/^sha256:[0-9a-f]{64}$/.test(direct))return direct.slice(7);const checksum=release.checksumAsset;if(!checksum?.browser_download_url)return '';const response=await fetch(checksum.browser_download_url,{headers:{'User-Agent':'ZeroPlay-Windows-Updater'},redirect:'follow',signal:AbortSignal.timeout(30000)});if(!response.ok)throw Error('Could not download SHA256SUMS.txt ('+response.status+').');const text=await response.text(),target=String(release.asset?.name||'');for(const line of text.split(/\r?\n/)){const match=line.trim().match(/^([0-9a-fA-F]{64})\s+\*?(.+)$/);if(match&&match[2].trim()===target)return match[1].toLowerCase();}throw Error('SHA256SUMS.txt does not contain a checksum for '+target+'.');}
async function installVersion(release){if(downloadBusy)throw Error('An update is already downloading.');downloadBusy=true;let work;try{const info=releaseView(release),root=versions.rootDir(),versionsDir=await versions.ensureVersionsDir();work=path.join(versionsDir,'.download-'+info.version+'-'+Date.now());const zip=path.join(work,'ZeroPlay-'+info.version+'-Windows-x64.zip');await fsp.mkdir(work,{recursive:true});const expected=await expectedSha256(release);if(!expected)throw Error('The update package has no trusted SHA-256 checksum. Installation was stopped.');const response=await fetch(release.asset.browser_download_url,{headers:{'User-Agent':'ZeroPlay-Windows-Updater'},redirect:'follow',signal:AbortSignal.timeout(1800000)});if(!response.ok||!response.body)throw Error('Update download failed ('+response.status+').');const total=Number(response.headers.get('content-length'))||Number(release.asset.size)||0;let received=0;const source=Readable.fromWeb(response.body);source.on('data',chunk=>{received+=chunk.length;if(updateWindow&&!updateWindow.isDestroyed())updateWindow.webContents.send('update-progress',{received,total,percent:total?Math.min(100,received/total*100):0});});await pipeline(source,fs.createWriteStream(zip,{flags:'wx'}));const digest=await sha256(zip);if(digest!==expected)throw Error('Downloaded update failed SHA-256 verification.');const helper=path.join(root,'ZeroPlayUpdater.exe');await fsp.access(helper);const child=spawn(helper,['--root',root,'--zip',zip,'--version',info.version,'--sha256',expected,'--wait-pid',String(process.pid)],{cwd:root,detached:true,stdio:'ignore',windowsHide:true});child.unref();work=null;return {ok:true,version:info.version,helper:true};}catch(error){if(work)await fsp.rm(work,{recursive:true,force:true}).catch(()=>{});throw error;}finally{downloadBusy=false;}}
async function startInstall(event){trustedUpdate(event);if(!currentRelease)throw Error('No update is selected.');const result=await installVersion(currentRelease);closeUpdate();setTimeout(()=>{try{app.exit(0);}catch{process.exit(0);}},250);return result;}
function bindMain(win){if(mainWindow||win.isDestroyed())return;mainWindow=win;win.on('closed',()=>{if(mainWindow===win)mainWindow=null;});win.once('ready-to-show',()=>{if(!process.argv.includes('--smoke-test'))setTimeout(()=>check({manual:false}).catch(()=>{}),1800);});}
function install(){if(installed)return;installed=true;app.on('browser-window-created',(_event,win)=>{if(!mainWindow&&win.getTitle()==='ZeroPlay')bindMain(win);});ipcMain.handle('update-check',async event=>{trustedMain(event);return check({manual:true});});ipcMain.handle('update-window-action',async(event,action)=>{trustedUpdate(event);if(action==='cancel'){closeUpdate();return {ok:true};}if(action==='skip'){if(currentRelease){const s=readState();s.skippedVersion=releaseView(currentRelease).version;writeState(s);}closeUpdate();return {ok:true};}if(action==='install')return startInstall(event);throw Error('Unsupported updater action');});}
module.exports={install,newer,cleanVersion,releaseView,expectedSha256,testRelease};
