'use strict';
const {app,BrowserWindow,ipcMain}=require('electron');
const fs=require('node:fs'),fsp=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),{Readable}=require('node:stream'),{pipeline}=require('node:stream/promises');
const API='https://api.github.com/repos/Zer0Spce/ZeroPlay/releases/latest';
let installed=false,mainWindow,updateWindow,currentRelease,downloadBusy=false;
const cleanVersion=value=>String(value||'').trim().replace(/^v/i,'').split('-')[0].split('.').map(x=>Number(x)||0);
function newer(remote,local){const a=cleanVersion(remote),b=cleanVersion(local),n=Math.max(a.length,b.length,3);for(let i=0;i<n;i++){const d=(a[i]||0)-(b[i]||0);if(d)return d>0;}return false;}
function stateFile(){return path.join(app.getPath('userData'),'updater.json');}
function readState(){try{return JSON.parse(fs.readFileSync(stateFile(),'utf8'));}catch{return {};}}
function writeState(value){const target=stateFile(),temp=target+'.tmp';fs.writeFileSync(temp,JSON.stringify(value));fs.renameSync(temp,target);}
function releaseView(release){return {current:app.getVersion(),version:String(release.tag_name||'').replace(/^v/i,''),tag:release.tag_name||'',name:release.name||release.tag_name||'ZeroPlay update',changelog:release.body||'No changelog was provided.',published:release.published_at||'',assetName:release.asset?.name||'',size:Number(release.asset?.size)||0};}
async function latest(){const response=await fetch(API,{headers:{Accept:'application/vnd.github+json','User-Agent':'ZeroPlay-Windows-Updater'},signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('Could not check GitHub for updates ('+response.status+').');const release=await response.json();if(release.draft||release.prerelease)throw Error('Latest GitHub release is not a stable ZeroPlay release.');const version=String(release.tag_name||'').replace(/^v/i,'');const asset=(release.assets||[]).find(x=>x.name===`ZeroPlay-${version}-Windows-x64.zip`)||(release.assets||[]).find(x=>/^ZeroPlay-.*-Windows-x64\.zip$/i.test(x.name||''));if(!asset)throw Error('The latest release does not contain a Windows portable ZIP.');return {...release,asset};}
function trustedMain(event){if(!mainWindow||mainWindow.isDestroyed()||event.sender!==mainWindow.webContents)throw Error('Untrusted updater request');}
function trustedUpdate(event){if(!updateWindow||updateWindow.isDestroyed()||event.sender!==updateWindow.webContents)throw Error('Untrusted updater window');}
function closeUpdate(){if(updateWindow&&!updateWindow.isDestroyed())updateWindow.close();updateWindow=null;}
async function showUpdate(release){currentRelease=release;if(updateWindow&&!updateWindow.isDestroyed()){updateWindow.focus();updateWindow.webContents.send('update-release',releaseView(release));return;}
 updateWindow=new BrowserWindow({width:560,height:590,minWidth:500,minHeight:500,maxWidth:680,maxHeight:760,resizable:true,maximizable:false,fullscreenable:false,title:'ZeroPlay Update',parent:mainWindow||undefined,modal:false,show:false,autoHideMenuBar:true,backgroundColor:'#0f0f0f',icon:path.join(__dirname,'assets/icon.png'),webPreferences:{preload:path.join(__dirname,'updater-preload.cjs'),contextIsolation:true,sandbox:true,nodeIntegration:false,webSecurity:true}});
 updateWindow.setMenuBarVisibility(false);updateWindow.webContents.setWindowOpenHandler(()=>({action:'deny'}));updateWindow.webContents.on('will-navigate',event=>event.preventDefault());updateWindow.on('closed',()=>{updateWindow=null;});updateWindow.once('ready-to-show',()=>updateWindow?.show());await updateWindow.loadFile(path.join(__dirname,'ui/updater.html'));updateWindow.webContents.send('update-release',releaseView(release));}
async function check({manual=false}={}){const release=await latest();const info=releaseView(release);if(!newer(info.version,app.getVersion()))return {status:'current',...info};if(!manual&&readState().skippedVersion===info.version)return {status:'skipped',...info};await showUpdate(release);return {status:'available',...info};}
function psQuote(value){return "'"+String(value).replace(/'/g,"''")+"'";}
async function sha256(file){const hash=crypto.createHash('sha256'),stream=fs.createReadStream(file);for await(const chunk of stream)hash.update(chunk);return hash.digest('hex');}
async function prepareUpdate(release){if(downloadBusy)throw Error('An update is already downloading.');downloadBusy=true;try{const info=releaseView(release),root=path.join(app.getPath('temp'),'ZeroPlay-update-'+info.version+'-'+Date.now()),zip=path.join(root,'update.zip'),stage=path.join(root,'stage');await fsp.mkdir(root,{recursive:true});const response=await fetch(release.asset.browser_download_url,{headers:{'User-Agent':'ZeroPlay-Windows-Updater'},redirect:'follow',signal:AbortSignal.timeout(120000)});if(!response.ok||!response.body)throw Error('Update download failed ('+response.status+').');const total=Number(response.headers.get('content-length'))||Number(release.asset.size)||0;let received=0;const source=Readable.fromWeb(response.body);source.on('data',chunk=>{received+=chunk.length;if(updateWindow&&!updateWindow.isDestroyed())updateWindow.webContents.send('update-progress',{received,total,percent:total?Math.min(100,received/total*100):0});});await pipeline(source,fs.createWriteStream(zip,{flags:'wx'}));if(release.asset.digest?.startsWith('sha256:')){const digest=await sha256(zip),expected=release.asset.digest.slice(7).toLowerCase();if(digest!==expected)throw Error('Downloaded update failed SHA-256 verification.');}
 await new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',`Expand-Archive -LiteralPath ${psQuote(zip)} -DestinationPath ${psQuote(stage)} -Force`],{windowsHide:true});let stderr='';p.stderr.on('data',d=>stderr+=d);p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(Error(stderr.trim()||'Could not unpack the update.')));});
 let sourceDir=stage;const children=await fsp.readdir(stage,{withFileTypes:true});if(children.length===1&&children[0].isDirectory())sourceDir=path.join(stage,children[0].name);const exe=path.join(sourceDir,'ZeroPlay.exe');try{await fsp.access(exe);}catch{throw Error('The update package does not contain ZeroPlay.exe.');}
 const installDir=path.dirname(process.execPath),script=path.join(root,'apply-update.ps1'),currentPid=process.pid,launch=path.join(installDir,'ZeroPlay.exe');const body=`$ErrorActionPreference='Stop'\n$pidToWait=${currentPid}\n$source=${psQuote(sourceDir)}\n$target=${psQuote(installDir)}\n$launch=${psQuote(launch)}\nfor($i=0;$i -lt 60;$i++){try{Get-Process -Id $pidToWait -ErrorAction Stop | Out-Null; Start-Sleep -Milliseconds 500}catch{break}}\nStart-Sleep -Milliseconds 500\nGet-ChildItem -LiteralPath $source -Force | ForEach-Object { Copy-Item -LiteralPath $_.FullName -Destination $target -Recurse -Force }\nStart-Process -FilePath $launch\nRemove-Item -LiteralPath ${psQuote(root)} -Recurse -Force -ErrorAction SilentlyContinue\n`;await fsp.writeFile(script,body,'utf8');return {script,version:info.version};}finally{downloadBusy=false;}}
async function startInstall(event){trustedUpdate(event);if(!currentRelease)throw Error('No update is selected.');const prepared=await prepareUpdate(currentRelease);const child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',prepared.script],{detached:true,stdio:'ignore',windowsHide:true});child.unref();setTimeout(()=>app.quit(),250);return {ok:true,version:prepared.version};}
function bindMain(win){if(mainWindow||win.isDestroyed())return;mainWindow=win;win.on('closed',()=>{if(mainWindow===win)mainWindow=null;});win.once('ready-to-show',()=>{if(!process.argv.includes('--smoke-test'))setTimeout(()=>check({manual:false}).catch(()=>{}),1800);});}
function install(){if(installed)return;installed=true;app.on('browser-window-created',(_event,win)=>{if(!mainWindow&&win.getTitle()==='ZeroPlay')bindMain(win);});ipcMain.handle('update-check',async(event)=>{trustedMain(event);return check({manual:true});});ipcMain.handle('update-window-action',async(event,action)=>{trustedUpdate(event);if(action==='cancel'){closeUpdate();return {ok:true};}if(action==='skip'){if(currentRelease){const s=readState();s.skippedVersion=releaseView(currentRelease).version;writeState(s);}closeUpdate();return {ok:true};}if(action==='install')return startInstall(event);throw Error('Unsupported updater action');});}
module.exports={install,newer,cleanVersion,releaseView};
