/* Shared responsive layouts. Navigation nodes stay in place to preserve focus. */
(()=>{'use strict';
const root=document.documentElement,rail=document.querySelector('aside'),main=document.querySelector('main');let expanded=false;
const nativeSetInterval=window.setInterval.bind(window);
window.setInterval=(fn,delay,...args)=>nativeSetInterval(fn,delay===8000?15000:delay,...args);
const style=document.createElement('style');style.textContent=`
.zero-wordmark{font-size:18px;font-weight:800;letter-spacing:.035em;white-space:nowrap;margin-right:8px}.zero-wordmark .zero{color:var(--ink)}.zero-wordmark .play{color:var(--mint)}
:root[data-layout="youtube"] main>header:before{display:none!important}
:root[data-layout="google"] .card:not(.landscape),:root[data-layout="google"] .cards .card:not(.landscape){width:178px!important;min-width:178px!important;max-width:178px!important;flex:0 0 178px!important}
:root[data-layout="google"] .card:not(.landscape) img,:root[data-layout="google"] .card:not(.landscape) .poster-empty,:root[data-layout="google"] .grid .card:not(.landscape) img{aspect-ratio:2/3!important;height:auto!important;object-fit:cover!important;border-radius:16px!important}
:root[data-layout="google"] .grid{grid-template-columns:repeat(auto-fill,minmax(168px,1fr))!important}
.cast-person[role="button"]{cursor:pointer;border-radius:12px;padding:6px;transition:background .15s,transform .15s}.cast-person[role="button"]:hover,.cast-person[role="button"]:focus-visible{background:color-mix(in srgb,var(--mint) 16%,transparent);outline:2px solid var(--mint);outline-offset:2px;transform:translateY(-2px)}
.filmography-panel{margin-top:24px}.filmography-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:14px}.filmography-card{border:0;background:transparent!important;padding:0!important;text-align:left}.filmography-card img{width:100%;aspect-ratio:2/3;object-fit:cover;border-radius:10px}.filmography-card strong{display:block;margin-top:7px;color:var(--ink);font-size:12px}.filmography-card small{color:var(--muted);font-size:11px}
.zero-category-extra{position:relative;overflow:hidden;background-size:cover!important;background-position:center!important}.zero-category-extra:before{content:"";position:absolute;inset:0;background:linear-gradient(0deg,#000d,#0002)}.zero-category-extra .genre-caption{position:relative;z-index:1}
@keyframes zeroHeroNext{from{opacity:.2;transform:translateX(34px)}to{opacity:1;transform:none}}@keyframes zeroHeroPrev{from{opacity:.2;transform:translateX(-34px)}to{opacity:1;transform:none}}
:root:not([data-animations="false"]) .hero.zero-enter-next{animation:zeroHeroNext .32s ease-out}:root:not([data-animations="false"]) .hero.zero-enter-prev{animation:zeroHeroPrev .32s ease-out}
`;document.head.appendChild(style);
function expand(value){expanded=value;root.dataset.railExpanded=String(value);const toggle=rail?.querySelector('[data-layout-menu]');if(toggle)toggle.setAttribute('aria-expanded',String(value));}
if(rail){for(const b of rail.querySelectorAll('button')){b.setAttribute('aria-label',b.textContent.trim());b.title=b.textContent.trim();}const brand=rail.querySelector('.brand');if(brand){const menu=document.createElement('button');menu.dataset.layoutMenu='';menu.className='layout-menu';menu.textContent='☰';menu.setAttribute('aria-label','Expand or collapse navigation');menu.addEventListener('click',()=>expand(!expanded));rail.insertBefore(menu,brand);}rail.addEventListener('focusin',e=>{if(!e.target.hasAttribute('data-layout-menu'))expand(true);});rail.addEventListener('pointerenter',()=>expand(true));rail.addEventListener('pointerleave',()=>{if(!rail.contains(document.activeElement))expand(false);});}
main?.addEventListener('focusin',()=>expand(false));main?.addEventListener('pointerdown',()=>expand(false));
function ensureWordmark(){const header=document.querySelector('main>header');if(!header||header.querySelector('.zero-wordmark'))return;const mark=document.createElement('div');mark.className='zero-wordmark';mark.setAttribute('aria-label','ZeroPlay');mark.innerHTML='<span class="zero">Zero</span><span class="play">Play</span>';header.prepend(mark);}
const posterCache=new Map();
async function modernPoster(card){if(root.dataset.layout!=='google'||card.classList.contains('landscape')||card.dataset.zeroPoster==='1')return;const key=card.dataset.detail;if(!/^(movie|tv):\d+$/.test(key||''))return;card.dataset.zeroPoster='1';const [type,id]=key.split(':');try{let poster=posterCache.get(key);if(poster===undefined){const data=await window.zero?.api?.('/'+type+'/'+id,{});poster=data?.poster_path?`https://image.tmdb.org/t/p/w342${data.poster_path}`:'';posterCache.set(key,poster);}const img=card.querySelector('img');if(img&&poster)img.src=poster;}catch{card.dataset.zeroPoster='';}}
let heroDirection='next',surpriseDetail=false;
document.addEventListener('click',event=>{const t=event.target.closest?.('[data-action="hero-prev"],[data-action="hero-next"],[data-action="surprise"]');if(!t)return;if(t.dataset.action==='hero-prev')heroDirection='prev';if(t.dataset.action==='hero-next')heroDirection='next';if(t.dataset.action==='surprise')surpriseDetail=true;},true);
function animateHero(){const hero=document.querySelector('#hero');if(!hero||hero.dataset.zeroAnimated==='1')return;hero.dataset.zeroAnimated='1';hero.classList.add(heroDirection==='prev'?'zero-enter-prev':'zero-enter-next');heroDirection='next';}
async function wireCast(){const detail=document.querySelector('#detail[open]'),play=detail?.querySelector('[data-play]'),people=[...detail?.querySelectorAll('.cast-person')||[]];if(!detail||!play||!people.length||people.every(x=>x.dataset.personId))return;const match=String(play.dataset.play||'').match(/^(movie|tv):(\d+)$/);if(!match)return;try{const data=await window.zero.api('/'+match[1]+'/'+match[2],{append_to_response:'credits'});const cast=(data?.credits?.cast||[]).filter(x=>x.profile_path).slice(0,people.length);people.forEach((node,i)=>{const person=cast[i];if(!person?.id)return;node.dataset.personId=String(person.id);node.tabIndex=0;node.setAttribute('role','button');node.setAttribute('aria-label','Show titles with '+person.name);const open=()=>showFilmography(person.id,person.name,node);node.addEventListener('click',open);node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});}catch{}
}
async function showFilmography(personId,name,anchor){const bottom=anchor.closest('.detail-bottom');if(!bottom)return;let panel=bottom.querySelector('.filmography-panel');if(!panel){panel=document.createElement('section');panel.className='filmography-panel';bottom.appendChild(panel);}panel.innerHTML='<h3>'+escapeHtml(name)+'</h3><p>Loading filmography…</p>';try{const data=await window.zero.api('/person/'+personId+'/combined_credits',{});const seen=new Set(),rows=[];for(const raw of data.cast||[]){const type=raw.media_type;if(!['movie','tv'].includes(type)||raw.adult||!raw.id||!raw.poster_path)continue;const id=type+':'+raw.id;if(seen.has(id))continue;seen.add(id);rows.push({id,type,title:raw.title||raw.name||'Untitled',poster:'https://image.tmdb.org/t/p/w342'+raw.poster_path,year:String(raw.release_date||raw.first_air_date||'').slice(0,4),pop:Number(raw.popularity)||0,votes:Number(raw.vote_count)||0});}rows.sort((a,b)=>(b.pop+b.votes*.03)-(a.pop+a.votes*.03));panel.innerHTML='<h3>'+escapeHtml(name)+'</h3><p>'+rows.length+' movies & series from TMDB combined credits</p><div class="filmography-grid">'+rows.slice(0,36).map(row=>'<button class="filmography-card" data-film-title="'+escapeHtml(row.title)+'"><img loading="lazy" src="'+row.poster+'" alt=""><strong>'+escapeHtml(row.title)+'</strong><small>'+(row.type==='tv'?'Series':'Movie')+(row.year?' · '+row.year:'')+'</small></button>').join('')+'</div>';panel.querySelectorAll('[data-film-title]').forEach(btn=>btn.addEventListener('click',()=>{const q=document.querySelector('#query'),form=document.querySelector('#search-form');if(q&&form){document.querySelector('#detail')?.close();q.value=btn.dataset.filmTitle;form.requestSubmit();}}));}catch(error){panel.innerHTML='<h3>'+escapeHtml(name)+'</h3><p>Filmography unavailable. '+escapeHtml(error?.message||'Try again.')+'</p>';}}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function surpriseAgain(){const detail=document.querySelector('#detail[open]');if(!detail||!surpriseDetail||detail.querySelector('[data-zero-surprise-again]'))return;const actions=detail.querySelector('.detail-info .actions');if(!actions)return;const b=document.createElement('button');b.dataset.zeroSurpriseAgain='';b.textContent='🎲 Surprise me again';b.addEventListener('click',()=>document.querySelector('[data-action="surprise"]')?.click());actions.appendChild(b);}
const extraCategories=[[-107,'Chinese titles','zh'],[-108,'Thai titles','th'],[-109,'Indonesian titles','id'],[-110,'Portuguese titles','pt'],[-111,'German titles','de'],[-112,'Italian titles','it'],[-113,'Turkish titles','tr']];
async function addExtraCategories(){const grid=document.querySelector('.genre-grid');if(!grid||grid.dataset.zeroIntl==='1')return;grid.dataset.zeroIntl='1';const type=document.querySelector('[data-genre-type].selected')?.dataset.genreType||'movie';for(const [id,label,lang] of extraCategories){const b=document.createElement('button');b.className='zero-category-extra';b.dataset.zeroLanguage=lang;b.dataset.zeroCategoryId=String(id);b.innerHTML='<span class="genre-caption">'+escapeHtml(label)+'<span>Explore →</span></span>';grid.appendChild(b);try{const data=await window.zero.api('/discover/'+type,{with_original_language:lang,sort_by:'popularity.desc',page:1});const pick=(data.results||[]).find(x=>x.backdrop_path||x.poster_path);if(pick)b.style.backgroundImage='url(https://image.tmdb.org/t/p/w780'+(pick.backdrop_path||pick.poster_path)+')';}catch{}}}
async function openExtraCategory(button){const type=document.querySelector('[data-genre-type].selected')?.dataset.genreType||'movie',lang=button.dataset.zeroLanguage,label=button.textContent.replace('Explore →','').trim(),content=document.querySelector('#content');if(!content)return;content.innerHTML='<h2>'+escapeHtml(label)+'</h2><p>Loading titles…</p>';try{const data=await window.zero.api('/discover/'+type,{with_original_language:lang,sort_by:'popularity.desc',page:1});const rows=(data.results||[]).filter(x=>x.poster_path).slice(0,30);content.innerHTML='<div class="section-head"><h2>'+escapeHtml(label)+'</h2></div><div class="grid">'+rows.map(x=>{const title=x.title||x.name||'Untitled';return '<button class="card" data-zero-search-title="'+escapeHtml(title)+'"><div class="card-art"><img loading="lazy" src="https://image.tmdb.org/t/p/w342'+x.poster_path+'" alt="'+escapeHtml(title)+'"></div><span class="card-title">'+escapeHtml(title)+'</span><small>'+String(x.release_date||x.first_air_date||'').slice(0,4)+'</small></button>';}).join('')+'</div>';content.querySelectorAll('[data-zero-search-title]').forEach(b=>b.addEventListener('click',()=>{const q=document.querySelector('#query'),form=document.querySelector('#search-form');if(q&&form){q.value=b.dataset.zeroSearchTitle;form.requestSubmit();}}));}catch(error){content.innerHTML='<h2>'+escapeHtml(label)+'</h2><p>Could not load this collection. '+escapeHtml(error?.message||'')+'</p>';}}
document.addEventListener('click',event=>{const extra=event.target.closest?.('.zero-category-extra');if(extra){event.preventDefault();event.stopPropagation();openExtraCategory(extra);}},true);
function scan(){ensureWordmark();animateHero();document.querySelectorAll('.card[data-detail]').forEach(modernPoster);wireCast();surpriseAgain();addExtraCategories();}
const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();
window.zeroLayouts={apply(value){root.dataset.layout=['youtube','google','flix','classic'].includes(value)?value:'youtube';for(const b of rail?.querySelectorAll('[data-nav] span')||[]){b.dataset.originalLabel ||= b.textContent;b.textContent=root.dataset.layout==='google'&&b.parentElement.dataset.nav==='Home'?'For you':root.dataset.layout==='google'&&b.parentElement.dataset.nav==='Series'?'Shows':b.dataset.originalLabel;}expand(false);queueMicrotask(scan);},expand};
document.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||e.altKey||e.ctrlKey||e.metaKey||document.querySelector('dialog[open]')||['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const current=document.activeElement,r=current?.getBoundingClientRect();if(!r||!r.width)return;const x=r.left+r.width/2,y=r.top+r.height/2,horizontal=e.key==='ArrowLeft'||e.key==='ArrowRight',sign=e.key==='ArrowLeft'||e.key==='ArrowUp'?-1:1;let best,score=Infinity;for(const candidate of document.querySelectorAll('aside button,main button,main a,main input')){if(candidate===current||candidate.disabled||candidate.closest('[hidden]'))continue;const c=candidate.getBoundingClientRect();if(!c.width||!c.height||c.bottom<0||c.top>innerHeight)continue;const dx=c.left+c.width/2-x,dy=c.top+c.height/2-y,along=(horizontal?dx:dy)*sign,cross=Math.abs(horizontal?dy:dx);if(along<=1)continue;const distance=along+cross*3;if(distance<score){best=candidate;score=distance;}}if(best){e.preventDefault();best.focus();best.scrollIntoView?.({block:'nearest',inline:'nearest'});}});
window.zeroLayouts.apply('youtube');})();
