'use strict';
const $=id=>document.getElementById(id),video=$('video');let player,context,token=0,idle,loading=false;
function wake(){document.body.classList.remove('hidden');clearTimeout(idle);if(!video.paused&&!loading)idle=setTimeout(()=>document.body.classList.add('hidden'),4500);}
function fail(){loading=false;$('status').textContent='Stream unavailable · Retry or choose another channel';wake();}
async function load(index){const current=++token;loading=true;wake();$('status').textContent='Connecting…';try{const channel=await window.live.select(index);if(current!==token)return;await player.unload();if(current!==token)return;player.resetConfiguration();$('title').textContent=channel.name;player.configure({drm:{clearKeys:channel.clearKeys||{}},streaming:{retryParameters:{timeout:20000,maxAttempts:2}},manifest:{retryParameters:{timeout:15000,maxAttempts:2}}});await player.load(channel.url,null,channel.mime||undefined);if(current!==token)return;await video.play();loading=false;$('channels').value=String(index);tracks();wake();}catch{if(current===token)fail();}}
function tracks(){const audio=player.getAudioLanguagesAndRoles();$('audio').replaceChildren(...audio.map((a,i)=>new Option(a.language||'Audio '+(i+1),a.language)));$('audio').disabled=!audio.length;const subs=player.getTextTracks();$('subs').replaceChildren(new Option('Subtitles off',''),...subs.map(t=>new Option(t.label||t.language||'Subtitles',String(t.id))));}
$('audio').onchange=()=>player.selectAudioLanguage($('audio').value);
$('subs').onchange=()=>{const t=player.getTextTracks().find(t=>String(t.id)===$('subs').value);player.setTextTrackVisibility(!!t);if(t)player.selectTextTrack(t);};
$('channels').onchange=()=>load(Number($('channels').value));$('back').onclick=()=>window.live.close();$('full').onclick=()=>window.live.fullscreen();$('pause').onclick=()=>{video.paused?video.play().catch(fail):video.pause();wake();};$('edge').onclick=()=>{const range=player.seekRange();video.currentTime=range.end;video.play().catch(fail);};$('retry').onclick=()=>load(Number($('channels').value));$('fit').onclick=()=>{video.style.objectFit=video.style.objectFit==='cover'?'contain':'cover';};$('volume').oninput=()=>video.volume=Number($('volume').value);
for(const event of ['mousemove','pointerdown','keydown'])document.addEventListener(event,wake);
document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();if(!document.body.classList.contains('hidden')&&!video.paused)document.body.classList.add('hidden');else window.live.close();}if(event.key==='F11'){event.preventDefault();window.live.fullscreen();}if(event.code==='Space'&&event.target===document.body){event.preventDefault();$('pause').click();}});
video.addEventListener('error',fail);video.addEventListener('pause',wake);video.addEventListener('playing',()=>{loading=false;wake();});video.addEventListener('waiting',()=>{$('status').textContent='Buffering…';});
setInterval(()=>{if(!player||loading||player.getLoadMode()===0)return;$('pause').textContent=video.paused?'Play':'Pause';if(!video.error&&!video.paused)$('status').textContent=video.ended?'Stream ended · Retry or choose another channel':'● LIVE';},1000);
(async()=>{try{shaka.polyfill.installAll();if(!shaka.Player.isBrowserSupported())throw Error();player=new shaka.Player();await player.attach(video);player.addEventListener('error',fail);context=await window.live.context();$('channels').replaceChildren(...context.names.map((n,i)=>new Option(n,String(i))));await load(context.index);}catch{fail();}})();
