'use strict';
const $=id=>document.getElementById(id),video=$('video');let player,context,token=0,idle,loading=false;
function wake(){document.body.classList.remove('hidden');clearTimeout(idle);if(!video.paused&&!loading)idle=setTimeout(()=>document.body.classList.add('hidden'),4500);}
function fail(error){const detail=error?.detail||error;console.error('Live playback failed',Number(detail?.code)||0,detail?.category||'',detail instanceof Error?detail.name:'');loading=false;$('status').textContent='Stream unavailable · Retry or choose another channel';wake();}
async function load(index){const current=++token;loading=true;wake();$('status').textContent='Connecting…';try{const channel=await window.live.select(index);if(current!==token)return;await player.unload();if(current!==token)return;player.resetConfiguration();$('title').textContent=channel.name;player.configure({drm:{clearKeys:channel.clearKeys||{}},streaming:{retryParameters:{timeout:20000,maxAttempts:2}},manifest:{retryParameters:{timeout:15000,maxAttempts:2}}});if(context?.offline){video.muted=false;video.volume=Number($('volume').value);await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Unsupported or unreadable video file')),20000);video.onloadeddata=()=>{clearTimeout(timer);resolve();};video.onerror=()=>{clearTimeout(timer);reject(Error('Unsupported video codec'));};video.src=channel.url;video.load();});}else await player.load(channel.url,null,channel.mime||undefined);if(current!==token)return;if(context?.vod&&channel.start>0)video.currentTime=channel.start;await video.play();loading=false;$('channels').value=String(index);tracks();wake();}catch(error){if(current===token)fail(error);}}
function tracks(){const audio=player.getAudioTracks();$('audio').replaceChildren(...audio.map((a,i)=>new Option(a.label||a.language||'Audio '+(i+1),String(a.id))));const active=audio.find(a=>a.active);if(active)$('audio').value=String(active.id);$('audio').disabled=!audio.length;const subs=player.getTextTracks();$('subs').replaceChildren(new Option('Subtitles off',''),...subs.map(t=>new Option(t.label||t.language||'Subtitles',String(t.id))));}
$('audio').onchange=()=>{const track=player.getAudioTracks().find(t=>String(t.id)===$('audio').value);if(track)player.selectAudioTrack(track);};
$('subs').onchange=()=>{const t=player.getTextTracks().find(t=>String(t.id)===$('subs').value);player.setTextTrackVisibility(!!t);if(t)player.selectTextTrack(t);};
$('channels').onchange=()=>load(Number($('channels').value));$('back').onclick=()=>window.live.close();$('full').onclick=()=>window.live.fullscreen();$('pause').onclick=()=>{video.paused?video.play().catch(fail):video.pause();wake();};$('edge').onclick=()=>{const range=player.seekRange();video.currentTime=range.end;video.play().catch(fail);};$('retry').onclick=()=>load(Number($('channels').value));$('fit').onclick=()=>{video.style.objectFit=video.style.objectFit==='cover'?'contain':'cover';};$('volume').oninput=()=>video.volume=Number($('volume').value);
for(const event of ['mousemove','pointerdown','keydown'])document.addEventListener(event,wake);
document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();if(!document.body.classList.contains('hidden')&&!video.paused)document.body.classList.add('hidden');else window.live.close();}if(event.key==='F11'){event.preventDefault();window.live.fullscreen();}if(event.code==='Space'&&event.target===document.body){event.preventDefault();$('pause').click();}});
video.addEventListener('error',fail);video.addEventListener('pause',wake);video.addEventListener('playing',()=>{loading=false;wake();});video.addEventListener('waiting',()=>{$('status').textContent='Buffering…';});
setInterval(()=>{if(!player||loading||player.getLoadMode()===0&&!context?.offline)return;$('pause').textContent=video.paused?'Play':'Pause';if(!video.error&&!video.paused)$('status').textContent=video.ended?'Stream ended · Retry or choose another channel':context?.offline?'✓ Offline playback':context?.vod?'RawCast · Limited API quota':'● LIVE';},1000);
(async()=>{try{shaka.polyfill.installAll();if(!shaka.Player.isBrowserSupported())throw Error();player=new shaka.Player();await player.attach(video);player.getNetworkingEngine().registerResponseFilter((type,response)=>{if(type===shaka.net.NetworkingEngine.RequestType.MANIFEST)response.data=window.zeroDashCompat(response.data);});player.addEventListener('error',fail);context=await window.live.context();if(context.offline||context.vod){$('edge').hidden=true;$('channels').hidden=true;$('seek').hidden=false;$('elapsed').hidden=false;document.querySelector('#top>b').textContent=context.offline?'ZERO • OFFLINE':'ZERO • RAWCAST · LIMITED';}$('channels').replaceChildren(...context.names.map((n,i)=>new Option(n,String(i))));await load(context.index);}catch(error){fail(error);}})();

$('seek').oninput=()=>{if((context?.offline||context?.vod)&&Number.isFinite(video.duration))video.currentTime=Number($('seek').value)*video.duration/100;};video.addEventListener('timeupdate',()=>{if(context?.vod&&video.duration>0)window.live.progress({timestamp:video.currentTime,duration:video.duration});if((context?.offline||context?.vod)&&video.duration>0){$('seek').value=100*video.currentTime/video.duration;$('elapsed').textContent=Math.floor(video.currentTime/60)+':'+String(Math.floor(video.currentTime%60)).padStart(2,'0')+' / '+Math.floor(video.duration/60)+':'+String(Math.floor(video.duration%60)).padStart(2,'0');}});
