'use strict';
const video=document.getElementById('video'),status=document.getElementById('status'),title=document.getElementById('title');const urls=[];let idle,fill=false;
function wake(){document.body.classList.remove('hidden');clearTimeout(idle);if(!player.paused())idle=setTimeout(()=>document.body.classList.add('hidden'),4200);}
function disableTracks(){const tracks=player.textTracks();for(let i=0;i<tracks.length;i++)tracks[i].mode='disabled';}
function track(row,show=false){if(!row?.vtt)return null;const src=URL.createObjectURL(new Blob([row.vtt],{type:'text/vtt;charset=utf-8'}));urls.push(src);const remote=player.addRemoteTextTrack({kind:'subtitles',label:row.label||'Subtitle',srclang:row.language||'und',src,default:show},false);if(show&&remote?.track){remote.track.mode='showing';setTimeout(()=>{if(remote.track)remote.track.mode='showing';},0);}return remote;}
const player=videojs(video,{controls:true,autoplay:true,preload:'auto',playbackRates:[.75,1,1.25,1.5,2],controlBar:{pictureInPictureToggle:true,remainingTimeDisplay:true,subsCapsButton:true}});
for(const event of ['mousemove','pointerdown','keydown'])document.addEventListener(event,wake);
document.getElementById('back').onclick=()=>window.offline.close();document.getElementById('full').onclick=()=>window.offline.fullscreen();document.getElementById('fit').onclick=()=>{fill=!fill;player.el().classList.toggle('vjs-fill',fill);document.querySelector('#fit span:last-child').textContent=fill?'Fill screen':'Fit / Fill';};document.getElementById('subtitle').onclick=async()=>{const button=document.getElementById('subtitle');button.disabled=true;try{status.textContent='Choose an SRT, VTT, ASS or SSA subtitle…';const row=await window.offline.loadSubtitle();if(!row){status.textContent='Subtitle selection cancelled';return;}disableTracks();const added=track(row,true);if(!added)throw Error('Subtitle file did not contain usable cues.');status.textContent='✓ Loaded subtitles · '+row.label;player.trigger('texttrackchange');wake();}catch(e){status.textContent=e.message||'Could not load subtitles';wake();}finally{button.disabled=false;}};
document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();window.offline.close();}else if(event.key==='F11'){event.preventDefault();window.offline.fullscreen();}else if(event.code==='Space'&&event.target===document.body){event.preventDefault();player.paused()?player.play():player.pause();}else if(event.key==='ArrowRight'){player.currentTime(Math.min(player.duration()||Infinity,player.currentTime()+10));}else if(event.key==='ArrowLeft'){player.currentTime(Math.max(0,player.currentTime()-10));}});
player.on('play',wake);player.on('pause',wake);player.on('error',()=>{status.textContent='This file uses a codec that the Windows media engine cannot decode. Try Open in external player.';wake();});player.on('loadedmetadata',()=>{if(!/subtitle/i.test(status.textContent))status.textContent='✓ Ready · '+Math.round((player.duration()||0)/60)+' min';wake();});
(async()=>{try{const context=await window.offline.context();title.textContent=context.title||'Downloaded video';player.src({src:context.url});const found=context.subtitles||[];found.forEach((row,index)=>track(row,index===0));if(found.length)status.textContent='✓ '+found.length+' local subtitle'+(found.length===1?'':'s')+' found';await player.play().catch(()=>{});wake();}catch(e){status.textContent=e.message||'Could not open downloaded video';}})();
window.addEventListener('beforeunload',()=>{urls.forEach(URL.revokeObjectURL);player.dispose();});
