'use strict';
const video=document.getElementById('video'),status=document.getElementById('status'),title=document.getElementById('title'),subtitleFile=document.getElementById('subtitle-file');let idle,fill=false;
function wake(){document.body.classList.remove('hidden');clearTimeout(idle);if(!player.paused())idle=setTimeout(()=>document.body.classList.add('hidden'),4200);}
function disableTracks(){const tracks=player.textTracks();for(let i=0;i<tracks.length;i++)tracks[i].mode='disabled';}
function cueTime(value){const parts=String(value||'').trim().replace(',','.').split(':').map(Number);if(parts.some(Number.isNaN))return null;if(parts.length===3)return Math.max(0,parts[0]*3600+parts[1]*60+parts[2]);if(parts.length===2)return Math.max(0,parts[0]*60+parts[1]);return null;}
function parseVtt(vtt){const lines=String(vtt||'').replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n'),cues=[];let i=0;if(lines[0]?.trim().startsWith('WEBVTT'))i=1;while(i<lines.length){while(i<lines.length&&!lines[i].trim())i++;if(i>=lines.length)break;if(!lines[i].includes('-->'))i++;if(i>=lines.length||!lines[i].includes('-->'))continue;const timing=lines[i++].split('-->'),start=cueTime(timing[0]),end=cueTime((timing[1]||'').trim().split(/\s+/)[0]);if(start==null||end==null||end<=start)continue;const text=[];while(i<lines.length&&lines[i].trim())text.push(lines[i++]);const caption=text.join('\n').replace(/<\/?(?:c(?:\.[^>]*)?|v|lang|ruby|rt)[^>]*>/gi,'').trim();if(caption)cues.push({start,end,text:caption});}return cues;}
function makeCue(start,end,text){const Cue=window.VTTCue||window.TextTrackCue;if(!Cue)throw Error('This Windows media engine does not expose subtitle cue support.');return new Cue(start,end,text);}
function track(row,show=false){if(!row?.vtt)return null;const cues=parseVtt(row.vtt);if(!cues.length)return null;const remote=player.addTextTrack('subtitles',row.label||'Subtitle',row.language||'und');let added=0;for(const cue of cues){try{remote.addCue(makeCue(cue.start,cue.end,cue.text));added++;}catch(_){}}if(!added)return null;if(show){disableTracks();remote.mode='showing';setTimeout(()=>{remote.mode='showing';player.trigger('texttrackchange');},0);}return remote;}
function time(value){const parts=String(value||'').trim().replace(',','.').split(':').map(Number);if(parts.some(Number.isNaN))return null;let h=0,m=0,s=0;if(parts.length===3)[h,m,s]=parts;else if(parts.length===2)[m,s]=parts;else return null;return String(Math.max(0,Math.floor(h))).padStart(2,'0')+':'+String(Math.max(0,Math.floor(m))).padStart(2,'0')+':'+Number(s).toFixed(3).padStart(6,'0');}
function subtitleVtt(name,text){const ext=(name.match(/\.[^.]+$/)?.[0]||'').toLowerCase(),raw=String(text||'').replace(/^\uFEFF/,'');if(ext==='.vtt'){const ready=raw.replace(/\r/g,'');if(!/^WEBVTT(?:\s|$)/m.test(ready))throw Error('This VTT file is missing a WEBVTT header.');return ready;}if(ext==='.srt'){const body=raw.replace(/\r/g,'').replace(/(\d{1,2}:\d{2}:\d{2})[,.](\d{1,3})/g,(_,stamp,ms)=>stamp+'.'+String(ms).padEnd(3,'0')).replace(/^\s*\d+\s*\n(?=\d{1,2}:\d{2}:\d{2}[.]\d{3}\s+-->)/gm,'');return 'WEBVTT\n\n'+body;}if(ext==='.ass'||ext==='.ssa'){const cues=[];for(const line of raw.split(/\r?\n/)){if(!/^Dialogue:/i.test(line))continue;const parts=line.replace(/^Dialogue:\s*/i,'').split(',');if(parts.length<10)continue;const start=time(parts[1]),end=time(parts[2]);if(!start||!end)continue;const caption=parts.slice(9).join(',').replace(/\{[^}]*\}/g,'').replace(/\\N/g,'\n').replace(/\\n/g,'\n').trim();if(caption)cues.push(start+' --> '+end+'\n'+caption);}if(!cues.length)throw Error('No usable subtitle cues were found.');return 'WEBVTT\n\n'+cues.join('\n\n')+'\n';}throw Error('Choose an SRT, VTT, ASS or SSA subtitle file.');}
function subtitleLanguage(name){const lower=String(name||'').toLowerCase(),m=lower.match(/[._ -](en|eng|english|es|spa|fr|fra|de|ger|it|pt|ja|ko|tl|fil)[._ -]/),code=m?.[1]||'und';return ({eng:'en',english:'en',spa:'es',fra:'fr',ger:'de',fil:'tl'})[code]||code;}
const player=videojs(video,{controls:true,autoplay:true,preload:'auto',playbackRates:[.75,1,1.25,1.5,2],controlBar:{pictureInPictureToggle:true,remainingTimeDisplay:true,subsCapsButton:true}});
for(const event of ['mousemove','pointerdown','keydown'])document.addEventListener(event,wake);
document.getElementById('back').onclick=()=>window.offline.close();document.getElementById('full').onclick=()=>window.offline.fullscreen();document.getElementById('fit').onclick=()=>{fill=!fill;player.el().classList.toggle('vjs-fill',fill);document.querySelector('#fit span:last-child').textContent=fill?'Fill screen':'Fit / Fill';};
document.getElementById('subtitle').onclick=()=>{status.textContent='Choose an SRT, VTT, ASS or SSA subtitle…';subtitleFile.value='';subtitleFile.click();wake();};
subtitleFile.addEventListener('change',async()=>{const file=subtitleFile.files?.[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('Subtitle file must be under 2 MB.');const vtt=subtitleVtt(file.name,await file.text());const added=track({label:file.name,language:subtitleLanguage(file.name),vtt},true);if(!added)throw Error('Subtitle file did not contain usable cues.');status.textContent='✓ Loaded subtitles · '+file.name;wake();}catch(e){status.textContent=e.message||'Could not load subtitles';wake();}});
subtitleFile.addEventListener('cancel',()=>{status.textContent='Subtitle selection cancelled';wake();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();window.offline.close();}else if(event.key==='F11'){event.preventDefault();window.offline.fullscreen();}else if(event.code==='Space'&&event.target===document.body){event.preventDefault();player.paused()?player.play():player.pause();}else if(event.key==='ArrowRight'){player.currentTime(Math.min(player.duration()||Infinity,player.currentTime()+10));}else if(event.key==='ArrowLeft'){player.currentTime(Math.max(0,player.currentTime()-10));}});
player.on('play',wake);player.on('pause',wake);player.on('error',()=>{status.textContent='This file uses a codec that the Windows media engine cannot decode. Try Open in external player.';wake();});player.on('loadedmetadata',()=>{if(!/subtitle/i.test(status.textContent))status.textContent='✓ Ready · '+Math.round((player.duration()||0)/60)+' min';wake();});
(async()=>{try{const context=await window.offline.context();title.textContent=context.title||'Downloaded video';player.src({src:context.url});const found=context.subtitles||[];found.forEach((row,index)=>track(row,index===0));if(found.length)status.textContent='✓ '+found.length+' local subtitle'+(found.length===1?'':'s')+' found';await player.play().catch(()=>{});wake();}catch(e){status.textContent=e.message||'Could not open downloaded video';}})();
window.addEventListener('beforeunload',()=>player.dispose());
