'use strict';
const video=document.getElementById('video'),status=document.getElementById('status'),title=document.getElementById('title');const urls=[];let idle,fill=false;
function wake(){document.body.classList.remove('hidden');clearTimeout(idle);if(!player.paused())idle=setTimeout(()=>document.body.classList.add('hidden'),4200);}
function track(row,show=false){if(!row?.vtt)return;const src=URL.createObjectURL(new Blob([row.vtt],{type:'text/vtt'}));urls.push(src);const remote=player.addRemoteTextTrack({kind:'subtitles',label:row.label||'Subtitle',srclang:row.language||'und',src,default:show},false);if(show&&remote?.track)remote.track.mode='showing';}
const player=videojs(video,{controls:true,autoplay:true,preload:'auto',playbackRates:[.75,1,1.25,1.5,2],controlBar:{pictureInPictureToggle:true,remainingTimeDisplay:true,subsCapsButton:true}});
for(const event of ['mousemove','pointerdown','keydown'])document.addEventListener(event,wake);
document.getElementById('back').onclick=()=>window.offline.close();document.getElementById('full').onclick=()=>window.offline.fullscreen();document.getElementById('fit').onclick=()=>{fill=!fill;player.el().classList.toggle('vjs-fill',fill);};document.getElementById('subtitle').onclick=async()=>{try{const row=await window.offline.loadSubtitle();if(row){for(const t of player.textTracks())t.mode='disabled';track(row,true);status.textContent='✓ Loaded subtitles · '+row.label;}}catch(e){status.textContent=e.message||'Could not load subtitles';}};
document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();window.offline.close();}else if(event.key==='F11'){event.preventDefault();window.offline.fullscreen();}else if(event.code==='Space'&&event.target===document.body){event.preventDefault();player.paused()?player.play():player.pause();}else if(event.key==='ArrowRight'){player.currentTime(Math.min(player.duration()||Infinity,player.currentTime()+10));}else if(event.key==='ArrowLeft'){player.currentTime(Math.max(0,player.currentTime()-10));}});
player.on('play',wake);player.on('pause',wake);player.on('error',()=>{status.textContent='This file uses a codec that the Windows media engine cannot decode. Try Open in external player.';wake();});player.on('loadedmetadata',()=>{status.textContent='✓ Ready · '+Math.round((player.duration()||0)/60)+' min';wake();});
(async()=>{try{const context=await window.offline.context();title.textContent=context.title||'Downloaded video';player.src({src:context.url});(context.subtitles||[]).forEach((row,index)=>track(row,index===0));if(context.subtitles?.length)status.textContent='✓ '+context.subtitles.length+' local subtitle'+(context.subtitles.length===1?'':'s')+' found';await player.play().catch(()=>{});wake();}catch(e){status.textContent=e.message||'Could not open downloaded video';}})();
window.addEventListener('beforeunload',()=>{urls.forEach(URL.revokeObjectURL);player.dispose();});
