const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('ui/index.html','utf8'),script=fs.readFileSync('ui/app.js','utf8');
const movie={id:299534,title:'Avengers: Endgame',poster_path:'/test.jpg',backdrop_path:'/backdrop.jpg',release_date:'2019-04-24',media_type:'movie',vote_average:8,overview:'A story.'};
const dom=new JSDOM(html,{runScripts:'outside-only',url:'https://zero.local'}),w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
let state={favorites:[],planned:[],history:[],positions:{},searches:[],collections:{},settings:{region:'PH',gain:1,theme:'dark',source:'vidstuck'},hasKey:true,version:'0.4.5'},played,queries=[];
w.zero={surprise:async()=>({id:999,type:'movie',title:'Surprise beyond home',date:'2020-01-01'}),state:async()=>state,api:async(path,params)=>{queries.push([path,params]);if(path.startsWith('/genre/'))return {genres:[{id:28,name:'Action'},{id:35,name:'Comedy'}]};if(path.includes('providers'))return {results:[]};if(path==='/movie/299534')return {...movie,genres:[{name:'Adventure'}],credits:{cast:[],crew:[]},videos:{results:[]},recommendations:{results:[]}};return {results:[movie],total_pages:2};},change:async(action,value)=>{if(action==='search')state.searches=[value];if(action==='settings')state.settings={...state.settings,...value};return state;},play:async(item,ep)=>{played=[item,ep];},external:async()=>{},onRefresh:()=>()=>{}};
const errors=[];w.addEventListener('error',event=>errors.push(event.message));w.eval(script);
async function tick(){await new Promise(resolve=>setTimeout(resolve,30));}
(async()=>{await tick();assert.ok(w.document.querySelector('#hero'));assert.ok(w.document.querySelector('#content').textContent.includes('Watchlist'));w.document.querySelector('[data-action="toggle-theme"]').click();await tick();assert.equal(w.document.documentElement.dataset.theme,'light');assert.equal(w.document.querySelectorAll('[data-nav="Live"],[data-nav="Manga"]').length,0);const query=w.document.querySelector('#query');query.value='my own movie';w.document.querySelector('#search-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.ok(queries.some(([path,params])=>path==='/search/multi'&&params.query==='my own movie'));w.document.querySelector('[data-detail]').click();await tick();assert.ok(w.document.querySelector('#detail').open);assert.ok(w.document.querySelector('#detail-body').textContent.includes('Adventure'));assert.ok(w.document.querySelector('#detail .watch-actions'));assert.ok(w.document.querySelector('#detail .watch-actions').textContent.includes('Recommended'));w.document.querySelector('#detail [data-action="source"]').click();await tick();assert.equal(w.document.querySelectorAll('[data-source]').length,4);w.document.querySelector('[data-source="vidsrc-sh"]').click();await tick();w.document.querySelector('#detail [data-play]').click();await tick();assert.equal(played[0].id,299534);assert.equal(state.settings.source,'vidsrc-sh');w.document.querySelector('[data-action="close"]').click();await tick();w.document.querySelector('[data-nav="Categories"]').click();await tick();assert.ok(queries.some(([path])=>path==='/genre/movie/list'));w.document.querySelector('[data-genre="28"]').click();await tick();assert.ok(queries.some(([path,p])=>path==='/discover/movie'&&p.with_genres===28));w.document.querySelector('[data-nav="Categories"]').click();await tick();w.document.querySelector('[data-genre-type="tv"]').click();await tick();assert.ok(queries.some(([path])=>path==='/genre/tv/list'));w.document.querySelector('[data-genre="35"]').click();await tick();assert.ok(queries.some(([path,p])=>path==='/discover/tv'&&p.with_genres===35));assert.equal(w.document.querySelectorAll('[data-action="surprise"]').length,1);w.document.querySelector('[data-action="surprise"]').click();await tick();assert.ok(w.document.querySelector('#detail-body').textContent.includes('Surprise beyond home'));assert.deepEqual(errors,[]);console.log('Desktop carousel, full search, details and playback UI checks passed');w.close();})().catch(error=>{console.error(error);w.close();process.exitCode=1;});
