const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('ui/index.html','utf8'),script=fs.readFileSync('ui/app.js','utf8');
const movie={id:299534,title:'Avengers: Endgame',poster_path:'/test.jpg',backdrop_path:'/backdrop.jpg',release_date:'2019-04-24',media_type:'movie',vote_average:8,overview:'A story.'};
const dom=new JSDOM(html,{runScripts:'outside-only',url:'https://zero.local'}),w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};
let state={favorites:[],planned:[],history:[],positions:{},searches:[],collections:{},settings:{region:'PH',gain:1},hasKey:true,version:'0.4.1'},played,queries=[];
w.zero={state:async()=>state,api:async(path,params)=>{queries.push([path,params]);if(path.includes('providers'))return {results:[]};if(path==='/movie/299534')return {...movie,genres:[{name:'Adventure'}],credits:{cast:[],crew:[]},videos:{results:[]},recommendations:{results:[]}};return {results:[movie],total_pages:2};},change:async(action,value)=>{if(action==='search')state.searches=[value];return state;},play:async(item,ep)=>{played=[item,ep];},external:async()=>{},onRefresh:()=>()=>{}};
const errors=[];w.addEventListener('error',event=>errors.push(event.message));w.eval(script);
async function tick(){await new Promise(resolve=>setTimeout(resolve,30));}
(async()=>{await tick();assert.ok(w.document.querySelector('#hero'));assert.equal(w.document.querySelectorAll('[data-nav="Live"],[data-nav="Manga"]').length,0);const query=w.document.querySelector('#query');query.value='my own movie';w.document.querySelector('#search-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.ok(queries.some(([path,params])=>path==='/search/multi'&&params.query==='my own movie'));w.document.querySelector('[data-detail]').click();await tick();assert.ok(w.document.querySelector('#detail').open);assert.ok(w.document.querySelector('#detail-body').textContent.includes('Adventure'));w.document.querySelector('#detail [data-play]').click();await tick();assert.equal(played[0].id,299534);assert.deepEqual(errors,[]);console.log('Desktop carousel, full search, details and playback UI checks passed');w.close();})().catch(error=>{console.error(error);w.close();process.exitCode=1;});
