const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.env.ZERO_GUARD_PATH||'android-next/player-guard.js','utf8');
function page(html){const dom=new JSDOM(html,{runScripts:'outside-only',url:'https://vidstuck.xyz/embed/movie/299534'}),w=dom.window;w.__zeroTv=true;w.__zeroBlockAds=true;w.HTMLElement.prototype.getBoundingClientRect=function(){const left=Number(this.dataset.x)||0,top=Number(this.dataset.y)||0,width=Number(this.dataset.w)||100,height=Number(this.dataset.h)||40;return {left,top,width,height,right:left+width,bottom:top+height};};w.HTMLElement.prototype.scrollIntoView=function(){};w.eval(source);w.document.dispatchEvent(new w.Event('DOMContentLoaded'));return dom;}
async function run(){
  let dom=page('<video></video><div class="plyr__controls" data-y="650" data-w="1024" data-h="70"><button id="play" data-x="100" data-y="660">Play</button><button id="volume" data-x="300" data-y="660">Volume</button><button id="subtitles" data-x="500" data-y="660">Subtitles</button></div>');const w=dom.window;let seeks=0,clicks=0;w.document.addEventListener('keydown',event=>{if(event.key==='ArrowLeft')seeks++;});w.document.getElementById('play').onclick=()=>clicks++;
  w.__zeroTvNavigate('right');assert.equal(w.document.activeElement.id,'play');w.__zeroTvNavigate('right');assert.equal(w.document.activeElement.id,'volume');
  const left=new w.KeyboardEvent('keydown',{key:'ArrowLeft',bubbles:true,cancelable:true});w.document.dispatchEvent(left);assert.equal(w.document.activeElement.id,'play');assert.equal(seeks,0,'Left must navigate focus without reaching provider seek hotkeys');assert.equal(left.defaultPrevented,true);assert.equal(clicks,0,'Arrow movement must not activate playback');
  w.__zeroTvNavigate('ok');assert.equal(clicks,1);dom.window.close();
  dom=page('<button id="back" aria-label="Go back">Back</button><button id="play" data-x="200">Play</button>');let exits=0;dom.window.ZeroPlayer={postMessage:value=>{assert.equal(value,'back');exits++;}};dom.window.document.getElementById('back').click();assert.equal(exits,1,'The player Back button should exit via the narrow native action');dom.window.close();
  dom=page('<iframe id="frame" data-w="1024" data-h="768"></iframe>');let forwarded;const frame=dom.window.document.querySelector('iframe');frame.contentWindow.postMessage=data=>forwarded=data;dom.window.__zeroTvNavigate('left');assert.equal(forwarded.type,'zerostreams-tv-nav');assert.equal(forwarded.direction,'left');assert.equal(dom.window.document.activeElement,frame);dom.window.close();
  dom=page('<video></video><div id="component"></div>');const root=dom.window.document.getElementById('component').attachShadow({mode:'open'});root.innerHTML='<img id="painted" data-w="1024" data-h="768">';dom.window.__zeroDismissQrAd();assert.equal(root.getElementById('painted').style.display,'none','Native-confirmed painted QR advertisements inside open shadow DOM should be removed');assert.equal(dom.window.document.querySelector('video').style.display,'');dom.window.close();
  console.log('TV focus navigation, no arrow seeking, OK activation, embedded navigation, player Back and shadow QR checks passed');
}
run().catch(error=>{console.error(error);process.exitCode=1;});
