package com.zerostreams.app;
import androidx.test.ext.junit.runners.AndroidJUnit4;import androidx.test.platform.app.InstrumentationRegistry;import org.junit.*;import org.junit.runner.RunWith;import org.json.*;import android.content.*;import java.io.*;
@RunWith(AndroidJUnit4.class) public class RawCastDownloadsTest {
 Context context;File root;DirectDownloads manager;
 @Before public void before()throws Exception{context=InstrumentationRegistry.getInstrumentation().getTargetContext();root=new File(context.getCacheDir(),"torrent-fixture-"+System.nanoTime());Assert.assertTrue(root.mkdirs());}
 @After public void after(){if(manager!=null){manager.worker.shutdownNow();if(manager.engine!=null)manager.engine.stop();}delete(root);}void delete(File file){File[] rows=file.listFiles();if(rows!=null)for(File child:rows)delete(child);file.delete();}
 @Test public void legacyFilesAreImportedOnceAndHistoryDoesNotDeleteVideo()throws Exception{File file=new File(root,"Fixture.mp4");try(FileOutputStream out=new FileOutputStream(file)){out.write(new byte[1024]);}JSONObject row=new JSONObject().put("id","legacy").put("title","Fixture").put("state","completed").put("file",file.toString());try(FileOutputStream out=new FileOutputStream(new File(root,"direct-downloads.json"))){out.write(new JSONArray().put(row).toString().getBytes("UTF-8"));}manager=new DirectDownloads(context,root);Assert.assertEquals("Legacy fixture must be imported into the queue",1,manager.jobs.size());Assert.assertEquals("Imported fixture must be listed",1,manager.list().length());manager.action("legacy","history");Assert.assertTrue(file.isFile());manager.worker.shutdownNow();manager=new DirectDownloads(context,root);Assert.assertEquals(0,manager.list().length());}
 @Test public void restartRecoversInterruptedJobsButPreservesManualPause()throws Exception{JSONArray rows=new JSONArray().put(new JSONObject().put("id","active").put("state","downloading")).put(new JSONObject().put("id","paused").put("state","paused"));try(FileOutputStream out=new FileOutputStream(new File(root,"torrent-downloads.json"))){out.write(rows.toString().getBytes("UTF-8"));}manager=new DirectDownloads(context,root);Assert.assertEquals("queued",manager.list().getJSONObject(0).getString("state"));Assert.assertEquals("paused",manager.list().getJSONObject(1).getString("state"));}
 @Test public void secureTspKeyStorage()throws Exception{TspSearchProvider api=new TspSearchProvider(context);api.save("https://api.tspsearch.dev","fixture.secret-key",true,3,60);Assert.assertEquals("fixture.secret-key",api.key());Assert.assertFalse(api.prefs.getString("key","").contains("fixture.secret-key"));api.prefs.edit().clear().commit();}
 @Test public void nativeTorrentEngineLoadsForDeviceAbi(){com.frostwire.jlibtorrent.SessionManager engine=TorrentRuntime.create();try{engine.start();Assert.assertNotNull(engine.saveState());}finally{engine.stop();}}
 @Test public void builtInPlayerSupportsDownloadedContainers()throws Exception{for(String format:new String[]{"mp4","mkv","webm"}){File target=new File(root,"playback."+format);try(InputStream in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("fixture."+format);FileOutputStream out=new FileOutputStream(target)){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);}Assert.assertTrue(format+" must be playable with the built-in player",MediaFiles.playable(context,target,format));}}
}
