package com.zerostreams.app;
import androidx.test.ext.junit.runners.AndroidJUnit4;import androidx.test.platform.app.InstrumentationRegistry;import org.junit.*;import org.junit.runner.RunWith;import org.json.*;import android.content.*;import java.io.*;import java.net.*;import java.util.concurrent.atomic.*;
@RunWith(AndroidJUnit4.class) public class RawCastDownloadsTest {
 Context context;File root;DirectDownloads manager;byte[] video=new byte[8192];
 @Before public void before()throws Exception{context=InstrumentationRegistry.getInstrumentation().getTargetContext();root=new File(context.getCacheDir(),"direct-fixture-"+System.nanoTime());Assert.assertTrue(root.mkdirs());System.arraycopy("ftypisom".getBytes("US-ASCII"),0,video,4,8);}
 @After public void after(){if(manager!=null)manager.worker.shutdownNow();delete(root);}void delete(File file){File[] rows=file.listFiles();if(rows!=null)for(File child:rows)delete(child);file.delete();}
 HttpURLConnection response(long offset){try{return new HttpURLConnection(new URL("https://fixture.invalid/video.mp4")){public void connect(){}public boolean usingProxy(){return false;}public void disconnect(){}public int getResponseCode(){return offset>0?206:200;}public String getContentType(){return "video/mp4";}public String getHeaderField(String name){if(name.equalsIgnoreCase("Content-Length"))return String.valueOf(video.length-offset);if(name.equalsIgnoreCase("Content-Range")&&offset>0)return "bytes "+offset+"-"+(video.length-1)+"/"+video.length;if(name.equalsIgnoreCase("ETag"))return "fixture-v1";return null;}public InputStream getInputStream(){return new ByteArrayInputStream(video,(int)offset,video.length-(int)offset);}};}catch(Exception e){throw new RuntimeException(e);}}
 void ready()throws Exception{for(int i=0;i<200;i++){if(manager.list().optJSONObject(0).optString("state").equals("completed"))return;Thread.sleep(20);}Assert.fail("Download did not complete: "+manager.list());}
 @Test public void queueDuplicatePersistenceMissingFileAndHistoryOnlyRemoval()throws Exception{manager=new DirectDownloads(context,root,j->"https://fixture.invalid/video.mp4",(url,offset,validator)->response(offset));String id=manager.add("movie","550","Fixture Movie","1999","",1,1,"");Assert.assertEquals(id,manager.add("movie","550","Fixture Movie","1999","",1,1,""));ready();JSONObject row=manager.list().getJSONObject(0);File file=new File(row.getString("file"));Assert.assertTrue(file.isFile());Assert.assertEquals(video.length,file.length());manager.action(id,"history");Assert.assertTrue("History removal must preserve the video",file.isFile());Assert.assertEquals(0,manager.list().length());String second=manager.add("tv","1399","Fixture Series","","",1,3,"Episode");ready();row=manager.list().getJSONObject(0);file=new File(row.getString("file"));Assert.assertTrue(file.delete());Assert.assertEquals("missing",manager.list().getJSONObject(0).getString("state"));manager.action(second,"delete");Assert.assertEquals(0,manager.list().length());}
 @Test public void partialFileResumesAndDeleteRemovesActualFile()throws Exception{File folder=new File(root,"ZeroPlay");Assert.assertTrue(folder.mkdirs());File target=new File(folder,"Fixture.mp4");try(FileOutputStream out=new FileOutputStream(target+".part")){out.write(video,0,100);}JSONObject row=new JSONObject().put("id","resume").put("tmdb","550").put("type","movie").put("title","Fixture").put("season",1).put("episode",1).put("state","downloading").put("file",target.toString());try(FileOutputStream out=new FileOutputStream(new File(root,"direct-downloads.json"))){out.write(new JSONArray().put(row).toString().getBytes("UTF-8"));}AtomicLong requested=new AtomicLong();manager=new DirectDownloads(context,root,j->"https://fixture.invalid/video.mp4",(url,offset,validator)->{requested.set(offset);return response(offset);});manager.pump();ready();Assert.assertEquals(100,requested.get());Assert.assertEquals(video.length,target.length());manager.action("resume","delete");Assert.assertFalse(target.exists());}
 @Test public void secureKeyStorageAndRemoval()throws Exception{RawCast api=RawCast.get(context);api.remove();String fixture="rc_"+"live_"+new String(new char[32]).replace('\0','A');api.save(fixture);Assert.assertEquals(fixture,api.key());Assert.assertFalse(context.getSharedPreferences("rawcast-secure",Context.MODE_PRIVATE).getString("key","").contains(fixture));Assert.assertTrue(api.saved());api.remove();Assert.assertFalse(api.saved());Assert.assertFalse(api.hasKey());}
 @Test public void historyStorageFailurePausesQueueWithoutNetwork()throws Exception{Assert.assertTrue(new File(root,"direct-downloads.json").mkdirs());AtomicInteger calls=new AtomicInteger();manager=new DirectDownloads(context,root,j->{calls.incrementAndGet();return "https://fixture.invalid/video.mp4";},(url,offset,validator)->response(offset));manager.add("movie","550","Fixture","1999","",1,1,"");Assert.assertEquals("paused",manager.list().getJSONObject(0).getString("state"));Assert.assertTrue(manager.list().getJSONObject(0).getString("error").contains("storage"));Assert.assertEquals(0,calls.get());}
 @Test public void safeNames(){Assert.assertEquals("Movie_ _ (2024).mp4",DirectDownloads.filename("Movie: ?","2024","movie",1,1,""));Assert.assertEquals("Series - S01E03 - Episode.mp4",DirectDownloads.filename("Series","","tv",1,3,"Episode"));Assert.assertTrue(DirectDownloads.filename("CON","","movie",1,1,"").startsWith("ZeroPlay"));}
 @Test public void builtInPlayerSupportsDownloadedContainers()throws Exception{for(String format:new String[]{"mp4","mkv","webm"}){File target=new File(root,"playback."+format);try(InputStream in=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("fixture."+format);FileOutputStream out=new FileOutputStream(target)){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);}Assert.assertTrue(format+" must be playable with the built-in player",MediaFiles.playable(context,target,format));}}

}
