const {JSDOM}=require('jsdom'),fs=require('node:fs'),assert=require('node:assert/strict');
const dom=new JSDOM(fs.readFileSync('web/public/index.html','utf8'),{runScripts:'outside-only',url:'https://zerostreams.example'}),w=dom.window;
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.open=()=>{};w.scrollTo=()=>{};
const movie={id:299534,title:'Avengers: Endgame',poster_path:'/test.jpg',backdrop_path:'/backdrop.jpg',release_date:'2019-04-24',media_type:'movie',vote_average:8,overview:'A story.'};let requests=[];
w.fetch=async url=>{const parsed=new URL(url,w.location.href);requests.push(parsed);const route=parsed.searchParams.get('path');let data={results:[movie],total_pages:2};if(route.includes('providers'))data={results:[]};if(route==='/movie/299534')data={...movie,genres:[{name:'Adventure'}],credits:{cast:[],crew:[]},videos:{results:[]},recommendations:{results:[]}};return {ok:true,json:async()=>data};};
const errors=[];w.addEventListener('error',event=>errors.push(event.message));w.eval(fs.readFileSync('web/public/browser.js','utf8'));w.eval(fs.readFileSync('web/public/app.js','utf8'));
const tick=()=>new Promise(resolve=>setTimeout(resolve,30));
(async()=>{
  await tick();assert.ok(w.document.querySelector('#hero'));assert.equal(w.document.querySelectorAll('[data-nav="Live"],[data-nav="Manga"]').length,0);assert.equal(w.document.querySelector('#api-key'),null);
  w.document.querySelector('#query').value='my own movie';w.document.querySelector('#search-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await tick();assert.ok(requests.some(url=>url.searchParams.get('path')==='/search/multi'&&url.searchParams.get('query')==='my own movie'));
  w.document.querySelector('[data-detail]').click();await tick();assert.ok(w.document.querySelector('#detail').open);w.document.querySelector('#detail [data-favorite]').click();await tick();assert.equal((await w.zero.state()).favorites.length,1);
  w.document.querySelector('#detail [data-play]').click();await tick();let iframe=w.document.querySelector('#player-stage iframe');assert.ok(iframe.src.includes('vidstuck.xyz/embed/movie/299534'));assert.equal(iframe.sandbox?.contains('allow-popups')||iframe.getAttribute('sandbox').includes('allow-popups'),false);assert.equal(w.document.querySelector('#web-player').open,true);
  const data={id:299534,type:'movie',timestamp:180,duration:1200};w.dispatchEvent(new w.MessageEvent('message',{origin:'https://attacker.example',source:iframe.contentWindow,data}));assert.equal((await w.zero.state()).positions['movie:299534'].percent,undefined);
  w.dispatchEvent(new w.MessageEvent('message',{origin:'https://vidstuck.xyz',source:iframe.contentWindow,data}));assert.equal((await w.zero.state()).positions['movie:299534'].percent,15);
  w.document.querySelector('#close-player').click();await tick();assert.equal(w.document.querySelector('#player-stage iframe'),null);assert.equal(w.document.querySelector('#web-player').open,false);
  await w.zero.play({id:1399,type:'tv',title:'A series'},{season:0,episode:2});iframe=w.document.querySelector('#player-stage iframe');assert.ok(iframe.src.includes('/embed/tv/1399/0/2'));w.document.querySelector('#close-player').click();await tick();
  assert.equal((await w.zero.state()).positions['tv:1399'].season,0);assert.ok(w.localStorage.getItem('zerostreams-web-v1').includes('my own movie'));assert.deepEqual(errors,[]);console.log('Website search, library, player URL, origin-bound progress, close behavior and TV specials checks passed');w.close();
})().catch(error=>{console.error(error);w.close();process.exitCode=1;});
