package com.zerostreams.app;
import android.content.*;import android.os.*;import java.io.*;import java.util.*;import java.util.concurrent.*;import org.json.*;import com.frostwire.jlibtorrent.*;
/** Integrated libtorrent queue. TSP performs search, never the transfer. */
final class DirectDownloads {
 static DirectDownloads instance;static synchronized DirectDownloads get(Context c){if(instance==null)instance=new DirectDownloads(c.getApplicationContext());return instance;}
 final Context context;File folder;final File index;final List<JSONObject> jobs=new ArrayList<>();final ExecutorService worker=Executors.newSingleThreadExecutor();SessionManager engine;final Map<String,TorrentHandle> handles=new HashMap<>();Runnable listener;volatile boolean running;
 DirectDownloads(Context c){this(c,null);} DirectDownloads(Context c,File testRoot){context=c;File base=c.getExternalFilesDir(Environment.DIRECTORY_MOVIES);String saved=c.getSharedPreferences("torrentSearchSettings-secure",0).getString("folder","");folder=testRoot!=null?new File(testRoot,"ZeroPlay"):saved.isEmpty()?new File(base==null?c.getFilesDir():base,"ZeroPlay"):new File(saved);folder.mkdirs();index=new File(testRoot==null?c.getFilesDir():testRoot,"torrent-downloads.json");try{JSONArray all=new JSONArray(Catalog.read(new FileInputStream(index),2_000_000));for(int i=0;i<all.length();i++){JSONObject j=all.getJSONObject(i);if(Arrays.asList("downloading","preparing","queued").contains(j.optString("state")))j.put("state","queued");jobs.add(j);}}catch(Exception ignored){}importLegacy(); }
 void importLegacy(){File marker=new File(index.getParentFile(),"legacy-imported"),legacyFile=new File(index.getParentFile(),"direct-downloads.json");if(marker.exists())return;if(legacyFile.isFile())try(FileInputStream in=new FileInputStream(legacyFile)){JSONArray rows=new JSONArray(Catalog.read(in,2_000_000));for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if(!"completed".equals(row.optString("state"))||!new File(row.optString("file")).isFile())continue;boolean exists=false;for(JSONObject current:jobs)if(current.optString("id").equals(row.optString("id"))){exists=true;break;}if(!exists){row.put("legacy",true);jobs.add(row);}}}catch(Exception e){android.util.Log.w("ZeroPlayDownloads","Legacy import failed: "+e.getClass().getSimpleName());return;}save();try{marker.createNewFile();}catch(IOException ignored){} }

 synchronized void set(JSONObject j,String k,Object v){try{j.put(k,v);}catch(Exception ignored){}}
 synchronized void save(){try{File tmp=new File(index+".tmp");try(FileOutputStream out=new FileOutputStream(tmp)){out.write(new JSONArray(jobs).toString().getBytes("UTF-8"));out.getFD().sync();}if(!tmp.renameTo(index))throw new IOException();}catch(Exception e){for(JSONObject j:jobs)if(!j.optString("state").equals("completed")){set(j,"state","paused");set(j,"error","Cannot save download history. Check storage.");}if(engine!=null)for(TorrentHandle h:handles.values())h.pause();}}
 synchronized void update(){save();if(listener!=null)new Handler(Looper.getMainLooper()).post(listener);}
 synchronized JSONArray list(){for(JSONObject j:jobs)if(j.optString("state").equals("completed")&&!new File(j.optString("file")).isFile())set(j,"state","missing");try{return new JSONArray(new JSONArray(jobs).toString());}catch(Exception e){return new JSONArray();}}
 synchronized String add(Catalog.Item item,int season,int episode,JSONObject result,byte[] metadata)throws Exception{String id=result.getString("id");if(!id.matches("[a-f0-9]{40}"))throw new IOException("Invalid torrent hash.");for(JSONObject j:jobs)if(j.optString("id").equals(id))return id;File dir=new File(folder,"torrent-"+id);if(!dir.mkdirs()&&!dir.isDirectory())throw new IOException("Check storage.");String magnet=result.optString("magnet");if(metadata!=null)try(FileOutputStream out=new FileOutputStream(new File(dir,"metadata.torrent"))){out.write(metadata);}
 JSONObject j=new JSONObject().put("id",id).put("title",item.title).put("description",item.description).put("tmdb",item.id.substring(item.id.lastIndexOf('-')+1)).put("type",item.type.equals("series")?"tv":"movie").put("season",season).put("episode",episode).put("poster",item.poster).put("dir",dir.toString()).put("magnet",magnet).put("state","queued").put("bytes",0).put("total",result.optLong("size_bytes")).put("speed",0).put("error","");set(j,"created",System.currentTimeMillis());set(j,"resolution",result.optString("resolution"));set(j,"codec",result.optString("codec"));set(j,"health",result.optInt("health_score",result.optInt("healthScore",0)));set(j,"seeders",result.optInt("seeders",0));set(j,"leechers",result.optInt("leechers",0));jobs.add(j);update();start();return id;}
 void start(){Intent i=new Intent(context,TorrentDownloadService.class);if(Build.VERSION.SDK_INT>=26)context.startForegroundService(i);else context.startService(i);}
 synchronized boolean hasWork(){for(JSONObject j:jobs)if(Arrays.asList("queued","preparing","downloading").contains(j.optString("state")))return true;return false;}
 synchronized void pump(){if(running)return;running=true;worker.execute(()->{try{if(engine==null){engine=TorrentRuntime.create();engine.start();File state=new File(index.getParentFile(),"torrent-session.dat");try{engine.loadState(readBytes(state));}catch(Exception ignored){}installResumeListener();}while(hasWork()){if(engine!=null){if(canTransfer())engine.resume();else engine.pause();}for(JSONObject j:jobSnapshot()){if(j.optString("state").equals("queued")&&canTransfer()&&activeCount()<TspSearchProvider.get(context).prefs.getInt("maxActive",2))begin(j);if(j.optString("state").equals("downloading")){TorrentHandle h=handles.get(j.optString("id"));if(h!=null){TorrentStatus s=h.status(true);set(j,"bytes",s.totalWantedDone());set(j,"total",s.totalWanted());set(j,"speed",canTransfer()?Math.round(j.optLong("speed")*.7+s.downloadRate()*.3):0);set(j,"peers",s.numPeers());if(s.isFinished()){set(j,"state","completed");set(j,"completed",System.currentTimeMillis());set(j,"speed",0);h.pause();h.saveResumeData();}}}}update();Thread.sleep(1000);}}catch(Exception|LinkageError e){synchronized(this){for(JSONObject j:jobs)if(Arrays.asList("queued","preparing","downloading").contains(j.optString("state"))){set(j,"state","failed");set(j,"error","Torrent engine failed. Check network and storage.");}update();}}finally{running=false;}});}
 void begin(JSONObject j){try{set(j,"state","preparing");update();File dir=new File(j.getString("dir")),meta=new File(dir,"metadata.torrent");if(!meta.isFile()){byte[] b=engine.fetchMagnet(j.getString("magnet"),60,true);if(b==null)throw new IOException("Torrent metadata timed out. Try again when peers are available.");try(FileOutputStream out=new FileOutputStream(meta)){out.write(b);}}if(!j.optString("state").equals("preparing"))return;TorrentInfo ti=new TorrentInfo(meta);FileStorage files=ti.files();int chosen=-1;long largest=0;JSONArray choices=new JSONArray();Priority[] priorities=new Priority[files.numFiles()];Arrays.fill(priorities,Priority.IGNORE);String pattern=String.format(Locale.ROOT,"(?i).*S%02dE%02d.*",j.optInt("season"),j.optInt("episode"));for(int n=0;n<files.numFiles();n++){String name=files.filePath(n);File target=new File(dir,name);if(!target.getCanonicalPath().startsWith(dir.getCanonicalPath()+File.separator))throw new IOException("Unsafe torrent file path.");if(name.matches("(?i).*\\.(mp4|mkv|webm|m4v|mov|avi)$")&&!name.toLowerCase(Locale.ROOT).contains("sample")&&(!j.optString("type").equals("tv")||name.matches(pattern))){choices.put(new JSONObject().put("index",n).put("path",name).put("size",files.fileSize(n)));if(files.fileSize(n)>largest){chosen=n;largest=files.fileSize(n);}}}if(chosen<0)throw new IOException("No matching playable video in torrent.");if(j.has("selectedIndex")){chosen=j.getInt("selectedIndex");boolean valid=false;for(int i=0;i<choices.length();i++)if(choices.getJSONObject(i).getInt("index")==chosen)valid=true;if(!valid)throw new IOException("Selected file is unavailable.");}else{int large=0;for(int i=0;i<choices.length();i++)if(choices.getJSONObject(i).getLong("size")>=largest/2)large++;if(large>1){set(j,"files",choices);set(j,"state","selecting");update();return;}}priorities[chosen]=Priority.NORMAL;for(int n=0;n<files.numFiles();n++)if(files.filePath(n).matches("(?i).*\\.(srt|vtt|ass)$"))priorities[n]=Priority.NORMAL;set(j,"file",new File(dir,files.filePath(chosen)).toString());String name=files.filePath(chosen),format=name.substring(name.lastIndexOf('.')+1).toLowerCase(Locale.ROOT);set(j,"format",format);set(j,"mime",MediaFiles.mime(format));engine.download(ti,dir,new File(dir,"resume.dat"),priorities,null);TorrentHandle h=null;for(int n=0;n<100&&h==null;n++){Thread.sleep(100);h=engine.find(ti.infoHash());}if(h==null)throw new IOException("Torrent could not start.");handles.put(j.getString("id"),h);h.saveResumeData();if(!j.optString("state").equals("preparing")){h.pause();return;}h.resume();set(j,"state","downloading");}catch(Exception e){if(Arrays.asList("paused","cancelled").contains(j.optString("state")))return;set(j,"state","failed");set(j,"error",e instanceof IOException?e.getMessage():"Could not start torrent. Check metadata and storage.");}update();}
 synchronized void pauseAll(){for(JSONObject j:jobs)if(Arrays.asList("queued","preparing","downloading").contains(j.optString("state"))){set(j,"state","paused");TorrentHandle h=handles.get(j.optString("id"));if(h!=null)h.pause();}update();}
 synchronized void action(String id,String action)throws Exception{JSONObject j=null;for(JSONObject row:jobs)if(row.optString("id").equals(id))j=row;if(j==null)throw new IOException("Download not found.");TorrentHandle h=handles.get(id);if(action.startsWith("select:")){int selected=Integer.parseInt(action.substring(7));JSONArray files=j.optJSONArray("files");boolean valid=false;if(files!=null)for(int i=0;i<files.length();i++)if(files.getJSONObject(i).getInt("index")==selected)valid=true;if(!valid)throw new IOException("Select a listed file.");set(j,"selectedIndex",selected);set(j,"state","queued");start();}else if(action.equals("pause")||action.equals("cancel")){if(h!=null){h.pause();h.saveResumeData();}set(j,"state",action.equals("pause")?"paused":"cancelled");}else if(action.equals("resume")||action.equals("retry")){if(j.optBoolean("legacy"))throw new IOException("This legacy file cannot be downloaded again.");set(j,"state","queued");start();}else if(action.equals("history")||action.equals("delete")){if(Arrays.asList("queued","preparing","downloading").contains(j.optString("state")))throw new IOException("Pause or cancel first.");if(h!=null){engine.remove(h);handles.remove(id);}if(action.equals("delete")){if(j.optBoolean("legacy")){File f=new File(j.optString("file"));if(f.exists()&&!f.delete())throw new IOException("Could not delete video.");}else delete(new File(j.optString("dir")));}jobs.remove(j);}else throw new IOException("Unsupported action.");update();}
  synchronized List<JSONObject> jobSnapshot(){return new ArrayList<>(jobs);} synchronized int activeCount(){int count=0;for(JSONObject j:jobs)if(Arrays.asList("preparing","downloading").contains(j.optString("state")))count++;return count;}
 boolean canTransfer(){android.net.ConnectivityManager cm=(android.net.ConnectivityManager)context.getSystemService(Context.CONNECTIVITY_SERVICE);android.net.NetworkInfo n=cm.getActiveNetworkInfo();if(n==null||!n.isConnected())return false;return !TspSearchProvider.get(context).prefs.getBoolean("wifiOnly",true)||n.getType()==android.net.ConnectivityManager.TYPE_WIFI||n.getType()==android.net.ConnectivityManager.TYPE_ETHERNET;}
 static byte[] readBytes(File file)throws IOException{try(FileInputStream in=new FileInputStream(file);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>8_000_000)throw new IOException();}return out.toByteArray();}}
 void installResumeListener(){engine.addListener(new AlertListener(){public int[] types(){return new int[]{com.frostwire.jlibtorrent.alerts.AlertType.SAVE_RESUME_DATA.swig()};}public void alert(com.frostwire.jlibtorrent.alerts.Alert<?> alert){try{com.frostwire.jlibtorrent.alerts.SaveResumeDataAlert a=(com.frostwire.jlibtorrent.alerts.SaveResumeDataAlert)alert;String hash=a.handle().infoHash().toHex();for(JSONObject j:jobSnapshot())if(j.optString("id").equals(hash)){File file=new File(j.getString("dir"),"resume.dat");try(FileOutputStream out=new FileOutputStream(file)){com.frostwire.jlibtorrent.swig.byte_vector bytes=com.frostwire.jlibtorrent.swig.add_torrent_params.write_resume_data_buf(a.params().swig());byte[] data=new byte[(int)bytes.size()];for(int i=0;i<data.length;i++)data[i]=(byte)bytes.get(i);out.write(data);}}byte[] state=engine.saveState();if(state!=null)try(FileOutputStream out=new FileOutputStream(new File(index.getParentFile(),"torrent-session.dat"))){out.write(state);}}catch(Exception ignored){}}});}
 void delete(File f)throws IOException{File[] children=f.listFiles();if(children!=null)for(File child:children)delete(child);if(f.exists()&&!f.delete())throw new IOException("Could not delete download files.");}
}
