package com.zerostreams.app;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.SharedPreferences;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.text.*;
import org.json.*;
import java.net.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    static final int BG=Color.rgb(9,10,16),SURFACE=Color.rgb(22,24,34),INK=Color.rgb(244,245,250),MUTED=Color.rgb(157,162,181),ACCENT=Color.rgb(101,230,204);
    private static final String FEED="https://raw.githubusercontent.com/Zer0Spce/ZeroMovies/main/public/catalog.json";
    private static final String SERIES="https://raw.githubusercontent.com/Zer0Spce/ZeroMovies/main/public/series/";
    private final ExecutorService io=Executors.newFixedThreadPool(3);
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final android.util.LruCache<String,Bitmap> pictures=new android.util.LruCache<String,Bitmap>(12*1024*1024){@Override protected int sizeOf(String key,Bitmap value){return value.getByteCount();}};
    private List<Catalog.Item> catalog=new ArrayList<>(),browse=new ArrayList<>();
    private SharedPreferences prefs;
    private LinearLayout content;private TextView status;private EditText search;private ScrollView scroll;
    private String category="Home",query="",collection="",sort="Featured";private int loadVersion,renderVersion,mangaOffset,searchPage=1,searchVersion;private long lastRequested;private boolean ready;
    private final Map<String,Button> navigation=new LinkedHashMap<>();
    private final Runnable remoteSearch=()->{if(category.equals("Manga"))load();else if(category.equals("Search"))onlineSearch();};
    int dp(float n){return(int)(getResources().getDisplayMetrics().density*n+.5f);}
    LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);return t;}
    GradientDrawable shape(int color,int border){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(10));if(border!=0)d.setStroke(dp(2),border);return d;}
    Button button(String label,Runnable action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextColor(INK);b.setTextSize(BuildConfig.TV?15:13);b.setMinWidth(0);b.setMinimumWidth(0);b.setPadding(dp(12),dp(5),dp(12),dp(5));b.setBackground(shape(SURFACE,0));b.setFocusable(true);b.setOnClickListener(v->action.run());b.setOnFocusChangeListener((v,f)->{v.setBackground(shape(f?Color.rgb(34,57,58):SURFACE,f?ACCENT:0));});return b;}
    void bold(TextView t){t.setTypeface(null,Typeface.BOLD);}
    void space(LinearLayout parent,int height){parent.addView(new View(this),new LinearLayout.LayoutParams(1,dp(height)));}
    void message(String value){Toast.makeText(this,value,Toast.LENGTH_LONG).show();}
    @Override public void onCreate(Bundle state){
        super.onCreate(state);prefs=getSharedPreferences("zero",MODE_PRIVATE);if(state!=null){category=state.getString("category","Home");query=state.getString("query","");collection=state.getString("collection","");}
        LinearLayout outer=new LinearLayout(this);outer.setBackgroundColor(BG);
        if(BuildConfig.TV){LinearLayout rail=column();rail.setPadding(dp(20),dp(32),dp(12),dp(20));rail.setBackgroundColor(Color.rgb(12,14,22));TextView z=text("Z",34,ACCENT);bold(z);rail.addView(z);space(rail,28);for(String tab:new String[]{"Home","Movies","Series","Live","Manga"}){Button b=nav(tab);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(46));p.setMargins(0,0,0,dp(8));rail.addView(b,p);}space(rail,20);rail.addView(button("Search",this::focusSearch));space(rail,10);rail.addView(button("My library",this::libraryMenu));space(rail,10);rail.addView(button("Settings",this::settings));outer.addView(rail,new LinearLayout.LayoutParams(dp(144),-1));}
        LinearLayout body=column();outer.addView(body,new LinearLayout.LayoutParams(0,-1,1));
        LinearLayout header=new LinearLayout(this);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(BuildConfig.TV?30:20),dp(14),dp(20),dp(12));TextView logo=text("ZEROSTREAMS",BuildConfig.TV?23:19,INK);bold(logo);logo.setSingleLine(true);logo.setEllipsize(TextUtils.TruncateAt.END);logo.setLetterSpacing(.06f);header.addView(logo,new LinearLayout.LayoutParams(0,-2,1));Button library=button(BuildConfig.TV?"My library":"Library",this::libraryMenu);header.addView(library);Button settings=button("Settings",this::settings);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-2,dp(40));hp.setMargins(dp(8),0,0,0);header.addView(settings,hp);body.addView(header);
        search=new EditText(this);search.setSingleLine(true);search.setTextColor(INK);search.setHintTextColor(MUTED);search.setTextSize(15);search.setHint("Search movies and series");search.setText(query);search.setBackground(shape(SURFACE,0));search.setPadding(dp(16),dp(8),dp(16),dp(8));search.setContentDescription("Search titles");search.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);search.setInputType(android.text.InputType.TYPE_CLASS_TEXT);search.setSelectAllOnFocus(BuildConfig.TV);search.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(search.getWindowToken(),0);ui.removeCallbacks(remoteSearch);if(category.equals("Manga"))load();else if(category.equals("Search"))onlineSearch();else render();return true;}return false;});LinearLayout.LayoutParams qp=new LinearLayout.LayoutParams(-1,dp(46));qp.setMargins(dp(BuildConfig.TV?30:20),0,dp(20),dp(6));body.addView(search,qp);
        status=text("Loading…",12,MUTED);status.setPadding(dp(BuildConfig.TV?30:20),dp(4),dp(20),dp(4));body.addView(status);
        scroll=new ScrollView(this);scroll.setFillViewport(true);content=column();content.setPadding(dp(BuildConfig.TV?30:20),dp(14),dp(20),dp(28));scroll.addView(content);body.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        if(!BuildConfig.TV){LinearLayout bar=new LinearLayout(this);bar.setPadding(dp(8),dp(8),dp(8),dp(8));bar.setBackgroundColor(Color.rgb(14,16,25));for(String tab:new String[]{"Home","Movies","Series","Live","Manga"})bar.addView(nav(tab),new LinearLayout.LayoutParams(0,dp(46),1));body.addView(bar);}
        outer.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int b,int c){query=s.toString();mangaOffset=0;searchPage=1;++searchVersion;ui.removeCallbacks(remoteSearch);if(category.equals("Manga"))ui.postDelayed(remoteSearch,700);else{if(category.equals("Home")||category.equals("Movies")||category.equals("Series")||category.equals("Search")){category=query.trim().isEmpty()?"Home":"Search";if(!browse.isEmpty())catalog=new ArrayList<>(browse);if(category.equals("Search"))ui.postDelayed(remoteSearch,650);}render();}}});
        setContentView(outer);ready=true;load();if(BuildConfig.TV)(navigation.containsKey(category)?navigation.get(category):navigation.get("Home")).requestFocus();
    }
    void focusSearch(){if(!category.equals("Manga")&&!category.equals("Live")){category="Search";collection="";catalog=new ArrayList<>(browse);render();}search.requestFocus();((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);}
    Button nav(String tab){Button b=button(tab,()->open(tab));navigation.put(tab,b);return b;}
    void open(String tab){++searchVersion;query="";search.setText("");ui.removeCallbacks(remoteSearch);category=tab;search.setHint(tab.equals("Manga")?"Search manga":tab.equals("Live")?"Search live events":"Search movies and series");collection="";mangaOffset=0;scroll.scrollTo(0,0);if(tab.equals("Live")||tab.equals("Manga"))load();else{++loadVersion;catalog=new ArrayList<>(browse);render();if(browse.isEmpty())load();}}
    @Override protected void onResume(){super.onResume();if(ready){render();if(SystemClock.elapsedRealtime()-lastRequested>300_000)load();}}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("category",category);state.putString("query",query);state.putString("collection",collection);}
    void load(){if(category.equals("Search")&&!query.trim().isEmpty()&&!tmdbKey().isEmpty()){onlineSearch();return;}++renderVersion;lastRequested=SystemClock.elapsedRealtime();int token=++loadVersion;String section=category,endpoint=prefs.getString("endpoint",FEED),live=prefs.getString("liveEndpoint",ContentApi.LIVE),q=query;int offset=mangaOffset;status.setText("Updating "+section.toLowerCase(Locale.ROOT)+"…");
        io.execute(()->{try{List<Catalog.Item> rows=section.equals("Manga")?ContentApi.manga(q,offset):section.equals("Live")?ContentApi.live(live):Catalog.load(this,endpoint);ui.post(()->{if(isDestroyed()||token!=loadVersion)return;catalog=rows;if(!section.equals("Live")&&!section.equals("Manga"))browse=new ArrayList<>(rows);status.setText(section.equals("Manga")?"MangaDex · English chapters":section.equals("Live")?"Today's sports · times and availability from source":endpoint.isEmpty()?"Demo catalog":"Catalog updated · "+rows.size()+" titles");render();});}
        catch(Exception e){ui.post(()->{if(isDestroyed()||token!=loadVersion)return;catalog=new ArrayList<>();status.setText("Content service unavailable. Retry or check Settings.");render();message(e.getMessage());});}});
    }

    String tmdbKey(){String configured=prefs.getString("tmdbKey","").trim();return configured.isEmpty()?BuildConfig.DEFAULT_TMDB_KEY:configured;}
    void onlineSearch(){
        if(!category.equals("Search")||query.trim().isEmpty())return;
        String key=tmdbKey();if(key.isEmpty()){status.setText("Catalog search · add your TMDB API key in Settings for online search");return;}
        int token=++searchVersion;++loadVersion;String requested=query.trim();int page=searchPage;status.setText("Searching movies and series online…");
        io.execute(()->{try{List<Catalog.Item> rows=ContentApi.searchMovies(requested,key,page);ui.post(()->{if(isDestroyed()||token!=searchVersion||!category.equals("Search"))return;catalog=rows;status.setText("TMDB search · page "+page+" · "+rows.size()+" titles");render();});}
            catch(Exception e){ui.post(()->{if(isDestroyed()||token!=searchVersion||!category.equals("Search"))return;catalog=new ArrayList<>(browse);searchPage=1;status.setText("Online search unavailable · showing catalog matches. Check your TMDB key in Settings.");render();});}});
    }
    Set<String> favorites(){return new HashSet<>(prefs.getStringSet("favorites",Collections.emptySet()));}
    Set<String> savedIds(String key){return new HashSet<>(prefs.getStringSet(key,Collections.emptySet()));}
    boolean matches(Catalog.Item item){if(!query.isEmpty()&&!item.raw.optBoolean("onlineSearch")&&!TitleSearch.matches(item.title,query)&&!item.id.equalsIgnoreCase(query.trim())&&!item.id.substring(item.id.lastIndexOf('-')+1).equals(query.trim())&&!category.equals("Manga"))return false;
        switch(category){case"Search":return item.type.equals("movie")||item.type.equals("series");case"Movies":return item.type.equals("movie");case"Series":return item.type.equals("series");case"Live":return item.type.equals("live");case"Manga":return item.type.equals("manga");case"Watchlist":return favorites().contains(item.id);case"Continue":return prefs.getLong("position:"+item.id,0)>0;case"Collections":return savedIds("collection:"+collection).contains(item.id);default:return true;}}
    void render(){if(content==null)return;int token=++renderVersion;content.removeAllViews();for(Map.Entry<String,Button> entry:navigation.entrySet()){boolean active=entry.getKey().equals(category);entry.getValue().setTextColor(active?ACCENT:MUTED);}
        if(category.equals("Collections")&&collection.isEmpty()){collections();return;}
        List<Catalog.Item> rows=new ArrayList<>();for(Catalog.Item item:catalog)if(matches(item))rows.add(item);
        if(sort.equals("Newest"))Collections.sort(rows,(a,b)->Integer.compare(b.year,a.year));else if(sort.equals("A–Z"))Collections.sort(rows,(a,b)->a.title.compareToIgnoreCase(b.title));
        if(rows.isEmpty()){TextView empty=text(!query.trim().isEmpty()?"No matches for “"+query.trim()+"”":category.equals("Watchlist")?"Your watchlist starts here.":category.equals("Continue")?"Pick a title to start watching.":"No titles to show right now.",23,INK);bold(empty);content.addView(empty);space(content,10);content.addView(text("Search another title, refresh the catalog, or return to Home.",15,MUTED));space(content,18);if(category.equals("Search")&&searchPage>1){content.addView(button("Previous page",()->{searchPage--;onlineSearch();}));space(content,12);}if(!query.trim().isEmpty()){content.addView(button("Clear search",()->search.setText("")));space(content,12);}content.addView(button("Refresh",this::load));return;}
        if(category.equals("Home")&&query.isEmpty()){
            hero(rows.get(0),token);List<Catalog.Item> resumes=new ArrayList<>(),movies=new ArrayList<>(),shows=new ArrayList<>();for(Catalog.Item item:rows){if(prefs.getLong("position:"+item.id,0)>0)resumes.add(item);if(item.type.equals("movie"))movies.add(item);if(item.type.equals("series"))shows.add(item);}
            if(!resumes.isEmpty())posterRow("Continue watching",resumes,token);
            posterRow("Trending now",rows.subList(0,Math.min(rows.size(),15)),token);posterRow("Popular movies",movies,token);posterRow("Series worth watching",shows,token);
            List<Catalog.Item> newest=new ArrayList<>(movies);Collections.sort(newest,(a,b)->Integer.compare(b.year,a.year));posterRow("Recent releases",newest,token);
        }else{LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);TextView label=text(category.equals("Collections")?collection:!query.trim().isEmpty()?"Search results · "+rows.size():category,BuildConfig.TV?29:26,INK);bold(label);heading.addView(label,new LinearLayout.LayoutParams(0,-2,1));heading.addView(button("Sort",()->new AlertDialog.Builder(this).setTitle("Sort titles").setItems(new String[]{"Featured","Newest","A–Z"},(d,n)->{sort=new String[]{"Featured","Newest","A–Z"}[n];render();}).show()));content.addView(heading);space(content,16);grid(rows,token);}
        if(category.equals("Search")&&!tmdbKey().isEmpty()&&!rows.isEmpty()&&rows.get(0).raw.optBoolean("onlineSearch")){LinearLayout paging=new LinearLayout(this);if(searchPage>1)paging.addView(button("Previous",()->{searchPage--;onlineSearch();scroll.scrollTo(0,0);}));paging.addView(button("Next page",()->{searchPage++;onlineSearch();scroll.scrollTo(0,0);}));content.addView(paging);}
        if(category.equals("Manga")){LinearLayout paging=new LinearLayout(this);if(mangaOffset>0)paging.addView(button("Previous results",()->{mangaOffset=Math.max(0,mangaOffset-40);load();scroll.scrollTo(0,0);}));if(rows.size()==40)paging.addView(button("More manga",()->{mangaOffset+=40;load();scroll.scrollTo(0,0);}));content.addView(paging);}
    }
    void hero(Catalog.Item item,int token){FrameLayout hero=new FrameLayout(this);hero.setBackground(shape(SURFACE,0));ImageView artwork=new ImageView(this);artwork.setScaleType(ImageView.ScaleType.CENTER_CROP);hero.addView(artwork,new FrameLayout.LayoutParams(-1,-1));String backdrop=item.raw.optString("backdrop",item.poster);if(!backdrop.isEmpty())picture(backdrop,artwork,token);
        View gradient=new View(this);gradient.setBackground(new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{0xF0090A10,0xCC090A10,0x40090A10}));hero.addView(gradient,new FrameLayout.LayoutParams(-1,-1));LinearLayout info=column();info.setPadding(dp(BuildConfig.TV?30:22),dp(24),dp(22),dp(22));info.addView(text("FEATURED THIS WEEK",11,ACCENT));space(info,12);TextView title=text(item.title,BuildConfig.TV?40:29,INK);bold(title);title.setMaxLines(2);info.addView(title);space(info,8);info.addView(text(meta(item),13,INK));space(info,10);TextView synopsis=text(item.description,14,MUTED);synopsis.setMaxLines(3);info.addView(synopsis);space(info,16);LinearLayout actions=new LinearLayout(this);Button play=button("Watch now",()->watch(item));play.setTextColor(BG);play.setBackground(shape(ACCENT,0));actions.addView(play);Button details=button("More info",()->details(item));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(44));p.setMargins(dp(10),0,0,0);actions.addView(details,p);info.addView(actions);FrameLayout.LayoutParams ip=new FrameLayout.LayoutParams(BuildConfig.TV?dp(520):-1,-2,Gravity.BOTTOM|Gravity.START);hero.addView(info,ip);content.addView(hero,new LinearLayout.LayoutParams(-1,dp(BuildConfig.TV?330:320)));space(content,24);}
    String meta(Catalog.Item item){return item.type.toUpperCase(Locale.ROOT)+(item.year>0?"  ·  "+item.year:"")+(item.raw.optDouble("rating",0)>0?"  ·  ★ "+String.format(Locale.ROOT,"%.1f",item.raw.optDouble("rating")):"");}
    void posterRow(String title,List<Catalog.Item> rows,int token){if(rows.isEmpty())return;TextView label=text(title,BuildConfig.TV?22:20,INK);bold(label);content.addView(label);space(content,12);HorizontalScrollView rail=new HorizontalScrollView(this);rail.setHorizontalScrollBarEnabled(false);LinearLayout cards=new LinearLayout(this);for(int i=0;i<Math.min(rows.size(),18);i++){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(BuildConfig.TV?150:132),-2);p.setMargins(0,0,dp(12),0);cards.addView(card(rows.get(i),token),p);}rail.addView(cards);content.addView(rail);space(content,26);}
    void grid(List<Catalog.Item> rows,int token){int columns=BuildConfig.TV?5:(getResources().getConfiguration().screenWidthDp>=600?4:2);for(int i=0;i<rows.size();i+=columns){LinearLayout line=new LinearLayout(this);for(int c=0;c<columns;c++){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.setMargins(0,0,dp(c==columns-1?0:12),dp(20));line.addView(i+c<rows.size()?card(rows.get(i+c),token):new View(this),p);}content.addView(line);}}
    LinearLayout card(Catalog.Item item,int token){LinearLayout card=column();card.setPadding(dp(3),dp(3),dp(3),dp(8));card.setBackground(shape(BG,0));card.setFocusable(true);card.setClickable(true);card.setContentDescription(item.title+", "+item.type);card.setOnClickListener(v->details(item));card.setOnFocusChangeListener((v,f)->{v.setBackground(shape(f?SURFACE:BG,f?ACCENT:0));if(BuildConfig.TV)v.animate().scaleX(f?1.035f:1f).scaleY(f?1.035f:1f).setDuration(140).start();});ImageView poster=new ImageView(this);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setImageResource(R.drawable.ic_zero);poster.setBackground(shape(SURFACE,0));poster.setClipToOutline(true);card.addView(poster,new LinearLayout.LayoutParams(-1,dp(BuildConfig.TV?210:190)));if(!item.poster.isEmpty())picture(item.poster,poster,token);space(card,8);TextView title=text(item.title,14,INK);bold(title);title.setMaxLines(2);card.addView(title);space(card,4);card.addView(text(item.year>0?String.valueOf(item.year):item.type.toUpperCase(Locale.ROOT),12,MUTED));return card;}
    void picture(String url,ImageView view,int token){Bitmap cached=pictures.get(url);if(cached!=null){view.setImageBitmap(cached);return;}io.execute(()->{if(token!=renderVersion)return;Bitmap prior=pictures.get(url);if(prior!=null){ui.post(()->{if(!isDestroyed()&&token==renderVersion)view.setImageBitmap(prior);});return;}HttpURLConnection c=null;try{URL address=new URL(url);if(!address.getProtocol().equals("https"))return;c=(HttpURLConnection)address.openConnection();c.setConnectTimeout(7000);c.setReadTimeout(8000);c.setInstanceFollowRedirects(false);if(c.getResponseCode()!=200)return;byte[] bytes;try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>5_000_000)return;out.write(b,0,n);}bytes=out.toByteArray();}BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);int sample=1;int maxWidth=url.contains("/w1280/")?1600:400,maxHeight=url.contains("/w1280/")?1000:600;while(o.outWidth/sample>maxWidth||o.outHeight/sample>maxHeight)sample*=2;o.inSampleSize=sample;o.inJustDecodeBounds=false;Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(bitmap!=null)pictures.put(url,bitmap);ui.post(()->{if(!isDestroyed()&&token==renderVersion&&bitmap!=null)view.setImageBitmap(bitmap);});}catch(Exception ignored){}finally{if(c!=null)c.disconnect();}});}
    void details(Catalog.Item item){
        int token=renderVersion;
        FrameLayout scene=new FrameLayout(this);scene.setBackground(shape(BG,0));scene.setClipToOutline(true);
        BlurArtwork backdrop=new BlurArtwork(this);scene.addView(backdrop,new FrameLayout.LayoutParams(-1,-1));
        String artwork=item.raw.optString("backdrop",item.poster);if(artwork.isEmpty())artwork=item.poster;
        if(!artwork.isEmpty())picture(artwork,backdrop,token);
        View shade=new View(this);shade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0xA0090A10,0xDE090A10,0xF5090A10}));scene.addView(shade,new FrameLayout.LayoutParams(-1,-1));
        LinearLayout panel=column();panel.setPadding(dp(BuildConfig.TV?32:24),dp(28),dp(BuildConfig.TV?32:24),dp(24));
        LinearLayout heading=new LinearLayout(this);heading.setGravity(Gravity.CENTER_VERTICAL);
        ImageView poster=new ImageView(this);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackground(shape(SURFACE,0));poster.setClipToOutline(true);heading.addView(poster,new LinearLayout.LayoutParams(dp(BuildConfig.TV?112:88),dp(BuildConfig.TV?160:128)));if(!item.poster.isEmpty())picture(item.poster,poster,token);
        LinearLayout info=column();info.setPadding(dp(20),0,0,0);info.addView(text(item.type.equals("series")?"EXPLORE THE SERIES":"SELECTED FOR YOU",11,ACCENT));space(info,10);TextView name=text(item.title,BuildConfig.TV?32:26,INK);bold(name);info.addView(name);space(info,12);info.addView(text(meta(item),13,INK));heading.addView(info,new LinearLayout.LayoutParams(0,-2,1));panel.addView(heading);
        space(panel,24);TextView synopsis=text(item.description.isEmpty()?"No synopsis available.":item.description,15,INK);synopsis.setLineSpacing(dp(4),1);panel.addView(synopsis);space(panel,24);
        Button play=button(item.type.equals("manga")?"Read chapters":item.type.equals("series")?"Browse seasons & episodes":"Watch now",()->watch(item));play.setTextColor(BG);play.setBackground(shape(ACCENT,0));play.setOnFocusChangeListener((v,focused)->{v.setBackground(shape(focused?Color.rgb(153,255,230):ACCENT,focused?INK:0));v.animate().scaleX(focused?1.015f:1f).scaleY(focused?1.015f:1f).setDuration(120).start();});panel.addView(play,new LinearLayout.LayoutParams(-1,dp(48)));space(panel,12);
        panel.addView(button(favorites().contains(item.id)?"Remove from watchlist":"Add to watchlist",()->toggleFavorite(item)));space(panel,10);panel.addView(button("Add to collection",()->addCollection(item)));
        ScrollView view=new ScrollView(this);view.setFillViewport(true);view.addView(panel);scene.addView(view,new FrameLayout.LayoutParams(-1,-1));
        AlertDialog dialog=new AlertDialog.Builder(this).setView(scene).setNegativeButton("Close",null).create();dialog.show();
        if(dialog.getWindow()!=null){dialog.getWindow().setBackgroundDrawable(shape(BG,0));int width=Math.min(getResources().getDisplayMetrics().widthPixels-dp(32),dp(BuildConfig.TV?760:600));int height=Math.min(getResources().getDisplayMetrics().heightPixels-dp(64),dp(620));dialog.getWindow().setLayout(width,height);dialog.getWindow().addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams attrs=dialog.getWindow().getAttributes();attrs.dimAmount=.72f;dialog.getWindow().setAttributes(attrs);}
        if(BuildConfig.TV)play.requestFocus();
    }
    void toggleFavorite(Catalog.Item item){Set<String> ids=favorites();boolean added=ids.add(item.id);if(!added)ids.remove(item.id);prefs.edit().putStringSet("favorites",ids).putString("saved:"+item.id,item.raw.toString()).apply();message(added?"Added to watchlist":"Removed from watchlist");render();}
    void watch(Catalog.Item item){if(item.type.equals("manga")){chapters(item,0);return;}if(item.type.equals("series")){seasons(item);return;}if(item.type.equals("live")){status.setText("Finding event streams…");io.execute(()->{try{JSONArray rows=ContentApi.liveStreams(item);ui.post(()->{if(!isDestroyed()){status.setText("Today's sports");chooseStreams(item,rows,item.id);}});}catch(Exception e){ui.post(()->message("Live source is currently unavailable"));}});return;}
        JSONArray streams=item.streams();if(item.id.matches("tmdb-movie-[0-9]+"))try{streams=ContentApi.movieSources(item.id.substring("tmdb-movie-".length()),"movie",1,1);}catch(Exception ignored){}chooseStreams(item,streams,item.id);}
    void seasons(Catalog.Item item){JSONArray local=item.episodes();if(local!=null&&local.length()>0){episodeList(item,local);return;}if(!item.id.matches("tmdb-series-[0-9]+")){message("No episodes configured for this series");return;}String id=item.id.substring("tmdb-series-".length());status.setText("Loading seasons…");io.execute(()->{try{JSONObject show=(JSONObject)ContentApi.json(SERIES+id+".json");JSONArray episodes=show.getJSONArray("episodes");ui.post(()->{if(!isDestroyed()){status.setText("Catalog updated");episodeList(item,episodes);}});}catch(Exception e){ui.post(()->{if(!isDestroyed()){status.setText("Catalog updated");try{chooseStreams(item,ContentApi.movieSources(id,"tv",1,1),item.id+":s1e1");message("Opening VidStuck’s episode selector");}catch(JSONException ignored){message("Episode catalog is not available yet");}}});}});}
    void episodeList(Catalog.Item item,JSONArray episodes){TreeSet<Integer> numbers=new TreeSet<>();for(int i=0;i<episodes.length();i++){JSONObject ep=episodes.optJSONObject(i);if(ep!=null)numbers.add(ep.optInt("season",1));}if(numbers.isEmpty()){message("No episodes available");return;}Integer[] seasons=numbers.toArray(new Integer[0]);String[] labels=new String[seasons.length];for(int i=0;i<labels.length;i++)labels[i]=seasons[i]==0?"Specials":"Season "+seasons[i];new AlertDialog.Builder(this).setTitle(item.title).setItems(labels,(d,index)->{List<JSONObject> selected=new ArrayList<>();for(int i=0;i<episodes.length();i++){JSONObject ep=episodes.optJSONObject(i);if(ep!=null&&ep.optInt("season",1)==seasons[index])selected.add(ep);}String[] titles=new String[selected.size()];for(int i=0;i<titles.length;i++)titles[i]="Episode "+selected.get(i).optInt("episode",i+1)+" · "+selected.get(i).optString("title","Episode");new AlertDialog.Builder(this).setTitle(labels[index]).setItems(titles,(dialog,n)->{JSONObject ep=selected.get(n);JSONArray sources=ep.optJSONArray("streams");if(item.id.matches("tmdb-series-[0-9]+"))try{sources=ContentApi.movieSources(item.id.substring("tmdb-series-".length()),"tv",ep.optInt("season",1),ep.optInt("episode",1));}catch(Exception ignored){}chooseStreams(item,sources,item.id+":"+ep.optString("id"));}).setNegativeButton("Close",null).show();}).setNegativeButton("Close",null).show();}
    void chapters(Catalog.Item item,int offset){status.setText("Loading English chapters…");io.execute(()->{try{JSONArray data=ContentApi.chapters(item.raw.getString("mangaId"),offset);List<JSONObject> rows=new ArrayList<>();for(int i=0;i<data.length();i++){JSONObject chapter=data.getJSONObject(i);String external=chapter.getJSONObject("attributes").optString("externalUrl");if(external.isEmpty()||external.startsWith("https://"))rows.add(chapter);}ui.post(()->{if(isDestroyed())return;status.setText("MangaDex · English chapters");if(rows.isEmpty()){message("No readable English chapters in this page");return;}String[] labels=new String[rows.size()];for(int i=0;i<labels.length;i++){JSONObject a=rows.get(i).optJSONObject("attributes");labels[i]="Chapter "+a.optString("chapter","Special")+" · "+a.optString("title","")+(a.optString("externalUrl").isEmpty()?"":" · Publisher reader");}AlertDialog.Builder dialog=new AlertDialog.Builder(this).setTitle(item.title).setItems(labels,(d,n)->{JSONObject chapter=rows.get(n);String external=chapter.optJSONObject("attributes").optString("externalUrl");if(external.isEmpty())startActivity(new Intent(this,MangaReaderActivity.class).putExtra("chapter",chapter.optString("id")).putExtra("parent",item.id));else startActivity(new Intent(this,BrowserPlayerActivity.class).putExtra("url",external).putExtra("reader",true).putExtra("title",item.title));}).setNegativeButton("Close",null);if(data.length()==100)dialog.setNeutralButton("Older chapters",(d,n)->chapters(item,offset+100));dialog.show();});}catch(Exception e){ui.post(()->{if(!isDestroyed()){status.setText("MangaDex");message("Chapter service unavailable");}});}});}
    void chooseStreams(Catalog.Item item,JSONArray sources,String key){
        if(sources==null||sources.length()==0){message("No playback sources available right now");return;}
        if(sources.length()==1){openStream(item,sources.optJSONObject(0),key);return;}
        String[] labels=new String[sources.length()];for(int i=0;i<labels.length;i++)labels[i]=sources.optJSONObject(i)==null?"Unavailable":sources.optJSONObject(i).optString("label","Stream "+(i+1));
        new AlertDialog.Builder(this).setTitle("Choose live stream").setItems(labels,(d,n)->openStream(item,sources.optJSONObject(n),key)).setNegativeButton("Cancel",null).show();
    }
    void openStream(Catalog.Item item,JSONObject source,String key){
        if(source==null)return;try{URL u=new URL(source.optString("url"));if(!u.getProtocol().equals("https"))throw new Exception();}catch(Exception e){message("Invalid playback source");return;}
        prefs.edit().putString("saved:"+item.id,item.raw.toString()).apply();
        if(source.optBoolean("embed")){prefs.edit().putLong("position:"+item.id,1).apply();startActivity(new Intent(this,BrowserPlayerActivity.class).putExtra("url",source.optString("url")).putExtra("title",item.title));}
        else startActivity(new Intent(this,PlayerActivity.class).putExtra("stream",source.toString()).putExtra("title",item.title).putExtra("key",key).putExtra("parent",item.id).putExtra("live",item.type.equals("live")));
    }
    void libraryMenu(){new AlertDialog.Builder(this).setTitle("Your library").setItems(new String[]{"Watchlist","Continue watching","Collections"},(d,n)->{category=new String[]{"Watchlist","Continue","Collections"}[n];collection="";++loadVersion;catalog=new ArrayList<>(browse);for(Map.Entry<String,?> e:prefs.getAll().entrySet())if(e.getKey().startsWith("saved:")&&e.getValue() instanceof String)try{Catalog.Item item=new Catalog.Item(new JSONObject((String)e.getValue()));boolean exists=false;for(Catalog.Item old:catalog)if(old.id.equals(item.id))exists=true;if(!exists)catalog.add(item);}catch(Exception ignored){}render();}).show();}
    void collections(){TextView title=text("Collections",28,INK);bold(title);content.addView(title);space(content,16);content.addView(button("Create collection",()->createCollection(null)));space(content,16);for(String name:new TreeSet<>(savedIds("collections"))){content.addView(button(name,()->{collection=name;render();}));space(content,10);}if(savedIds("collections").isEmpty())content.addView(text("Organize your favorite titles into collections.",15,MUTED));}
    void createCollection(Catalog.Item item){EditText input=new EditText(this);input.setSingleLine(true);input.setHint("Collection name");new AlertDialog.Builder(this).setTitle("Create collection").setView(input).setPositiveButton("Create",(d,n)->{String name=input.getText().toString().trim();if(name.isEmpty()||name.length()>60){message("Use a name between 1 and 60 characters");return;}Set<String> names=savedIds("collections");names.add(name);SharedPreferences.Editor e=prefs.edit().putStringSet("collections",names);if(item!=null){Set<String> ids=savedIds("collection:"+name);ids.add(item.id);e.putStringSet("collection:"+name,ids).putString("saved:"+item.id,item.raw.toString());}e.apply();render();}).setNegativeButton("Cancel",null).show();}
    void addCollection(Catalog.Item item){String[] names=new TreeSet<>(savedIds("collections")).toArray(new String[0]);new AlertDialog.Builder(this).setTitle("Add to collection").setItems(names,(d,n)->{Set<String> ids=savedIds("collection:"+names[n]);ids.add(item.id);prefs.edit().putStringSet("collection:"+names[n],ids).putString("saved:"+item.id,item.raw.toString()).apply();message("Added to "+names[n]);}).setPositiveButton("New collection",(d,n)->createCollection(item)).setNegativeButton("Cancel",null).show();}
    void settings(){LinearLayout panel=column();panel.setPadding(dp(20),dp(12),dp(20),dp(12));panel.addView(text("TMDB API key (v3) · online title search",14,INK));EditText tmdb=new EditText(this);tmdb.setSingleLine(true);tmdb.setInputType(android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_PASSWORD);tmdb.setText(tmdbKey());panel.addView(tmdb);panel.addView(text("Get your own key at themoviedb.org/settings/api. Leave blank for catalog search.",12,MUTED));space(panel,12);panel.addView(text("Movie catalog URL",14,INK));EditText endpoint=new EditText(this);endpoint.setSingleLine(true);endpoint.setText(prefs.getString("endpoint",FEED));panel.addView(endpoint);space(panel,12);panel.addView(text("Live sports API base URL",14,INK));EditText live=new EditText(this);live.setSingleLine(true);live.setText(prefs.getString("liveEndpoint",ContentApi.LIVE));panel.addView(live);space(panel,12);Switch ads=new Switch(this);ads.setText("Block ads in external video players");ads.setTextColor(INK);ads.setChecked(prefs.getBoolean("blockAds",true));panel.addView(ads);space(panel,12);panel.addView(text("Blank movie URL uses the demo. External player resume positions depend on the provider.\nZeroStreams · "+BuildConfig.VERSION_NAME,13,MUTED));android.webkit.WebView tmdbLogo=new android.webkit.WebView(this);tmdbLogo.setBackgroundColor(Color.TRANSPARENT);tmdbLogo.setFocusable(false);tmdbLogo.getSettings().setAllowFileAccess(false);tmdbLogo.getSettings().setAllowContentAccess(false);try(InputStream logo=getAssets().open("tmdb-logo.svg")){tmdbLogo.loadDataWithBaseURL(null,"<html><head><style>body{margin:0;background:transparent}svg{width:110px;height:18px}</style></head><body>"+Catalog.read(logo,20000)+"</body></html>","text/html","UTF-8",null);}catch(IOException ignored){}panel.addView(tmdbLogo,new LinearLayout.LayoutParams(dp(120),dp(22)));space(panel,8);panel.addView(text("This product uses the TMDB API but is not endorsed or certified by TMDB.",12,MUTED));ScrollView settingsScroll=new ScrollView(this);settingsScroll.addView(panel);new AlertDialog.Builder(this).setTitle("Settings").setView(settingsScroll).setPositiveButton("Save & refresh",(d,n)->{String a=endpoint.getText().toString().trim(),b=live.getText().toString().trim();try{if(!a.isEmpty()&&!new URL(a).getProtocol().equals("https"))throw new Exception();if(!new URL(b).getProtocol().equals("https"))throw new Exception();}catch(Exception e){message("Use HTTPS URLs");return;}prefs.edit().putString("endpoint",a).putString("liveEndpoint",b.replaceAll("/+$","")).putBoolean("blockAds",ads.isChecked()).putString("tmdbKey",tmdb.getText().toString().trim()).apply();searchPage=1;load();}).setNeutralButton("Refresh",(d,n)->load()).setNegativeButton("Close",null).show();}
    @Override protected void onDestroy(){++searchVersion;++loadVersion;++renderVersion;ui.removeCallbacksAndMessages(null);io.shutdownNow();pictures.evictAll();super.onDestroy();}
}
