package com.zerostreams.app;
import android.content.*;import android.security.keystore.*;import android.util.Base64;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import java.security.KeyStore;import java.net.*;import java.io.*;import java.util.*;import org.json.*;
/** Download-only API client. No streaming-source or trailer code depends on this class. */
final class RawCast {
 private final Context context;private final SharedPreferences prefs;private final Map<String,JSONObject> cache=new HashMap<>();private final Map<String,Long> expiry=new HashMap<>();volatile JSONObject usage;private static RawCast instance;
 static synchronized RawCast get(Context c){if(instance==null)instance=new RawCast(c.getApplicationContext());return instance;}private RawCast(Context c){context=c;prefs=c.getSharedPreferences("rawcast-secure",Context.MODE_PRIVATE);try{usage=new JSONObject(prefs.getString("usage","{}"));}catch(Exception e){usage=new JSONObject();}}
 private SecretKey secret()throws Exception{KeyStore store=KeyStore.getInstance("AndroidKeyStore");store.load(null);String alias="zeroplay.rawcast";if(!store.containsAlias(alias)){KeyGenerator generator=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");generator.init(new KeyGenParameterSpec.Builder(alias,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());generator.generateKey();}return (SecretKey)store.getKey(alias,null);}
 synchronized void save(String value)throws Exception{if(!value.matches("rc_live_[A-Za-z0-9_-]{20,200}"))throw new IOException("Enter a valid RawCast API key.");Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.ENCRYPT_MODE,secret());prefs.edit().putString("key",Base64.encodeToString(cipher.doFinal(value.getBytes("UTF-8")),Base64.NO_WRAP)).putString("iv",Base64.encodeToString(cipher.getIV(),Base64.NO_WRAP)).remove("usage").apply();cache.clear();usage=new JSONObject();}
 synchronized String key(){try{String value=prefs.getString("key","");if(!value.isEmpty()){Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,secret(),new GCMParameterSpec(128,Base64.decode(prefs.getString("iv",""),Base64.NO_WRAP)));return new String(cipher.doFinal(Base64.decode(value,Base64.NO_WRAP)),"UTF-8");}}catch(Exception ignored){}return BuildConfig.DEBUG?System.getenv("RAWCAST_API_KEY"):null;}
 boolean hasKey(){String key=key();return key!=null&&!key.isEmpty();}boolean saved(){return prefs.contains("key");}synchronized void remove(){prefs.edit().remove("key").remove("iv").remove("usage").apply();cache.clear();usage=new JSONObject();}
 JSONObject request(String route)throws Exception{String key=key();if(key==null||key.isEmpty())throw new IOException("RawCast API key required. Add your own key in Settings → RawCast API.");HttpURLConnection connection=(HttpURLConnection)new URL("https://api.rawcast.space/v1"+route).openConnection();connection.setConnectTimeout(15000);connection.setReadTimeout(30000);connection.setInstanceFollowRedirects(false);connection.setRequestProperty("X-API-Key",key);connection.setRequestProperty("Accept","application/json");try{int code=connection.getResponseCode();String limit=connection.getHeaderField("X-RateLimit-Limit"),remaining=connection.getHeaderField("X-RateLimit-Remaining");if(limit!=null&&remaining!=null)try{JSONObject value=new JSONObject().put("limit",Long.parseLong(limit)).put("remaining",Long.parseLong(remaining)).put("used",Math.max(0,Long.parseLong(limit)-Long.parseLong(remaining)));String reset=connection.getHeaderField("X-RateLimit-Reset");if(reset!=null)value.put("reset",Long.parseLong(reset)*1000);usage=value;prefs.edit().putString("usage",value.toString()).apply();}catch(Exception ignored){}if(code!=200)throw new IOException(code==401?"RawCast API key rejected.":code==403?"RawCast key unavailable; check account verification.":code==404?"Unavailable for Download.":code==429?"RawCast rate or monthly quota limit reached.":"RawCast request failed. Try again later.");try(InputStream input=connection.getInputStream()){return new JSONObject(Catalog.read(input,2_000_000));}}finally{connection.disconnect();}}
 synchronized JSONObject resolve(String type,String id,int season,int episode,boolean fresh)throws Exception{if(!id.matches("[1-9][0-9]*")||!Arrays.asList("movie","tv").contains(type)||season<0||episode<1)throw new IOException("Select a valid title and episode.");String identity=type+":"+id+":"+season+":"+episode;if(!fresh&&(expiry.containsKey(identity)?expiry.get(identity):0L)>System.currentTimeMillis())return cache.get(identity);JSONObject value=request("/download/"+type+"/"+id+(type.equals("tv")?"/"+season+"/"+episode:"")+"?quality=1080p&redirect=false");String address=value.optString("downloadUrl",value.optString("url"));URI uri=new URI(address);if(!value.optString("format").equals("mp4")||!"https".equals(uri.getScheme())||uri.getUserInfo()!=null||address.contains(".m3u8"))throw new IOException("Unavailable for Download.");value=new JSONObject().put("url",address);cache.put(identity,value);expiry.put(identity,System.currentTimeMillis()+120000);return value;}
 void test()throws Exception{request("/meta/movie/550?lang=en-US");}void refreshUsage()throws Exception{request("/meta/movie/550?lang=en-US");}
}
