package com.zerostreams.app;
import android.content.Context;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;
final class SportsStore {
 static final String PRIMARY="https://api.ppv.st";
 static JSONObject fetch(String url)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(8000);c.setReadTimeout(8000);c.setUseCaches(false);c.setRequestProperty("Cache-Control","no-cache");try{if(c.getResponseCode()!=200)throw new IOException("Live Sports API unavailable");ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=c.getInputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>8000000)throw new IOException("Catalogue too large");}}return new JSONObject(out.toString("UTF-8"));}finally{c.disconnect();}}
 static synchronized JSONObject get(Context context,boolean force)throws Exception{File file=new File(context.getCacheDir(),"sports-catalogue.json");JSONObject cache=null;try{cache=new JSONObject(read(file));if(!force&&System.currentTimeMillis()-cache.optLong("updated")<60000)return cache;}catch(Exception ignored){}List<String> bases=new ArrayList<>();bases.add(PRIMARY);if(cache!=null){String previous=cache.optString("base");if(previous.matches("(?i)https://api\\.[a-z0-9.-]+")&&!previous.equals(PRIMARY))bases.add(previous);}
 for(int index=0;index<bases.size();index++){String base=bases.get(index);try{JSONObject data=fetch(base+"/api/streams");if(!data.optBoolean("success")||data.optJSONArray("streams")==null)throw new IOException("Invalid Live Sports catalogue");data.put("updated",System.currentTimeMillis()).put("base",base).put("stale",false);File tmp=new File(file.getPath()+".tmp");try(FileOutputStream out=new FileOutputStream(tmp)){out.write(data.toString().getBytes("UTF-8"));}if(!tmp.renameTo(file))throw new IOException("Cannot cache catalogue");return data;}catch(Exception ignored){if(base.equals(PRIMARY)){try{JSONObject ping=fetch(PRIMARY+"/api/ping");JSONArray domains=ping.optJSONArray("domains");if(ping.optBoolean("success")&&domains!=null)for(int i=0;i<domains.length();i++){String d=domains.optString(i);if(d.matches("(?i)(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z]{2,}")){String mirror="https://api."+d;if(!bases.contains(mirror))bases.add(mirror);}}}catch(Exception discoveryFailure){}}}}if(cache!=null)return cache.put("stale",true);throw new IOException("Live Sports unavailable · Retry");}
 static String read(File file)throws IOException{try(InputStream in=new FileInputStream(file);ByteArrayOutputStream out=new ByteArrayOutputStream()){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toString("UTF-8");}}
 static JSONArray sources(JSONObject event){JSONArray result=new JSONArray();if(!event.optString("iframe").trim().isEmpty())result.put(event);JSONArray subs=event.optJSONArray("substreams");if(subs!=null)for(int i=0;i<subs.length();i++){JSONObject source=subs.optJSONObject(i);if(source!=null&&!source.optString("iframe").trim().isEmpty())result.put(source);}return result;}
}
