package com.zerostreams.app;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.*;
/** API embeds run unchanged: no request interception, ad guard, QR scanning or player injection. */
public class SportsPlayerActivity extends Activity {
 private WebView web;private FrameLayout screen;private LinearLayout layout;private TextView status;private View custom;private WebChromeClient.CustomViewCallback customCallback;private TvMouse mouse;private JSONArray sources;private int selected;private boolean destroyed;
 @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);screen=new FrameLayout(this);screen.setBackgroundColor(Color.BLACK);layout=new LinearLayout(this);layout.setOrientation(LinearLayout.VERTICAL);LinearLayout tools=new LinearLayout(this);Button back=new Button(this);back.setText("Back");back.setOnClickListener(v->onBackPressed());tools.addView(back);Button retry=new Button(this);retry.setText("Retry");retry.setOnClickListener(v->load());tools.addView(retry);Button full=new Button(this);full.setText("Fullscreen");full.setOnClickListener(v->{tools.setVisibility(View.GONE);getWindow().getDecorView().setSystemUiVisibility(5894);web.requestFocus();});tools.addView(full);Spinner picker=new Spinner(this);tools.addView(picker,new LinearLayout.LayoutParams(0,-2,1));layout.addView(tools);status=new TextView(this);status.setTextColor(Color.WHITE);status.setPadding(16,8,16,8);layout.addView(status);web=new WebView(this);web.setBackgroundColor(Color.BLACK);web.setFocusable(true);WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setMediaPlaybackRequiresUserGesture(false);settings.setSupportMultipleWindows(true);settings.setJavaScriptCanOpenWindowsAutomatically(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
 web.setWebViewClient(new WebViewClient(){@Override public void onPageStarted(WebView w,String url,android.graphics.Bitmap icon){status.setText("Loading player…");}@Override public void onPageFinished(WebView w,String url){status.setText("Player loaded · "+label());}@Override public void onReceivedError(WebView w,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame())status.setText("Player unavailable · Retry or choose another source");}@Override public void onReceivedHttpError(WebView w,WebResourceRequest r,WebResourceResponse e){if(r.isForMainFrame())status.setText("Player unavailable · HTTP "+e.getStatusCode()+" · Retry");}});
 web.setWebChromeClient(new WebChromeClient(){@Override public void onShowCustomView(View view,CustomViewCallback callback){if(custom!=null){callback.onCustomViewHidden();return;}custom=view;customCallback=callback;layout.setVisibility(View.GONE);screen.addView(view,new FrameLayout.LayoutParams(-1,-1));getWindow().getDecorView().setSystemUiVisibility(5894);}@Override public void onHideCustomView(){hideCustom();}@Override public boolean onCreateWindow(WebView parent,boolean dialog,boolean gesture,Message message){WebView popup=new WebView(SportsPlayerActivity.this);popup.getSettings().setJavaScriptEnabled(true);popup.getSettings().setDomStorageEnabled(true);CookieManager.getInstance().setAcceptThirdPartyCookies(popup,true);Dialog window=new Dialog(SportsPlayerActivity.this);window.setContentView(popup);window.setOnDismissListener(d->{popup.stopLoading();popup.destroy();});popup.setWebChromeClient(new WebChromeClient(){@Override public void onCloseWindow(WebView w){window.dismiss();}});popup.setWebViewClient(new WebViewClient());window.show();window.getWindow().setLayout(-1,-1);WebView.WebViewTransport transport=(WebView.WebViewTransport)message.obj;transport.setWebView(popup);message.sendToTarget();return true;}});
 layout.addView(web,new LinearLayout.LayoutParams(-1,0,1));screen.addView(layout);if(BuildConfig.TV)mouse=new TvMouse(this,web,screen,()->{});setContentView(screen);try{sources=new JSONArray(getIntent().getStringExtra("sources"));if(sources.length()==0)throw new Exception();String[] labels=new String[sources.length()];for(int i=0;i<labels.length;i++){JSONObject s=sources.getJSONObject(i);labels[i]=s.optString("source_tag",s.optString("tag","Source "+(i+1)));}picker.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));selected=saved==null?0:saved.getInt("source",0);picker.setSelection(Math.min(selected,labels.length-1));picker.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int index,long id){selected=index;load();}});}catch(Exception e){status.setText("Player unavailable · go Back and refresh");}web.requestFocus();if(BuildConfig.TV)Toast.makeText(this,"Arrows move pointer · OK selects · Menu switches pointer/focus · Back exits fullscreen first",Toast.LENGTH_LONG).show();}
 String label(){JSONObject s=sources==null?null:sources.optJSONObject(selected);return s==null?"":s.optString("source_tag",s.optString("tag","Source "+(selected+1)));}
 void load(){if(destroyed||sources==null)return;hideCustom();String value=sources.optJSONObject(selected).optString("iframe").trim();status.setText("Loading player…");web.stopLoading();if(value.startsWith("<"))web.loadDataWithBaseURL(getIntent().getStringExtra("base"),"<!doctype html><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><style>html,body{margin:0;height:100%;background:black}iframe{width:100%;height:100%;border:0}</style>"+value,"text/html","UTF-8",null);else if(value.matches("(?i)^https?://.*"))web.loadUrl(value);else status.setText("Invalid embedded player · choose another source");}
 void hideCustom(){if(custom!=null){screen.removeView(custom);custom=null;layout.setVisibility(View.VISIBLE);WebChromeClient.CustomViewCallback callback=customCallback;customCallback=null;if(callback!=null)callback.onCustomViewHidden();getWindow().getDecorView().setSystemUiVisibility(0);}}
 @Override public void onBackPressed(){if(custom!=null){hideCustom();return;}if(layout.getChildAt(0).getVisibility()!=View.VISIBLE){layout.getChildAt(0).setVisibility(View.VISIBLE);getWindow().getDecorView().setSystemUiVisibility(0);return;}if(web.canGoBack()){web.goBack();return;}finish();}
 @Override public boolean dispatchKeyEvent(KeyEvent event){if(event.getKeyCode()==KeyEvent.KEYCODE_BACK){if(event.getAction()==KeyEvent.ACTION_UP)onBackPressed();return true;}if(mouse!=null&&custom==null&&web.hasFocus()&&mouse.handle(event))return true;return super.dispatchKeyEvent(event);}
 @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putInt("source",selected);}
 @Override protected void onPause(){if(mouse!=null)mouse.stop();web.onPause();super.onPause();}@Override protected void onResume(){super.onResume();if(web!=null)web.onResume();}@Override protected void onDestroy(){destroyed=true;hideCustom();if(mouse!=null)mouse.stop();web.stopLoading();web.destroy();super.onDestroy();}
}
