package com.zerostreams.app;
import android.app.*;import android.content.*;import android.os.*;import org.json.*;
public final class TorrentDownloadService extends Service {
 private final Handler handler=new Handler(Looper.getMainLooper());
 void poll(){DirectDownloads manager=DirectDownloads.get(this);if(!manager.hasWork()){stopSelf();return;}getSystemService(NotificationManager.class).notify(1701,notification());handler.postDelayed(this::poll,1000);}
 PendingIntent action(String name,int id){return PendingIntent.getService(this,id,new Intent(this,TorrentDownloadService.class).setAction(name),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 Notification notification(){String channel="zeroplay-torrents";if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager.class).createNotificationChannel(new NotificationChannel(channel,"ZeroPlay downloads",NotificationManager.IMPORTANCE_LOW));PendingIntent open=PendingIntent.getActivity(this,0,new Intent(this,MainActivity.class).putExtra("downloads",true),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification.Builder b=Build.VERSION.SDK_INT>=26?new Notification.Builder(this,channel):new Notification.Builder(this);long bytes=0,total=0,speed=0;JSONArray jobs=DirectDownloads.get(this).list();for(int i=0;i<jobs.length();i++){JSONObject j=jobs.optJSONObject(i);if(j.optString("state").equals("downloading")){bytes+=j.optLong("bytes");total+=j.optLong("total");speed+=j.optLong("speed");}}return b.setSmallIcon(android.R.drawable.stat_sys_download).setContentTitle("ZeroPlay downloads").setContentText(DirectDownloads.get(this).canTransfer()?speed/1024+" KB/s · Open Downloads":"Waiting for permitted network").setProgress(100,total>0?(int)(100*bytes/total):0,total==0).setContentIntent(open).setOngoing(true).addAction(android.R.drawable.ic_media_pause,"Pause",action("pause",1)).addAction(android.R.drawable.ic_menu_close_clear_cancel,"Cancel",action("cancel",2)).build();}
 @Override public int onStartCommand(Intent intent,int flags,int id){DirectDownloads manager=DirectDownloads.get(this);String action=intent==null?"":intent.getAction();if("pause".equals(action)||"cancel".equals(action)){JSONArray jobs=manager.list();for(int i=0;i<jobs.length();i++){JSONObject j=jobs.optJSONObject(i);if(java.util.Arrays.asList("queued","preparing","downloading").contains(j.optString("state")))try{manager.action(j.optString("id"),action);}catch(Exception ignored){}}stopSelf();return START_NOT_STICKY;}startForeground(1701,notification());manager.pump();handler.removeCallbacksAndMessages(null);handler.postDelayed(this::poll,1000);return START_NOT_STICKY;}
 @Override public IBinder onBind(Intent intent){return null;}
 @Override public void onDestroy(){handler.removeCallbacksAndMessages(null);super.onDestroy();}
 @Override public void onTimeout(int startId,int type){DirectDownloads.get(this).pauseAll();stopSelf();}
}
