package com.zerostreams.app;
import android.content.Context;
import android.net.Uri;
import android.os.Build;
import org.json.*;
import org.libtorrent4j.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;
/** Native torrents in app-private storage; only the largest playable non-sample file is selected. */
final class TorrentDownloads {
 private static TorrentDownloads instance;
 static synchronized TorrentDownloads get(Context c){if(instance==null)instance=new TorrentDownloads(c.getApplicationContext());return instance;}
 private final Context context;private final File root,index;private final List<JSONObject> rows=new ArrayList<>();private SessionManager session;
 private final Map<String,TorrentHandle> handles=new HashMap<>();private final Map<String,Long> pending=new HashMap<>();
 private final ScheduledExecutorService worker=Executors.newSingleThreadScheduledExecutor();
 private TorrentDownloads(Context c){context=c;root=new File(c.getFilesDir(),"torrent-downloads");root.mkdirs();index=new File(root,"index.json");try(FileInputStream input=new FileInputStream(index)){JSONArray data=new JSONArray(Catalog.read(input,1000000));for(int i=0;i<data.length();i++){JSONObject r=data.getJSONObject(i);if(!r.optString("id").matches("[a-f0-9]{40}"))continue;if(!r.optString("status").equals("completed"))r.put("status","paused");rows.add(r);}}catch(Exception ignored){}worker.scheduleAtFixedRate(this::tick,1,1,TimeUnit.SECONDS);}
 static String magnet(String value){if(value==null||value.length()>16000)throw new IllegalArgumentException("Enter a magnet link");Uri u=Uri.parse("https://magnet.invalid/"+value.trim().substring(value.trim().indexOf(':')+1));String xt=u.getQueryParameter("xt");if(!value.trim().toLowerCase(Locale.ROOT).startsWith("magnet:?")||xt==null||!xt.matches("(?i)urn:btih:[a-f0-9]{40}"))throw new IllegalArgumentException("Paste a magnet link with a 40-character torrent hash");Uri.Builder b=new Uri.Builder().scheme("magnet");for(String name:Arrays.asList("xt","dn","tr"))for(String v:u.getQueryParameters(name))b.appendQueryParameter(name,v);return b.build().toString();}
 synchronized List<JSONObject> list(){List<JSONObject> out=new ArrayList<>();for(JSONObject r:rows)try{out.add(new JSONObject(r.toString()));}catch(JSONException ignored){}return out;}
 synchronized void persist(){try{File temp=new File(root,"index.tmp");try(FileOutputStream out=new FileOutputStream(temp)){out.write(new JSONArray(rows).toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));}if(!temp.renameTo(index))throw new IOException();}catch(Exception ignored){}}
 void add(String title,String value){String url=magnet(value);String id=Uri.parse("https://magnet.invalid/"+url.substring(url.indexOf(':')+1)).getQueryParameter("xt").substring(9).toLowerCase(Locale.ROOT);worker.execute(()->{synchronized(this){JSONObject r=find(id);try{if(r==null){r=new JSONObject().put("id",id).put("title",title==null||title.trim().isEmpty()?"Torrent movie":title.substring(0,Math.min(300,title.length()))).put("magnet",url).put("status","queued").put("bytes",0).put("total",0);rows.add(0,r);}resume(r);}catch(Throwable e){failed(r,"Torrent could not start. Check available storage and try again.");}persist();}});}
 private JSONObject find(String id){for(JSONObject r:rows)if(r.optString("id").equals(id))return r;return null;}
 private void startSession(){if(session!=null)return;if(Build.VERSION.SDK_INT<24)throw new IllegalStateException("Torrent downloads require Android 7 or later");session=new SessionManager();session.start();}
 private void resume(JSONObject r)throws Exception{if(r.optString("status").equals("completed"))return;startSession();String id=r.getString("id");TorrentHandle h=handles.get(id);if(h==null){File folder=new File(root,id);folder.mkdirs();r.remove("fileIndex");session.download(r.getString("magnet"),folder,TorrentFlags.DEFAULT_DONT_DOWNLOAD);pending.put(id,System.currentTimeMillis());}else{h.unsetFlags(TorrentFlags.AUTO_MANAGED);h.resume();}r.put("status","metadata").put("error","");TorrentDownloadService.ensure(context);}
 private void failed(JSONObject r,String error){if(r!=null)try{r.put("status","failed").put("error",error);}catch(JSONException ignored){}}
 private void tick(){synchronized(this){boolean dirty=false;for(JSONObject r:rows){String id=r.optString("id"),state=r.optString("status");if(!state.equals("metadata")&&!state.equals("downloading"))continue;try{TorrentHandle h=handles.get(id);if(h==null){if(session==null)continue;h=session.find(Sha1Hash.parseHex(id));if(h==null){if(System.currentTimeMillis()-pending.getOrDefault(id,System.currentTimeMillis())>180000)failed(r,"No metadata received. Check peers and resume.");continue;}handles.put(id,h);}TorrentStatus status=h.status(true);r.put("peers",status.numPeers()).put("speed",status.downloadRate());if(!status.hasMetadata())continue;TorrentInfo info=h.torrentFile();if(info==null)continue;FileStorage files=info.files();int selected=r.optInt("fileIndex",-1);if(selected<0){long largest=0;for(int i=0;i<files.numFiles();i++){String name=files.filePath(i).toLowerCase(Locale.ROOT);File f=new File(root,id+"/"+files.filePath(i));if(!f.getCanonicalPath().startsWith(new File(root,id).getCanonicalPath()+File.separator))throw new IOException("Invalid torrent path");if(name.matches(".*\\.(mp4|m4v|webm|mkv)$")&&!name.contains("sample")&&files.fileSize(i)>largest){selected=i;largest=files.fileSize(i);}}if(selected<0)throw new IOException("Torrent contains no playable movie file");if(largest>50L*1024*1024*1024)throw new IOException("Movie exceeds 50 GB");Priority[] priorities=Priority.array(Priority.IGNORE,files.numFiles());priorities[selected]=Priority.DEFAULT;h.prioritizeFiles(priorities);h.unsetFlags(TorrentFlags.AUTO_MANAGED);h.resume();r.put("fileIndex",selected).put("file",files.filePath(selected)).put("total",largest);}
 long[] progress=h.fileProgress();long downloaded=selected<progress.length?progress[selected]:0;r.put("bytes",downloaded).put("status","downloading");if(downloaded>=r.optLong("total")&&r.optLong("total")>0){h.pause();session.remove(h);handles.remove(id);pending.remove(id);r.put("status","completed").put("speed",0);}dirty=true;
 }catch(Throwable e){TorrentHandle h=handles.remove(id);if(h!=null&&session!=null)session.remove(h);failed(r,e instanceof IOException?e.getMessage():"Torrent engine unavailable or storage full. Resume to retry.");dirty=true;}}if(dirty)persist();}}
 void action(String id,String action){worker.execute(()->{synchronized(this){JSONObject r=find(id);if(r==null)return;try{TorrentHandle h=handles.get(id);if(action.equals("pause")){if(h!=null){h.unsetFlags(TorrentFlags.AUTO_MANAGED);h.pause();}r.put("status","paused");}else if(action.equals("resume"))resume(r);else if(action.equals("remove")){if(h!=null){session.remove(h);handles.remove(id);}pending.remove(id);rows.remove(r);delete(new File(root,id));}}catch(Throwable e){failed(r,"Torrent engine unavailable. Resume to retry.");}persist();}});}
 synchronized boolean active(){for(JSONObject r:rows)if(Arrays.asList("downloading","metadata","queued").contains(r.optString("status")))return true;return false;}
 synchronized File playable(String id)throws IOException{JSONObject r=find(id);if(r==null||!r.optString("status").equals("completed"))throw new IOException("Download not ready");File folder=new File(root,id),f=new File(folder,r.optString("file"));if(!f.getCanonicalPath().startsWith(folder.getCanonicalPath()+File.separator)||!f.isFile())throw new IOException("Downloaded file missing");return f;}
 private static void delete(File f){File[] children=f.listFiles();if(children!=null)for(File child:children)delete(child);f.delete();}
 void pauseAll(){for(JSONObject r:list())if(Arrays.asList("downloading","metadata","queued").contains(r.optString("status")))action(r.optString("id"),"pause");}
}
