package com.zerostreams.app;
import android.content.*;import android.security.keystore.*;import android.util.Base64;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import java.security.KeyStore;import java.net.*;import java.io.*;import java.util.*;import org.json.*;
final class TspSearchProvider implements TorrentSearchProvider {
 final SharedPreferences prefs;final Map<String,JSONArray> cache=new HashMap<>();final Map<String,Long> expires=new HashMap<>();static TspSearchProvider instance;static synchronized TspSearchProvider get(Context c){if(instance==null)instance=new TspSearchProvider(c);return instance;}TspSearchProvider(Context c){prefs=c.getSharedPreferences("torrentSearchSettings-secure",0);}
 SecretKey secret()throws Exception{KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias("zeroplay.torrentSearchSettings")){KeyGenerator g=KeyGenerator.getInstance("AES","AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder("zeroplay.torrentSearchSettings",3).setBlockModes("GCM").setEncryptionPaddings("NoPadding").build());g.generateKey();}return (SecretKey)k.getKey("zeroplay.torrentSearchSettings",null);}
 String key(){try{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(2,secret(),new GCMParameterSpec(128,Base64.decode(prefs.getString("iv",""),2)));return new String(c.doFinal(Base64.decode(prefs.getString("key",""),2)),"UTF-8");}catch(Exception e){return "";}}
 static String server(String s)throws Exception{URI u=new URI(s);if(!"https".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null||u.getQuery()!=null||u.getFragment()!=null)throw new IOException("Use a valid HTTPS Torrent Search API URL.");return s.replaceAll("/+$","");}
 void save(String url,String key,boolean enabled,int seeds,int health)throws Exception{url=server(url);SharedPreferences.Editor e=prefs.edit().putString("url",url).putBoolean("enabled",enabled).putInt("seeds",Math.max(1,Math.min(1000,seeds))).putInt("health",Math.max(0,Math.min(100,health)));if(!key.isEmpty()){if(!key.matches("[A-Za-z0-9_.-]{8,512}"))throw new IOException("Check the API key.");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(1,secret());e.putString("key",Base64.encodeToString(c.doFinal(key.getBytes("UTF-8")),2)).putString("iv",Base64.encodeToString(c.getIV(),2));}e.apply();cache.clear();expires.clear();}
 boolean configured(){return prefs.getBoolean("enabled",true)&&!key().isEmpty()&&!prefs.getString("url","https://api.tspsearch.dev").isEmpty();}
 byte[] request(String route)throws Exception{if(!configured())throw new IOException("Set Up Downloads in Settings → Downloads → Torrent Search.");HttpURLConnection c=(HttpURLConnection)new URL(server(prefs.getString("url","https://api.tspsearch.dev"))+"/api/v1/"+route).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(45000);c.setInstanceFollowRedirects(false);c.setRequestProperty("X-Api-Key",key());try{int n=c.getResponseCode();if(n==401||n==403)throw new IOException("Invalid TSP API key.");if(n!=200)throw new IOException("TSP Search unavailable.");try(InputStream in=c.getInputStream();ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int count;while((count=in.read(buf))!=-1){b.write(buf,0,count);if(b.size()>8_000_000)throw new IOException("TSP response too large.");}return b.toByteArray();}}catch(SocketTimeoutException e){throw new IOException("TSP search timed out.");}catch(ConnectException e){throw new IOException("TSP Search unavailable. Check your network.");}finally{c.disconnect();}}
 JSONArray json(String route)throws Exception{return new JSONArray(new String(request(route),"UTF-8"));}
 int test()throws Exception{new JSONObject(new String(request("indexers"),"UTF-8"));HttpURLConnection c=(HttpURLConnection)new URL(server(prefs.getString("url","https://api.tspsearch.dev"))+"/api/v1/health").openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setInstanceFollowRedirects(false);try{if(c.getResponseCode()!=200)throw new IOException("TSP health check unavailable.");}finally{c.disconnect();}return 1;}
 static String norm(String s){return java.text.Normalizer.normalize(s,java.text.Normalizer.Form.NFKD).replaceAll("[^\\p{L}\\p{N}]+"," ").trim().toLowerCase(Locale.ROOT);}
 static JSONArray rank(JSONArray rows,String title,int year,String type,String tmdb,int season,int episode,int minSeeds,int minHealth)throws Exception{Map<String,JSONObject> unique=new HashMap<>();for(int i=0;i<rows.length();i++){JSONObject r=rows.getJSONObject(i);int seeds=r.optInt("seeders",-1),peers=r.optInt("leechers",-1);if(seeds<Math.max(1,minSeeds)||r.optBoolean("suspect")||!r.optString("category","video").equals("video"))continue;if(r.optLong("tmdbId")>0&&!r.optString("tmdbId").equals(tmdb))continue;String name=r.optString("name"),n=norm(name),wanted=norm(title);boolean exact=r.optString("tmdbId").equals(tmdb);if(!exact&&!n.startsWith(wanted+" ")&&!n.equals(wanted))continue;java.util.regex.Matcher y=java.util.regex.Pattern.compile("\\b(19\\d{2}|20\\d{2})\\b").matcher(name);if(type.equals("movie")&&year>0&&(!y.find()||Integer.parseInt(y.group())!=year))continue;java.util.regex.Matcher ep=java.util.regex.Pattern.compile("(?i)\\bS(\\d{1,3})E(\\d{1,3})\\b").matcher(name);boolean hasEpisode=ep.find();if(type.equals("tv")&&(!hasEpisode||Integer.parseInt(ep.group(1))!=season||Integer.parseInt(ep.group(2))!=episode)||type.equals("movie")&&hasEpisode)continue;String magnet=r.optString("magnet"),hash=r.optString("infohash").toLowerCase(Locale.ROOT);if(hash.isEmpty()&&!magnet.isEmpty()){java.util.regex.Matcher m=java.util.regex.Pattern.compile("(?i)urn:btih:([a-f0-9]{40})").matcher(magnet);if(m.find())hash=m.group(1).toLowerCase(Locale.ROOT);}if(!hash.isEmpty()&&!hash.matches("[a-f0-9]{40}"))continue;if(magnet.isEmpty()||!magnet.startsWith("magnet:?")||hash.isEmpty()||!magnet.toLowerCase(Locale.ROOT).contains("urn:btih:"+hash))continue;int points=seeds>50?50:seeds>=26?45:seeds>=11?35:seeds>=6?25:seeds>=3?15:5;int health=Math.min(100,points+(peers<0?0:Math.min(15,5*seeds/Math.max(1,peers)))+(r.optBoolean("measured")?10:0)+(r.optJSONArray("sources")==null?0:Math.min(10,Math.max(0,r.optJSONArray("sources").length()-1)*3))+recent(r.optString("scraped_at"))+5);if(health<minHealth)continue;String id=hash.isEmpty()?Integer.toHexString((n+":"+r.optLong("size_bytes")).hashCode()):hash;r=new JSONObject(r.toString()).put("id",id).put("infoHash",hash).put("title",name).put("healthScore",health).put("resolution",quality(name)).put("codec",codec(name)).put("score",(exact?100:0)+50+health+Math.min(30,seeds));if(!unique.containsKey(id)||unique.get(id).optInt("score")<r.optInt("score"))unique.put(id,r);}List<JSONObject> list=new ArrayList<>(unique.values());list.sort((a,b)->Integer.compare(b.optInt("score"),a.optInt("score")));JSONArray out=new JSONArray();for(int i=0;i<Math.min(10,list.size());i++)out.put(list.get(i));return out;}
 public synchronized JSONArray search(Catalog.Item item,int season,int episode,boolean fresh)throws Exception{String tmdb=item.id.substring(item.id.lastIndexOf('-')+1),type=item.type.equals("series")?"tv":"movie",id=item.id+":"+item.title+":"+item.year+":"+season+":"+episode+":"+prefs.getAll().toString().hashCode();if(!fresh&&expires.getOrDefault(id,0L)>System.currentTimeMillis())return cache.get(id);String extra=type.equals("tv")?String.format(Locale.ROOT," S%02dE%02d",season,episode):item.year>0?" "+item.year:"";String original=item.raw.optString("originalTitle",item.raw.optString("original_title",item.title));JSONArray rows=new JSONArray(),out=new JSONArray();LinkedHashSet<String> queries=new LinkedHashSet<>();queries.add(item.title+extra);if(!original.equals(item.title))queries.add(original+extra);if(type.equals("movie"))queries.add(item.title);for(String query:queries){String route="search?cat=video&limit=50&min_seeders="+prefs.getInt("seeds",3)+"&suspect=drop&q="+URLEncoder.encode(query,"UTF-8");JSONObject response=new JSONObject(new String(request(route),"UTF-8"));JSONArray result=response.getJSONArray("torrents");for(int i=0;i<result.length();i++)rows.put(result.get(i));out=rank(rows,item.title,item.year,type,tmdb,season,episode,prefs.getInt("seeds",3),prefs.getInt("health",60));if(out.length()>=10)break;}if(!original.equals(item.title)){JSONArray alt=rank(rows,original,item.year,type,tmdb,season,episode,prefs.getInt("seeds",3),prefs.getInt("health",60));Set<String> hashes=new HashSet<>();for(int i=0;i<out.length();i++)hashes.add(out.getJSONObject(i).optString("id"));for(int i=0;i<alt.length()&&out.length()<10;i++)if(hashes.add(alt.getJSONObject(i).optString("id")))out.put(alt.getJSONObject(i));}List<JSONObject> ordered=new ArrayList<>();for(int i=0;i<out.length();i++){JSONObject r=out.getJSONObject(i);r.put("score",r.optInt("score")+(r.optString("resolution").equals(prefs.getString("quality","Auto"))?15:0)+(r.optString("codec").equals(prefs.getString("codec","Auto"))?10:0));ordered.add(r);}ordered.sort((a,b)->Integer.compare(b.optInt("score"),a.optInt("score")));out=new JSONArray(ordered);cache.put(id,out);expires.put(id,System.currentTimeMillis()+300000);return out;}
 static int recent(String value){try{long age=System.currentTimeMillis()-new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssX",Locale.ROOT).parse(value.replaceAll("\\.\\d+Z$","Z")).getTime();return age>=0&&age<7L*86400000?10:0;}catch(Exception e){return 0;}}
 static String quality(String n){return n.matches("(?i).*\\b(2160p|4k|uhd)\\b.*")?"2160p":n.matches("(?i).*\\b(1080p|fhd)\\b.*")?"1080p":n.matches("(?i).*\\b(720p|hd)\\b.*")?"720p":n.matches("(?i).*\\b480p\\b.*")?"480p":"Unknown";}
 static String codec(String n){return n.matches("(?i).*\\b(x265|h[ .]?265|hevc)\\b.*")?"HEVC":n.matches("(?i).*\\b(x264|h[ .]?264|avc)\\b.*")?"H264":n.matches("(?i).*\\bav1\\b.*")?"AV1":"Unknown";}
}
