from pathlib import Path
import re

def read(p): return Path(p).read_text(encoding='utf-8')
def write(p,s): Path(p).write_text(s,encoding='utf-8')
def rep(s,a,b,label):
    n=s.count(a)
    if n!=1: raise RuntimeError(f'{label}: expected one match, got {n}')
    return s.replace(a,b,1)
def sub(s,pat,repl,label):
    out,n=re.subn(pat,repl,s,count=1,flags=re.S)
    if n!=1: raise RuntimeError(f'{label}: expected one regex match, got {n}')
    return out

# Persist richer metadata for new Android downloads.
p='app/src/main/java/com/zerostreams/app/DirectDownloads.java'; s=read(p)
old='JSONObject j=new JSONObject().put("id",id).put("title",item.title).put("tmdb",item.id.substring(item.id.lastIndexOf(\'-\')+1)).put("type",item.type.equals("series")?"tv":"movie").put("season",season).put("episode",episode).put("poster",item.poster).put("dir",dir.toString()).put("magnet",magnet).put("state","queued").put("bytes",0).put("total",result.optLong("size_bytes")).put("speed",0).put("error","");set(j,"created",System.currentTimeMillis());set(j,"resolution",result.optString("resolution"));set(j,"codec",result.optString("codec"));jobs.add(j);update();start();return id;}'
new='JSONObject j=new JSONObject().put("id",id).put("title",item.title).put("description",item.description).put("tmdb",item.id.substring(item.id.lastIndexOf(\'-\')+1)).put("type",item.type.equals("series")?"tv":"movie").put("season",season).put("episode",episode).put("poster",item.poster).put("dir",dir.toString()).put("magnet",magnet).put("state","queued").put("bytes",0).put("total",result.optLong("size_bytes")).put("speed",0).put("error","");set(j,"created",System.currentTimeMillis());set(j,"resolution",result.optString("resolution"));set(j,"codec",result.optString("codec"));set(j,"health",result.optInt("health_score",result.optInt("healthScore",0)));set(j,"seeders",result.optInt("seeders",0));set(j,"leechers",result.optInt("leechers",0));jobs.add(j);update();start();return id;}'
s=rep(s,old,new,'Android queued metadata')
write(p,s)

# Replace Android Downloads list with artwork-rich cards.
p='app/src/main/java/com/zerostreams/app/MainActivity.java'; s=read(p)
replacement=r'''    TextView downloadChip(String value){TextView chip=text(value,11,INK);chip.setPadding(dp(9),dp(5),dp(9),dp(5));chip.setBackground(pill(alphaColor(INK,lightTheme?0x0D:0x12),0));return chip;}
    LinearLayout downloadCard(JSONObject j){
        String id=j.optString("id"),state=j.optString("state");LinearLayout panel=column();panel.setPadding(dp(16),dp(16),dp(16),dp(16));panel.setBackground(shape(SURFACE,googleLayout()?alphaColor(INK,0x22):0));
        LinearLayout media=new LinearLayout(this);media.setGravity(Gravity.TOP);String posterUrl=j.optString("poster");if(!posterUrl.isEmpty()){ImageView poster=new ImageView(this);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackground(shape(BG,0));poster.setClipToOutline(true);media.addView(poster,new LinearLayout.LayoutParams(dp(BuildConfig.TV?105:86),dp(BuildConfig.TV?154:126)));picture(posterUrl,poster,renderVersion);}
        LinearLayout info=column();info.setPadding(posterUrl.isEmpty()?0:dp(16),0,0,0);TextView stateBadge=text(state.equals("downloading")?"DOWNLOADING":state.equals("preparing")?"FINDING PEERS":state.equals("queued")?"QUEUED":state.toUpperCase(Locale.ROOT),10,state.equals("failed")?Color.rgb(223,115,121):ACCENT);bold(stateBadge);info.addView(stateBadge);space(info,5);TextView title=text(j.optString("title")+(j.optString("type").equals("tv")?" · S"+j.optInt("season")+" E"+j.optInt("episode"):""),BuildConfig.TV?19:17,INK);bold(title);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);info.addView(title);String description=j.optString("description");if(description.isEmpty())description="Movie description is unavailable for this older download.";TextView overview=text(description,13,MUTED);overview.setMaxLines(BuildConfig.TV?3:2);overview.setEllipsize(TextUtils.TruncateAt.END);overview.setLineSpacing(dp(2),1);space(info,5);info.addView(overview);
        LinearLayout chips=new LinearLayout(this);chips.setGravity(Gravity.CENTER_VERTICAL);for(String value:new String[]{j.optString("resolution"),j.optString("codec"),j.optInt("health")>0?"Health "+j.optInt("health")+"/100":"",j.optInt("seeders")>0?j.optInt("seeders")+" seeders":""})if(!value.isEmpty()){TextView chip=downloadChip(value);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,-2);cp.setMargins(0,dp(8),dp(7),0);chips.addView(chip,cp);}HorizontalScrollView chipScroll=new HorizontalScrollView(this);chipScroll.setHorizontalScrollBarEnabled(false);chipScroll.addView(chips);info.addView(chipScroll);TextView stats=text(downloadStats(j),13,MUTED);stats.setPadding(0,dp(9),0,0);info.addView(stats);downloadStats.put(id,stats);media.addView(info,new LinearLayout.LayoutParams(0,-2,1));panel.addView(media);
        ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setProgressTintList(android.content.res.ColorStateList.valueOf(ACCENT));bar.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(alphaColor(INK,0x16)));bar.setMax(100);bar.setProgress(downloadPercent(j));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(8));bp.setMargins(0,dp(14),0,dp(4));panel.addView(bar,bp);downloadBars.put(id,bar);if(!j.optString("error").isEmpty()){TextView error=text(j.optString("error"),13,Color.rgb(223,115,121));error.setPadding(0,dp(7),0,0);panel.addView(error);}
        if(state.equals("selecting")){JSONArray files=j.optJSONArray("files");if(files!=null)for(int f=0;f<files.length();f++){JSONObject file=files.optJSONObject(f);Button choose=button("Select "+file.optString("path")+" · "+downloadSize(file.optLong("size")),()->downloadAction(id,"select:"+file.optInt("index")));panel.addView(choose);}}
        LinearLayout actions=new LinearLayout(this);actions.setGravity(Gravity.CENTER_VERTICAL);if(Arrays.asList("queued","preparing","downloading","selecting").contains(state)){actions.addView(button("Pause",()->downloadAction(id,"pause")));actions.addView(button("Cancel",()->downloadAction(id,"cancel")));}if(Arrays.asList("paused","failed","cancelled").contains(state))actions.addView(button(state.equals("paused")?"Resume":"Retry",()->downloadAction(id,"resume")));if(state.equals("completed")){actions.addView(button("▶ Play offline",()->openDownloaded(j)));actions.addView(button("External player",()->ExternalPlayer.open(this,new File(j.optString("file")),j.optString("mime","video/*"))));actions.addView(button("Delete",()->confirmDeleteDownload(j)));}if(!Arrays.asList("queued","preparing","downloading","selecting").contains(state))actions.addView(button("Remove history",()->downloadAction(id,"history")));HorizontalScrollView actionScroll=new HorizontalScrollView(this);actionScroll.setHorizontalScrollBarEnabled(false);actionScroll.addView(actions);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.setMargins(0,dp(10),0,0);panel.addView(actionScroll,ap);return panel;
    }
    void downloadsPage(){DirectDownloads manager=DirectDownloads.get(this);JSONArray jobs=manager.list();downloadStats.clear();downloadBars.clear();downloadStates=downloadStateKey(jobs);sectionLabel(content,"TSP Search Downloads");content.addView(text("Download movies and episodes from healthy TSP matches. Active transfers now keep the poster, synopsis and torrent health visible while they download.",13,MUTED));space(content,10);content.addView(button("Get a TSP API key",this::tspKeyGuide));content.addView(button("Downloads Settings",this::torrentSearchSettings));space(content,18);String[][] groups={{"Active downloads","preparing","downloading","selecting"},{"Queued & paused","queued","paused"},{"Completed downloads","completed"},{"Needs attention","failed","missing","cancelled"}};for(String[] group:groups){sectionLabel(content,group[0]);int count=0;for(int i=0;i<jobs.length();i++){JSONObject j=jobs.optJSONObject(i);if(!Arrays.asList(group).contains(j.optString("state")))continue;count++;content.addView(downloadCard(j));space(content,12);}if(count==0)content.addView(text("No items.",13,MUTED));}manager.listener=()->{if(!foreground||!category.equals("Downloads"))return;JSONArray rows=manager.list();if(!downloadStates.equals(downloadStateKey(rows))){render();return;}for(int i=0;i<rows.length();i++){JSONObject j=rows.optJSONObject(i);TextView label=downloadStats.get(j.optString("id"));if(label!=null)label.setText(downloadStats(j));ProgressBar bar=downloadBars.get(j.optString("id"));if(bar!=null)bar.setProgress(downloadPercent(j));}};}
    String downloadStateKey'''
s=sub(s,r'    void downloadsPage\(\)\{.*?\n    String downloadStateKey',replacement,'Android download cards')
write(p,s)

# Persist richer metadata for new Windows queue items.
p='windows/torrent-downloads.cjs'; s=read(p)
old="const j={id:result.id,item,episode,dir,file:'',torrent:typeof torrent==='string'?torrent:Buffer.from(torrent).toString('base64'),binary:typeof torrent!=='string',state:'queued',bytes:0,total:result.sizeBytes||0,speed:0,peers:0,created:Date.now(),resolution:result.resolution,codec:result.codec,error:'',discovery:''};"
new="const j={id:result.id,item,episode,dir,file:'',torrent:typeof torrent==='string'?torrent:Buffer.from(torrent).toString('base64'),binary:typeof torrent!=='string',state:'queued',bytes:0,total:result.sizeBytes||0,speed:0,peers:0,created:Date.now(),resolution:result.resolution,codec:result.codec,healthScore:Number(result.healthScore)||0,seeders:Number(result.seeders)||0,leechers:Number(result.leechers)||0,error:'',discovery:''};"
s=rep(s,old,new,'Windows queued metadata')
write(p,s)

# Windows Downloads page styled like the torrent search result cards.
p='windows/ui/downloads.js'; s=read(p)
anchor="function torrentHealthClass(score){return score>=85?'excellent':score>=70?'good':'fair';}"
helper=r'''function downloadJobCard(j){const item=j.item||{},poster=item.poster||'',description=item.overview||'Movie description is unavailable for this older download.',health=Number(j.healthScore)||0,percent=j.total?Math.max(0,Math.min(100,100*j.bytes/j.total)):0,state=String(j.state||'queued'),active=['metadata','queued','downloading','selecting'].includes(state);const stateLabel=state==='metadata'?'Finding peers':state==='downloading'?'Downloading':state==='completed'?'Ready offline':state.charAt(0).toUpperCase()+state.slice(1);return '<article class="download-media-card '+(active?'active':'')+'"><div class="download-media-art">'+(poster?'<img src="'+escape(poster)+'" alt="">':'<div class="download-media-empty">Z</div>')+'</div><div class="download-media-body"><div class="download-media-head"><div><span class="download-state '+escape(state)+'">'+escape(stateLabel)+'</span><h3>'+escape(j.title)+'</h3></div><strong class="download-percent">'+Math.round(percent)+'%</strong></div><p class="download-overview">'+escape(description)+'</p><div class="torrent-chips">'+(j.resolution?'<span>'+escape(j.resolution)+'</span>':'')+(j.codec?'<span>'+escape(j.codec)+'</span>':'')+(j.total?'<span>'+size(j.total)+'</span>':'')+(health?'<span class="health '+torrentHealthClass(health)+'">Health '+health+'/100</span>':'')+(j.seeders?'<span>'+j.seeders+' seeders</span>':'')+'</div><div class="download-transfer"><div><b>'+size(j.bytes)+'</b> / '+size(j.total)+' · '+size(j.speed)+'/s · '+(j.peers||0)+' peers'+(j.speed>0&&j.total>j.bytes?' · '+Math.ceil((j.total-j.bytes)/j.speed/60)+' min remaining':'')+'</div><progress max="100" value="'+percent+'"></progress></div>'+(j.discovery?'<p class="download-discovery">'+escape(j.discovery)+'</p>':'')+(j.error?'<p class="download-error">'+escape(j.error)+'</p>':'')+(state==='selecting'?'<div class="download-file-list">'+(j.files||[]).map(f=>'<button data-job="'+j.id+'" data-job-action="select" data-file="'+escape(f.path)+'">Select '+escape(f.path)+' · '+size(f.size)+'</button>').join('')+'</div>':'')+'<div class="actions download-actions">'+(active?'<button data-job="'+j.id+'" data-job-action="pause">Pause</button><button data-job="'+j.id+'" data-job-action="cancel">Cancel</button>':'')+(['paused','failed','cancelled'].includes(state)?'<button class="primary" data-job="'+j.id+'" data-job-action="resume">Resume / Retry</button>':'')+(state==='completed'?'<button class="primary" data-job="'+j.id+'" data-job-action="open">▶ Play offline</button><button data-job="'+j.id+'" data-job-action="external">External player</button><button data-job="'+j.id+'" data-job-action="delete">Delete Video</button>':'')+(!active?'<button data-job="'+j.id+'" data-job-action="history">Remove from History</button>':'')+'</div></div></article>';}
'''
s=rep(s,anchor,anchor+'\n'+helper,'Windows download card helper')
old="last.map(j=>'<section class=\"download-card\"><h3>'+escape(j.title)+'</h3><p>'+escape(j.state)+' · '+size(j.bytes)+' / '+size(j.total)+' · '+size(j.speed)+'/s · '+(j.peers||0)+' peers'+(j.speed>0&&j.total>j.bytes?' · '+Math.ceil((j.total-j.bytes)/j.speed/60)+' min remaining':'')+'</p><progress max=\"100\" value=\"'+(j.total?100*j.bytes/j.total:0)+'\"></progress><p>'+escape(j.error||'')+'</p><div class=\"actions\">'+(j.state==='selecting'?(j.files||[]).map(f=>'<button data-job=\"'+j.id+'\" data-job-action=\"select\" data-file=\"'+escape(f.path)+'\">Select '+escape(f.path)+' · '+size(f.size)+'</button>').join(''):'')+(['metadata','queued','downloading','selecting'].includes(j.state)?'<button data-job=\"'+j.id+'\" data-job-action=\"pause\">Pause</button><button data-job=\"'+j.id+'\" data-job-action=\"cancel\">Cancel</button>':'')+(['paused','failed','cancelled'].includes(j.state)?'<button data-job=\"'+j.id+'\" data-job-action=\"resume\">Resume / Retry</button>':'')+(j.state==='completed'?'<button data-job=\"'+j.id+'\" data-job-action=\"open\">Play offline</button><button data-job=\"'+j.id+'\" data-job-action=\"external\">Open in external player</button><button data-job=\"'+j.id+'\" data-job-action=\"delete\">Delete Video</button>':'')+(!['metadata','queued','downloading','selecting'].includes(j.state)?'<button data-job=\"'+j.id+'\" data-job-action=\"history\">Remove from History</button>':'')+'</div></section>').join('')"
s=rep(s,old,"last.map(downloadJobCard).join('')",'Windows render cards')
write(p,s)

# Theme-aware transfer card styling, intentionally borrowing visual language from torrent result cards.
p='windows/ui/layouts.css'; s=read(p); s += r'''

/* 1.9 Downloads library cards */
.download-media-card{display:grid;grid-template-columns:118px minmax(0,1fr);gap:18px;margin:14px 0;padding:16px;border:1px solid color-mix(in srgb,var(--ink) 12%,transparent);border-radius:18px;background:color-mix(in srgb,var(--surface) 88%,transparent);box-shadow:0 8px 28px #0002;overflow:hidden}.download-media-card.active{border-color:color-mix(in srgb,var(--mint) 35%,transparent)}.download-media-art{width:118px;aspect-ratio:2/3;border-radius:13px;overflow:hidden;background:color-mix(in srgb,var(--ink) 7%,var(--surface));align-self:start}.download-media-art img{width:100%;height:100%;object-fit:cover}.download-media-empty{width:100%;height:100%;display:grid;place-items:center;font-size:32px;font-weight:800;color:var(--mint)}.download-media-body{min-width:0}.download-media-head{display:flex;align-items:flex-start;justify-content:space-between;gap:15px}.download-media-head h3{margin:5px 0 0;font-size:20px}.download-state{display:inline-block;font-size:10px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:var(--mint)}.download-state.failed,.download-state.missing,.download-state.cancelled{color:#df7379}.download-state.completed{color:#6ed69a}.download-percent{font-size:21px;color:var(--ink);white-space:nowrap}.download-overview{margin:9px 0 11px;max-width:900px;font-size:13px;line-height:1.55;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.download-transfer{font-size:12px;color:var(--muted);margin-top:8px}.download-transfer b{color:var(--ink)}.download-transfer progress{width:100%;height:8px;margin-top:8px;border:0;accent-color:var(--mint)}.download-transfer progress::-webkit-progress-bar{background:color-mix(in srgb,var(--ink) 8%,transparent);border-radius:999px}.download-transfer progress::-webkit-progress-value{background:var(--mint);border-radius:999px}.download-discovery{margin:8px 0 0;font-size:12px;color:var(--muted)}.download-error{margin:8px 0 0;font-size:12px;color:#df7379}.download-actions{margin-top:13px}.download-actions button{padding:8px 13px}.download-file-list{display:grid;gap:7px;margin-top:10px}.download-file-list button{text-align:left}.download-media-card .torrent-chips{margin:5px 0 7px}:root[data-layout="youtube"] .download-media-card{background:#212121;border-color:#353535}:root[data-layout="youtube"] .download-media-card.active{border-color:#5c5c5c}:root[data-layout="youtube"] .download-state{color:#f1f1f1}@media(max-width:700px){.download-media-card{grid-template-columns:82px minmax(0,1fr);gap:12px;padding:12px}.download-media-art{width:82px}.download-media-head h3{font-size:17px}.download-overview{-webkit-line-clamp:3}.download-percent{font-size:16px}}
'''; write(p,s)

print('1.9 download UI polish applied')
