from pathlib import Path

main_path=Path('app/src/main/java/com/zerostreams/app/MainActivity.java')
api_path=Path('app/src/main/java/com/zerostreams/app/ContentApi.java')
collections_path=Path('app/src/main/java/com/zerostreams/app/DiscoveryCollections.java')
main=main_path.read_text()
api=api_path.read_text()
collections=collections_path.read_text()

def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'missing target: {label}')
    return text.replace(old,new,1)

# #22 centralized brand treatment.
main=replace_once(main,
'    void bold(TextView t){t.setTypeface(null,Typeface.BOLD);}\n',
'''    void bold(TextView t){t.setTypeface(null,Typeface.BOLD);}\n    TextView brandText(int size){TextView logo=text("ZeroPlay",size,INK);bold(logo);android.text.SpannableString styled=new android.text.SpannableString("ZeroPlay");styled.setSpan(new android.text.style.ForegroundColorSpan(INK),0,4,android.text.Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);styled.setSpan(new android.text.style.ForegroundColorSpan(ACCENT),4,8,android.text.Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);logo.setText(styled);logo.setLetterSpacing(.055f);logo.setSingleLine(true);logo.setContentDescription("ZeroPlay");return logo;}\n''','brand helper')
main=replace_once(main,'TextView z=text("Z",34,ACCENT);bold(z);z.setFocusable(true);','TextView z=brandText(22);z.setFocusable(true);','classic brand')
main=replace_once(main,'TextView logo=text("ZEROPLAY",googleLayout()?(BuildConfig.TV?25:22):(BuildConfig.TV?23:19),INK);eggLogo=logo;bold(logo);','TextView logo=brandText(googleLayout()?(BuildConfig.TV?25:22):(BuildConfig.TV?23:19));eggLogo=logo;','header brand')
main=replace_once(main,'TextView brand=text("ZEROPLAY",BuildConfig.TV?23:20,INK);bold(brand);brand.setLetterSpacing(.07f);','TextView brand=brandText(BuildConfig.TV?23:20);','modern brand')

# Track a surprise result only while its detail page is open (#21), and unique category art (#20).
main=replace_once(main,'private int genreId,surpriseVersion;private boolean surpriseLoading,genreHasMore;','private int genreId,surpriseVersion;private boolean surpriseLoading,genreHasMore;private String surpriseDetailId="";')
main=replace_once(main,'private final Set<String> genreArtworkLoading=new HashSet<>();','private final Set<String> genreArtworkLoading=new HashSet<>();private final Set<String> categoryArtworkUsed=new HashSet<>();')
main=replace_once(main,'status.setText("TMDB surprise · "+item.title);details(item);','status.setText("TMDB surprise · "+item.title);surpriseDetailId=item.id;details(item);','#21 surprise details marker')

# #21 temporary Surprise Me Again button inside the surprise result detail page.
main=replace_once(main,'detailsOpen=true;final JSONObject[] detailData={null};','detailsOpen=true;final JSONObject[] detailData={null};final AlertDialog[] detailDialog={null};')
main=replace_once(main,
'        LinearLayout actions=column();actions.addView(play,new LinearLayout.LayoutParams(-1,dp(48)));space(actions,8);actions.addView(source,new LinearLayout.LayoutParams(-1,dp(48)));if(item.id.startsWith("tmdb-")){space(actions,8);Button download=button("Download",()->downloadTitle(item));actions.addView(download,new LinearLayout.LayoutParams(-1,dp(48)));}\n',
'''        LinearLayout actions=column();actions.addView(play,new LinearLayout.LayoutParams(-1,dp(48)));space(actions,8);actions.addView(source,new LinearLayout.LayoutParams(-1,dp(48)));if(item.id.startsWith("tmdb-")){space(actions,8);Button download=button("Download",()->downloadTitle(item));actions.addView(download,new LinearLayout.LayoutParams(-1,dp(48)));}if(item.id.equals(surpriseDetailId)){space(actions,8);Button again=button("🎲 Surprise me again",()->{if(detailDialog[0]!=null)detailDialog[0].dismiss();surpriseMovie();});again.setTextColor(BG);again.setBackground(shape(ACCENT,0));again.setOnFocusChangeListener((v,f)->v.setBackground(shape(ACCENT,f?INK:0)));actions.addView(again,new LinearLayout.LayoutParams(-1,dp(48)));}\n''','#21 temporary reroll button')
main=replace_once(main,'AlertDialog dialog=new AlertDialog.Builder(this).setView(scene).setNegativeButton("Close",null).create();dialog.setOnDismissListener(d->{detailsOpen=false;if(!isDestroyed())render();});','AlertDialog dialog=new AlertDialog.Builder(this).setView(scene).setNegativeButton("Close",null).create();detailDialog[0]=dialog;dialog.setOnDismissListener(d->{detailsOpen=false;if(item.id.equals(surpriseDetailId))surpriseDetailId="";if(!isDestroyed())render();});','#21 dialog holder')

# #19 cast cards become focusable/clickable and open exact TMDB person credits.
old_cast='for(int i=0;i<Math.min(10,cast.length());i++){JSONObject actor=cast.optJSONObject(i);if(actor==null)continue;LinearLayout person=column();person.setGravity(Gravity.CENTER_HORIZONTAL);ImageView face=new ImageView(this);face.setScaleType(ImageView.ScaleType.CENTER_CROP);GradientDrawable circle=new GradientDrawable();circle.setShape(GradientDrawable.OVAL);circle.setColor(SURFACE);face.setBackground(circle);face.setClipToOutline(true);person.addView(face,new LinearLayout.LayoutParams(dp(64),dp(64)));String photo=ContentApi.image(actor.optString("profile_path"),"w185");if(!photo.isEmpty())picture(photo,face,token);space(person,6);TextView name=text(actor.optString("name"),12,INK);name.setGravity(Gravity.CENTER);name.setSingleLine(true);name.setEllipsize(TextUtils.TruncateAt.END);person.addView(name,new LinearLayout.LayoutParams(-1,-2));TextView role=text(actor.optString("character"),11,MUTED);role.setGravity(Gravity.CENTER);role.setSingleLine(true);role.setEllipsize(TextUtils.TruncateAt.END);person.addView(role,new LinearLayout.LayoutParams(-1,-2));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(100),-2);pp.setMargins(0,0,dp(8),0);people.addView(person,pp);}'
new_cast='for(int i=0;i<Math.min(12,cast.length());i++){JSONObject actor=cast.optJSONObject(i);if(actor==null)continue;int personId=actor.optInt("id");String personName=actor.optString("name");LinearLayout person=column();person.setGravity(Gravity.CENTER_HORIZONTAL);person.setPadding(dp(6),dp(6),dp(6),dp(8));person.setFocusable(personId>0);person.setClickable(personId>0);person.setContentDescription("See titles starring "+personName);person.setBackground(shape(Color.TRANSPARENT,0));person.setOnFocusChangeListener((v,f)->person.setBackground(shape(f?alphaColor(SURFACE,0xD8):Color.TRANSPARENT,f?ACCENT:0)));if(personId>0)person.setOnClickListener(v->personTitles(personId,personName));ImageView face=new ImageView(this);face.setScaleType(ImageView.ScaleType.CENTER_CROP);GradientDrawable circle=new GradientDrawable();circle.setShape(GradientDrawable.OVAL);circle.setColor(SURFACE);face.setBackground(circle);face.setClipToOutline(true);person.addView(face,new LinearLayout.LayoutParams(dp(64),dp(64)));String photo=ContentApi.image(actor.optString("profile_path"),"w185");if(!photo.isEmpty())picture(photo,face,token);space(person,6);TextView name=text(personName,12,INK);name.setGravity(Gravity.CENTER);name.setSingleLine(true);name.setEllipsize(TextUtils.TruncateAt.END);person.addView(name,new LinearLayout.LayoutParams(-1,-2));TextView role=text(actor.optString("character"),11,MUTED);role.setGravity(Gravity.CENTER);role.setSingleLine(true);role.setEllipsize(TextUtils.TruncateAt.END);person.addView(role,new LinearLayout.LayoutParams(-1,-2));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(112),-2);pp.setMargins(0,0,dp(8),0);people.addView(person,pp);}'
main=replace_once(main,old_cast,new_cast,'#19 cast cards')

insert_person='''    void personTitles(int personId,String personName){\n        if(personId<=0)return;message("Loading titles starring "+personName+"…");String key=tmdbKey();io.execute(()->{try{List<Catalog.Item> titles=ContentApi.personCredits(personId,key);ui.post(()->{if(isDestroyed())return;if(titles.isEmpty()){message("No movie or series credits found for "+personName);return;}LinearLayout panel=column();panel.setPadding(dp(16),dp(12),dp(16),dp(16));panel.addView(text("Movies and series featuring "+personName,13,MUTED));space(panel,12);int columns=BuildConfig.TV?4:2;for(int i=0;i<Math.min(32,titles.size());i+=columns){LinearLayout row=new LinearLayout(this);for(int c=0;c<columns;c++){LinearLayout.LayoutParams cell=new LinearLayout.LayoutParams(0,-2,1);cell.setMargins(0,0,dp(c==columns-1?0:10),dp(12));if(i+c<titles.size())row.addView(card(titles.get(i+c),renderVersion),cell);else row.addView(new View(this),cell);}panel.addView(row);}ScrollView scroller=new ScrollView(this);scroller.setFillViewport(true);scroller.addView(panel);AlertDialog results=new AlertDialog.Builder(this).setTitle(personName).setView(scroller).setNegativeButton("Close",null).create();results.show();if(results.getWindow()!=null){results.getWindow().setBackgroundDrawable(shape(BG,0));results.getWindow().setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(28),dp(BuildConfig.TV?980:620)),Math.min(getResources().getDisplayMetrics().heightPixels-dp(56),dp(650)));}ui.post(visiblePictures);});}catch(Exception e){ui.post(()->{if(!isDestroyed())message("Could not load "+personName+"'s titles right now.");});}});\n    }\n'''
main=replace_once(main,'    void trailer(JSONObject data){',insert_person+'    void trailer(JSONObject data){','#19 person titles method')

# #20 cleaner category header and cards. Artwork remains live TMDB artwork, no repeated icon treatment.
main=replace_once(main,'sectionLabel(content,"Categories");content.addView(text("Choose a genre and explore more movies and series.",14,MUTED));','TextView categoryHeading=text("Explore Categories",BuildConfig.TV?32:27,INK);bold(categoryHeading);content.addView(categoryHeading);space(content,6);content.addView(text("Browse genres, cultures and collections with artwork that changes with current titles.",14,MUTED));')
main=replace_once(main,'JSONArray tiles=new JSONArray();for(int g=0;g<genres.length();g++)tiles.put(genres.optJSONObject(g));','categoryArtworkUsed.clear();JSONArray tiles=new JSONArray();for(int g=0;g<genres.length();g++)tiles.put(genres.optJSONObject(g));')
old_tile='ImageView art=new ImageView(this);art.setScaleType(ImageView.ScaleType.CENTER_CROP);tile.addView(art,new FrameLayout.LayoutParams(-1,-1));genrePicture(genreType,id,art,renderVersion);View shade=new View(this);shade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0x20101824,0xEE0C1019}));tile.addView(shade,new FrameLayout.LayoutParams(-1,-1));LinearLayout caption=column();caption.setPadding(dp(14),dp(14),dp(14),dp(14));TextView title=text(name,BuildConfig.TV?19:16,Color.WHITE);bold(title);caption.addView(title);caption.addView(text("Explore →",12,0xFFB8D5CE));tile.addView(caption,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));'
new_tile='ImageView art=new ImageView(this);art.setScaleType(ImageView.ScaleType.CENTER_CROP);if(Build.VERSION.SDK_INT>=31)art.setRenderEffect(android.graphics.RenderEffect.createBlurEffect(dp(1.15f),dp(1.15f),android.graphics.Shader.TileMode.CLAMP));tile.addView(art,new FrameLayout.LayoutParams(-1,-1));genrePicture(genreType,id,art,renderVersion);View shade=new View(this);shade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0x48101824,0xF20A0D14}));tile.addView(shade,new FrameLayout.LayoutParams(-1,-1));LinearLayout caption=column();caption.setPadding(dp(16),dp(16),dp(16),dp(16));TextView title=text(name,BuildConfig.TV?25:20,ACCENT);bold(title);title.setShadowLayer(dp(3),0,dp(1),Color.BLACK);caption.addView(title);TextView sub=text(genreType.equals("tv")?"Series collection":"Movie collection",12,Color.WHITE);bold(sub);caption.addView(sub);tile.addView(caption,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));'
main=replace_once(main,old_tile,new_tile,'#20 category tile styling')

# Unique art choice: gather candidate art, pick the first artwork not already used on this category render.
old_loader='String apiKey=tmdbKey();io.execute(()->{String url="";try{List<Catalog.Item> examples=ContentApi.tmdbRows((task.id==-16?ContentApi.animeData(apiKey,task.type,1):ContentApi.categoryData(apiKey,task.type,task.id,1)).getJSONArray("results"),task.type,false);for(Catalog.Item item:examples){url=item.raw.optString("backdrop");if(url.isEmpty())url=item.poster;if(!url.isEmpty())break;}}catch(Exception ignored){}final String art=url;ui.post(()->{genreArtworkLoading.remove(key);if(isDestroyed())return;if(!art.isEmpty()){genreArtwork.put(key,art);if(task.token==renderVersion&&category.equals("Categories"))picture(art,task.image,task.token);ui.post(visiblePictures);}});});}'
new_loader='String apiKey=tmdbKey();io.execute(()->{List<String> candidates=new ArrayList<>();try{List<Catalog.Item> examples=ContentApi.tmdbRows((task.id==-16?ContentApi.animeData(apiKey,task.type,1):ContentApi.categoryData(apiKey,task.type,task.id,1)).getJSONArray("results"),task.type,false);for(Catalog.Item item:examples){String candidate=item.raw.optString("backdrop");if(candidate.isEmpty())candidate=item.poster;if(!candidate.isEmpty()&&!candidates.contains(candidate))candidates.add(candidate);if(candidates.size()>=10)break;}}catch(Exception ignored){}ui.post(()->{genreArtworkLoading.remove(key);if(isDestroyed())return;String art="";for(String candidate:candidates)if(!categoryArtworkUsed.contains(candidate)){art=candidate;break;}if(art.isEmpty()&&!candidates.isEmpty())art=candidates.get(Math.floorMod(task.id,candidates.size()));if(!art.isEmpty()){categoryArtworkUsed.add(art);genreArtwork.put(key,art);if(task.token==renderVersion&&category.equals("Categories"))picture(art,task.image,task.token);ui.post(visiblePictures);}});});}'
main=replace_once(main,old_loader,new_loader,'#20 unique category artwork')

# ContentApi exact person combined credits (#19).
api=replace_once(api,'    static JSONArray providers(String key,String type,String region) throws Exception {', '''    static List<Catalog.Item> personCredits(int personId,String key) throws Exception {\n        if(personId<=0)throw new IOException("Invalid person ID");JSONArray cast=tmdb("/person/"+personId+"/combined_credits",key,"").optJSONArray("cast");if(cast==null)return new ArrayList<>();List<JSONObject> raw=new ArrayList<>();for(int i=0;i<cast.length();i++){JSONObject credit=cast.optJSONObject(i);if(credit!=null&&!credit.optBoolean("adult")&&(credit.optString("media_type").equals("movie")||credit.optString("media_type").equals("tv")))raw.add(credit);}Collections.sort(raw,(a,b)->Double.compare(b.optDouble("popularity",0),a.optDouble("popularity",0)));JSONArray ordered=new JSONArray();HashSet<String> seen=new HashSet<>();for(JSONObject credit:raw){String id=credit.optString("media_type")+":"+credit.optLong("id");if(seen.add(id))ordered.put(credit);if(ordered.length()>=40)break;}return tmdbRows(ordered,"movie",false);\n    }\n    static JSONArray providers(String key,String type,String region) throws Exception {''','#19 ContentApi person credits')

# #20 more discovery collections.
collections='''package com.zerostreams.app;\nfinal class DiscoveryCollections {static final int[] IDS={-101,-102,-103,-104,-105,-106,-107,-108,-109,-110,-111,-112,-113};static final String[] NAMES={"Japanese titles","Korean titles","Filipino titles","French titles","Spanish titles","Hindi titles","Chinese titles","Thai titles","Indonesian titles","Portuguese titles","German titles","Italian titles","Turkish titles"};static final String[] LANGUAGES={"ja","ko","tl","fr","es","hi","zh","th","id","pt","de","it","tr"};static String language(int id){for(int i=0;i<IDS.length;i++)if(IDS[i]==id)return LANGUAGES[i];throw new IllegalArgumentException("Unknown collection");}}'''

main_path.write_text(main)
api_path.write_text(api)
collections_path.write_text(collections)
print('Applied fixes #19-#22')
