const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events'),{PlayerHost}=require('../player-host.cjs');
function fixture(){const main=new EventEmitter();Object.assign(main,{full:false,isFullScreen(){return this.full;},setFullScreen(value){this.full=value;},isDestroyed:()=>false,getContentSize:()=>[1440,900],contentView:{children:[],addChildView(v){this.children.push(v);},removeChildView(v){this.children=this.children.filter(x=>x!==v);}}});const makeView=()=>{const webContents=new EventEmitter();Object.assign(webContents,{dead:false,isDestroyed(){return this.dead;},close(){this.dead=true;},mainFrame:{framesInSubtree:[{executeJavaScript:async()=>{}}]}});return {webContents,setBounds(value){this.bounds=value;},setVisible(value){this.visible=value;}};};return {main,view:makeView(),toolbar:makeView()};}
test('Player is embedded in the existing content view and resizes to its full bounds',()=>{const f=fixture(),host=new PlayerHost(f.main,f.view,f.toolbar);assert.equal(f.main.contentView.children.length,2);assert.deepEqual(f.view.bounds,{x:0,y:0,width:1440,height:900});f.main.getContentSize=()=>[1920,1080];f.main.emit('resize');assert.equal(f.view.bounds.width,1920);host.close();assert.equal(f.main.contentView.children.length,0);assert.equal(f.view.webContents.dead,true);assert.equal(f.toolbar.webContents.dead,true);assert.equal(f.main.listenerCount('resize'),0);});
test('HTML player fullscreen makes the owning window fullscreen and hides app chrome',()=>{const f=fixture(),host=new PlayerHost(f.main,f.view,f.toolbar);f.view.webContents.emit('enter-html-full-screen');assert.equal(f.main.full,true);assert.equal(f.toolbar.visible,false);f.view.webContents.emit('leave-html-full-screen');assert.equal(f.main.full,false);host.close();});
test('Escape/F11 can leave fullscreen without closing the movie',async()=>{const f=fixture(),host=new PlayerHost(f.main,f.view,f.toolbar);await host.toggleFullscreen();assert.equal(f.main.full,true);await host.exitFullscreen();assert.equal(f.main.full,false);assert.equal(f.view.webContents.dead,false);host.close();});
test('Returning to browsing preserves the original window fullscreen state',()=>{const f=fixture();f.main.full=true;const host=new PlayerHost(f.main,f.view,f.toolbar);host.close();assert.equal(f.main.full,true);});

test('Sports uses a bottom overlay that remains reachable in native fullscreen',async()=>{const f=fixture(),host=new PlayerHost(f.main,f.view,f.toolbar,{bottom:true});assert.equal(f.toolbar.bounds.y,856);await host.toggleFullscreen();host.activity();assert.equal(f.toolbar.visible,true);assert.equal(f.view.bounds.height,900);host.close();});
test('Sports bar hides after inactivity even when a clicked control retains focus, then wakes on input',t=>{t.mock.timers.enable({apis:['setTimeout']});const f=fixture();let focused=0;f.toolbar.webContents.isFocused=()=>true;f.view.webContents.focus=()=>focused++;const host=new PlayerHost(f.main,f.view,f.toolbar,{bottom:true});t.mock.timers.tick(3001);assert.equal(f.toolbar.visible,false);assert.equal(focused,1);host.activity();assert.equal(f.toolbar.visible,true);t.mock.timers.tick(2000);host.activity();t.mock.timers.tick(2000);assert.equal(f.toolbar.visible,true);t.mock.timers.tick(1001);assert.equal(f.toolbar.visible,false);host.close();});
