const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {DownloadManager,filename}=require('../rawcast-downloads.cjs'),{RawCast}=require('../rawcast.cjs');
const movie={id:550,type:'movie',title:'A: Movie?',date:'1999-01-01'},body=Buffer.concat([Buffer.from([0,0,0,24]),Buffer.from('ftypisom'),Buffer.alloc(4096)]);
async function until(check){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,10));}throw Error('Download timed out');}
function temporary(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'zero-downloads-'));return root;}
test('Filenames cannot escape storage or use Windows reserved names',()=>{assert.equal(filename(movie),'A_ Movie_ (1999).mp4');assert.ok(filename({...movie,title:'CON',date:''}).startsWith('ZeroPlay -'));assert.equal(filename({...movie,type:'tv',title:'Series'},{season:1,episode:3,title:'Episode'}),'Series - S01E03 - Episode.mp4');});
test('Queue completes, prevents duplicates, history preserves file, deletion removes file',async t=>{const root=temporary(t),manager=new DownloadManager(root,async()=>({url:'https://example.test/video.mp4'}),()=>{},async()=>new Response(body,{headers:{'Content-Length':String(body.length),'Content-Type':'video/mp4'}}));t.after(()=>manager.close());const id=await manager.add(movie);assert.equal(await manager.add(movie),id);await until(()=>manager.list()[0].state==='completed');const file=await manager.action(id,'open');assert.ok(fs.existsSync(file));await manager.action(id,'history');assert.ok(fs.existsSync(file));const second=await manager.add({...movie,id:551});await until(()=>manager.list()[0].state==='completed');const other=await manager.action(second,'open');await manager.action(second,'delete');assert.equal(fs.existsSync(other),false);assert.equal(manager.list().length,0);});
test('Restart resumes a partial file with Range and detects externally deleted files',async t=>{const root=temporary(t),file=path.join(root,'Movie.mp4');fs.writeFileSync(file+'.part',body.subarray(0,100));fs.writeFileSync(path.join(root,'downloads.json'),JSON.stringify([{id:'test',item:movie,episode:{},file,state:'downloading',bytes:100,total:body.length,attempts:0}]));let request;const manager=new DownloadManager(root,async()=>({url:'https://example.test/video.mp4'}),()=>{},async(_u,options)=>{request=options;return new Response(body.subarray(100),{status:206,headers:{'Content-Range':`bytes 100-${body.length-1}/${body.length}`,'Content-Type':'video/mp4'}});});t.after(()=>manager.close());await until(()=>manager.list()[0].state==='completed');assert.equal(request.headers.Range,'bytes=100-');assert.deepEqual(fs.readFileSync(file),body);fs.unlinkSync(file);assert.equal(manager.list()[0].state,'missing');await assert.rejects(manager.action('test','open'),/missing/);});
test('HTML response is never recorded as a downloaded video',async t=>{const manager=new DownloadManager(temporary(t),async()=>({url:'https://example.test/file'}),()=>{},async()=>new Response('<html>Error</html>',{headers:{'Content-Type':'text/html'}}));t.after(()=>manager.close());await manager.add(movie);await until(()=>manager.list()[0].state==='failed');assert.equal(manager.list()[0].state,'failed');});
test('RawCast resolves only direct MP4, caches requests and reports authoritative quota',async()=>{let calls=0;const api=new RawCast(()=> 'local-fixture',async()=>{calls++;return new Response(JSON.stringify({format:'mp4',downloadUrl:'https://rawcast.space/v1/download/token'}),{headers:{'X-RateLimit-Limit':'1000','X-RateLimit-Remaining':'755','X-RateLimit-Reset':'1800000000'}});});const a=await api.resolve(movie);assert.equal((await api.resolve(movie)).url,a.url);assert.equal(calls,1);assert.equal(api.usage.used,245);assert.equal(api.usage.remaining,755);});
test('Missing key and HLS cannot be used for downloads',async()=>{await assert.rejects(new RawCast(()=> '').resolve(movie),/key required/);const api=new RawCast(()=> 'fixture',async()=>new Response(JSON.stringify({format:'hls',url:'https://example.test/video.m3u8'})));assert.equal(await api.resolve(movie),null);});
test('Mislabeled MP4 is rejected before its payload is saved',async t=>{const root=temporary(t),manager=new DownloadManager(root,async()=>({url:'https://example.test/video'}),()=>{},async()=>new Response(Buffer.alloc(8192),{headers:{'Content-Type':'application/octet-stream'}}));t.after(()=>manager.close());await manager.add(movie);await until(()=>manager.list()[0].state==='failed');assert.equal(fs.statSync(manager.list()[0].file+'.part').size,0);});
test('Range-ignoring servers restart the partial file instead of appending corrupt data',async t=>{const root=temporary(t),file=path.join(root,'Restart.mp4');fs.writeFileSync(file+'.part',body.subarray(0,100));fs.writeFileSync(path.join(root,'downloads.json'),JSON.stringify([{id:'restart',item:movie,episode:{},file,state:'downloading',bytes:100,total:body.length,attempts:0}]));const manager=new DownloadManager(root,async()=>({url:'https://example.test/video'}),()=>{},async()=>new Response(body,{headers:{'Content-Type':'video/mp4','Content-Length':String(body.length)}}));t.after(()=>manager.close());await until(()=>manager.list()[0].state==='completed');assert.deepEqual(fs.readFileSync(file),body);});
test('Invalid Content-Range fails without finalizing a file',async t=>{const root=temporary(t),file=path.join(root,'Invalid.mp4');fs.writeFileSync(file+'.part',body.subarray(0,100));fs.writeFileSync(path.join(root,'downloads.json'),JSON.stringify([{id:'invalid',item:movie,episode:{},file,state:'downloading',bytes:100,total:body.length,attempts:0}]));const manager=new DownloadManager(root,async()=>({url:'https://example.test/video'}),()=>{},async()=>new Response(body,{status:206,headers:{'Content-Range':`bytes 0-${body.length-1}/${body.length}`}}));t.after(()=>manager.close());await until(()=>manager.list()[0].state==='failed');assert.equal(fs.existsSync(file),false);assert.equal(fs.statSync(file+'.part').size,100);});
test('Actual MKV and WebM containers retain the correct extension and require device validation',async t=>{for(const format of ['mkv','webm']){const bytes=fs.readFileSync(path.join(__dirname,'video/fixture.'+format));let checked;const manager=new DownloadManager(temporary(t),async()=>({url:'https://example.test/mislabeled.mp4'}),()=>{},async()=>new Response(bytes,{headers:{'Content-Type':'video/mp4','Content-Length':String(bytes.length)}}),async(file,actual)=>{checked=actual;return true;});t.after(()=>manager.close());const id=await manager.add(movie);await until(()=>manager.list()[0].state==='completed');assert.equal(checked,format);assert.equal(path.extname(await manager.action(id,'open')),'.'+format);}});
test('Unsupported device codecs are not marked completed',async t=>{const manager=new DownloadManager(temporary(t),async()=>({url:'https://example.test/video.mp4'}),()=>{},async()=>new Response(body),async()=>false);t.after(()=>manager.close());await manager.add(movie);await until(()=>manager.list()[0].state==='failed');assert.match(manager.list()[0].error,/unsupported/);assert.equal(fs.existsSync(manager.list()[0].file),false);});
test('Unreadable successful API response does not report a connected key',async()=>{const api=new RawCast(()=> 'fixture',async()=>new Response('<html>Not API JSON</html>'));await assert.rejects(api.test(),/unreadable/);});
