const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const updater=require('../updater.cjs'),versions=require('../version-manager.cjs');
test('update version comparison handles tags and patch versions',()=>{assert.deepEqual(updater.cleanVersion('v2.1.0'),[2,1,0]);assert.equal(updater.newer('2.1','2.0.3'),true);assert.equal(updater.newer('2.1.0','2.1'),false);});
test('versioned launcher treats release tags with trailing zeroes as the same app version',()=>{assert.equal(versions.sameVersion('2.2','2.2.0'),true);assert.equal(versions.sameVersion('v2.2.0','2.2'),true);assert.equal(versions.sameVersion('2.2.1','2.2'),false);});
test('updater ignores demo releases',()=>{assert.equal(updater.testRelease({tag_name:'v9.9.9-TEST'}),true);assert.equal(updater.testRelease({tag_name:'v2.1-DEMO'}),true);assert.equal(updater.testRelease({tag_name:'v2.1'}),false);});
test('Windows updater delegates installation to ZeroPlayUpdater.exe',()=>{const source=fs.readFileSync(path.join(__dirname,'..','updater.cjs'),'utf8');assert.match(source,/ZeroPlayUpdater\.exe/);assert.match(source,/--wait-pid/);assert.doesNotMatch(source,/tar\.exe/);assert.doesNotMatch(source,/Expand-Archive/);assert.doesNotMatch(source,/robocopy\.exe/);});
test('standalone helper owns ZIP extraction and version activation',()=>{const source=fs.readFileSync(path.join(__dirname,'..','updater-helper','Program.cs'),'utf8');assert.match(source,/ZipFile\.ExtractToDirectory/);assert.match(source,/current\.json/);assert.match(source,/ZeroPlayUpdater-error\.txt/);});
test('stable launcher has confirmation and rollback handshake',()=>{const source=fs.readFileSync(path.join(__dirname,'..','version-manager.cjs'),'utf8');assert.match(source,/pending:true/);assert.match(source,/confirmCurrent/);assert.match(source,/sameVersion/);assert.match(source,/rollback/);assert.match(source,/current\.json/);});
test('Windows hero trailer follows heroPicks rather than trending',()=>{const source=fs.readFileSync(path.join(__dirname,'..','ui','experience.js'),'utf8');assert.match(source,/heroPicks\(\)/);assert.doesNotMatch(source,/homeData\.trending\|\|\[\]\)\.filter\(i=>i\.backdrop\)\.slice\(0,6\)\[heroIndex\]/);});
